; ########################################################################################
; # Generated by the active disassembly feature of the Exodus emulation platform
; #
; # Creation Date:   2020-12-1 23:47:47
; # Analysis Region: 0x00003628 - 0x00003682
; ########################################################################################

 org $00003628

	MOVEM.l	A1/A0/D3/D2/D1/D0, -(A7)
	MOVEA.l	A0, A1
	MOVEA.w	#$C000, A0
	MOVE.w	D0, D3
loc_00003634:
	CLR.w	D2
	MOVE.b	(A1)+, D2
	BEQ.b	loc_0000367C
	CMPI.b	#$7B, D2
	BEQ.b	loc_00003652
	CMPI.b	#$7C, D2
	BEQ.b	loc_00003652
	CMPI.b	#$0D, D2
	BNE.b	loc_00003664
	ADDQ.w	#2, D1
	MOVE.w	D3, D0
	BRA.b	loc_00003634
loc_00003652:
	SUBQ.w	#1, D0	;Predicted (Code-scan)
	SUBQ.w	#1, D1	;Predicted (Code-scan)
	ADDI.w	#$E4F0, D2	;Predicted (Code-scan)
	BSR.w	*+$E792	;Predicted (Code-scan)
	ADDQ.w	#1, D0	;Predicted (Code-scan)
	ADDQ.w	#1, D1	;Predicted (Code-scan)
	BRA.b	loc_00003634	;Predicted (Code-scan)
loc_00003664:
	ADDI.w	#$E4F0, D2
	BSR.w	*+$E784
	SUBQ.w	#1, D1
	MOVE.w	#$E52F, D2
	BSR.w	*+$E77A
	ADDQ.w	#1, D1
	ADDQ.w	#1, D0
	BRA.b	loc_00003634
loc_0000367C:
	MOVEM.l	(A7)+, D0/D1/D2/D3/A0/A1
	RTS
