; ########################################################################################
; # Generated by the active disassembly feature of the Exodus emulation platform
; #
; # Creation Date:   2020-11-29 21:45:40
; # Analysis Region: 0x00001F00 - 0x00002060
; ########################################################################################

 org $00001F00

	dc.b	$1C, $24, $24, $48, $4C, $DF, $01, $01, $36, $48, $49, $F9, $00, $06, $00, $00, $74, $2B, $20, $4C, $22, $4A, $10, $3C, $00, $0F, $12, $3C, $00, $0E, $61, $00 ;0x0 (0x00001F00-0x00001F58, Entry count: 0x58) [Unknown data]
	dc.b	$FF, $70, $28, $48, $20, $4A, $32, $4B, $30, $3C, $00, $40, $61, $00, $FB, $14, $D6, $FC, $00, $80, $51, $CA, $FF, $DC, $42, $80, $30, $0B, $2A, $40, $4D, $F9 ;0x20
	dc.b	$00, $06, $05, $80, $61, $00, $04, $3E, $2F, $08, $20, $4A, $61, $00, $1C, $4A, $20, $5F, $4C, $DF, $7F, $07, $4E, $75 ;0x40
	MOVEM.l	A1/A0/D0, -(A7)
	LEA	$00FF001A, A1
	ADDA.w	D1, A1
	SUBQ.w	#1, D0
loc_00001F66:
	MOVE.w	(A0)+, (A1)+
	DBF	D0, loc_00001F66
	BSET.b	#0, $00FF0018
	MOVEM.l	(A7)+, D0/A0/A1
	RTS
	MOVEM.l	A1/D0, -(A7)
	LEA	$00FF001A, A1
	ADDA.w	D1, A1
	SUBQ.w	#1, D0
loc_00001F88:
	MOVE.w	D2, (A1)+
	DBF	D0, loc_00001F88
	BSET.b	#0, $00FF0018
	MOVEM.l	(A7)+, D0/A1
	RTS
	dc.b	$48, $E7, $40, $80, $70, $00, $41, $FA, $01, $18, $30, $39, $00, $FF, $28, $10, $02, $40, $00, $FF, $12, $30, $00, $00, $E1, $49, $30, $39, $00, $FF, $00, $16 ;0x0 (0x00001F9C-0x00001FE8, Entry count: 0x4C) [Unknown data]
	dc.b	$02, $40, $00, $FF, $12, $30, $00, $00, $30, $39, $00, $FF, $28, $10, $D0, $41, $33, $C0, $00, $FF, $28, $10, $4C, $DF, $01, $02, $4E, $75, $61, $C2, $C0, $C1 ;0x20
	dc.b	$48, $40, $06, $40, $01, $00, $C0, $C2, $E0, $88, $4E, $75 ;0x40
	MOVEM.l	A1/A0/D2/D1/D0, -(A7)
	MOVE.w	A1, D2
	SUBI.w	#$0010, D0
	BMI.b	loc_0000203A
	EXT.l	D0
	LSL.w	#5, D0
	LEA	$000648E6, A0
	ADDA.l	D0, A0
	MOVEM.l	A0/D0, -(A7)
	MOVE.w	#$0080, D0
	BSR.w	*+$1B1A
	MOVEA.l	A0, A1
	MOVEM.l	(A7)+, D0/A0
	MOVE.l	A1, -(A7)
	MOVE.b	#$0F, D0
	MOVE.b	#$0E, D1
	BSR.w	*+$FE72
	MOVEA.l	(A7)+, A0
	MOVEA.w	D2, A1
	MOVE.w	#$0040, D0
	BSR.w	*+$FA18
	BSR.w	*+$1B6A
	LSR.w	#5, D2
	ORI.w	#$E000, D2
	BRA.w	*+$30
loc_0000203A:
	MOVE.w	#$E52F, D2	;Predicted (Code-scan)
	MOVEA.w	#$C000, A0	;Predicted (Code-scan)
	MOVE.w	D6, D0	;Predicted (Code-scan)
	MOVE.w	D7, D1	;Predicted (Code-scan)
	BSR.w	*+$FDA6	;Predicted (Code-scan)
	ADDQ.w	#1, D0	;Predicted (Code-scan)
	BSR.w	*+$FDA0	;Predicted (Code-scan)
	MOVE.w	D6, D0	;Predicted (Code-scan)
	ADDQ.w	#1, D1	;Predicted (Code-scan)
	BSR.w	*+$FD98	;Predicted (Code-scan)
	ADDQ.w	#1, D0	;Predicted (Code-scan)
	BSR.w	*+$FD92	;Predicted (Code-scan)
	dc.b	$4C, $DF ;0x0 (0x0000205E-0x00002060, Entry count: 0x2) [Unknown data]
