; ########################################################################################
; # Generated by the active disassembly feature of the Exodus emulation platform
; #
; # Creation Date:   2020-11-29 21:45:40
; # Analysis Region: 0x00001F00 - 0x00002060
; ########################################################################################

 org $00001FE8

	MOVEM.l	A1/A0/D2/D1/D0, -(A7)
	MOVE.w	A1, D2
	SUBI.w	#$0010, D0
	BMI.b	loc_0000203A
	EXT.l	D0
	LSL.w	#5, D0
	LEA	$000648E6, A0
	ADDA.l	D0, A0
	MOVEM.l	A0/D0, -(A7)
	MOVE.w	#$0080, D0
	BSR.w	*+$1B1A
	MOVEA.l	A0, A1
	MOVEM.l	(A7)+, D0/A0
	MOVE.l	A1, -(A7)
	MOVE.b	#$0F, D0
	MOVE.b	#$0E, D1
	BSR.w	*+$FE72
	MOVEA.l	(A7)+, A0
	MOVEA.w	D2, A1
	MOVE.w	#$0040, D0
	BSR.w	*+$FA18
	BSR.w	*+$1B6A
	LSR.w	#5, D2
	ORI.w	#$E000, D2
	BRA.w	*+$30
loc_0000203A:
	MOVE.w	#$E52F, D2	;Predicted (Code-scan)
	MOVEA.w	#$C000, A0	;Predicted (Code-scan)
	MOVE.w	D6, D0	;Predicted (Code-scan)
	MOVE.w	D7, D1	;Predicted (Code-scan)
	BSR.w	*+$FDA6	;Predicted (Code-scan)
	ADDQ.w	#1, D0	;Predicted (Code-scan)
	BSR.w	*+$FDA0	;Predicted (Code-scan)
	MOVE.w	D6, D0	;Predicted (Code-scan)
	ADDQ.w	#1, D1	;Predicted (Code-scan)
	BSR.w	*+$FD98	;Predicted (Code-scan)
	ADDQ.w	#1, D0	;Predicted (Code-scan)
	BSR.w	*+$FD92	;Predicted (Code-scan)
	dc.b	$4C, $DF ;0x0 (0x0000205E-0x00002060, Entry count: 0x2) [Unknown data]
