; ########################################################################################
; # Generated by the active disassembly feature of the Exodus emulation platform
; #
; # Creation Date:   2020-11-27 18:36:06
; # Analysis Region: 0x00003726 - 0x0000372C
; ########################################################################################

;	vram fix and new offset for "Choose a name" string

	org $3726
;;	ADDQ.w	#2, D6
	NOP
	ADDA.w	#$0040, A1


;	org	$492

;	LEA *+$6E6, A0
;	dc.l $41fa0258