; ########################################################################################
; # Generated by the active disassembly feature of the Exodus emulation platform
; #
; # Creation Date:   2020-11-27 18:36:06
; # Analysis Region: 0x00001200 - 0x00004000
; ########################################################################################

 org $00001200

	dc.b	$4E, $B9, $00, $00, $14, $16, $00, $00, $10, $32, $70, $01, $72, $0F, $74, $01, $61, $00, $1A, $6C, $41, $F9, $00, $06, $47, $96, $42, $40, $61, $00, $1B, $AA ;0x0 (0x00001200-0x000012D8, Entry count: 0xD8) [Unknown data]
	dc.b	$42, $B9, $00, $FF, $03, $9C, $42, $B9, $00, $FF, $07, $5C, $08, $F9, $00, $02, $00, $FF, $00, $18, $08, $F9, $00, $03, $00, $FF, $00, $18, $4E, $45, $00, $01 ;0x20
	dc.b	$61, $00, $06, $26, $33, $FC, $18, $9C, $00, $FF, $07, $B2, $70, $01, $61, $00, $11, $00, $74, $14, $4E, $45, $00, $01, $08, $39, $00, $07, $00, $FF, $27, $DA ;0x40
	dc.b	$66, $38, $53, $79, $00, $FF, $07, $B2, $51, $CA, $FF, $EA, $34, $3C, $00, $A8, $4E, $45, $00, $01, $08, $39, $00, $07, $00, $FF, $27, $DA, $66, $1C, $30, $79 ;0x60
	dc.b	$00, $FF, $07, $B4, $30, $3C, $01, $08, $32, $3C, $00, $C0, $61, $00, $17, $8E, $53, $79, $00, $FF, $07, $B2, $4A, $42, $66, $D6, $30, $79, $00, $FF, $07, $B4 ;0x80
	dc.b	$30, $3C, $01, $08, $32, $3C, $00, $C0, $61, $00, $15, $4E, $41, $FA, $01, $2E, $32, $7C, $60, $00, $30, $3C, $01, $20, $32, $3C, $01, $18, $74, $07, $61, $00 ;0xA0
	dc.b	$14, $A8, $41, $FA, $01, $20, $32, $7C, $60, $00, $30, $3C, $01, $1C, $32, $3C, $01, $38, $74, $07, $61, $00, $14, $92 ;0xC0
loc_000012D8:
	TRAP	#5
	ORI.b	#$39, D1	;Predicted (Code-scan)
	ORI.b	#$FF, D7	;Predicted (Code-scan)
	dc.b	$27, $DA ;0x0 (0x000012E2-0x000012E4, Entry count: 0x2) [Unknown data]
	BNE.b	loc_00001318
	SUBQ.w	#1, $00FF07B2
	BNE.b	loc_000012D8
	MOVE.w	#$00FD, D0	;Predicted (Code-scan)
	BSR.w	loc_00002350	;Predicted (Code-scan)
	MOVE.w	#$0168, D0	;Predicted (Code-scan)
	TRAP	#5	;Predicted (Code-scan)
	ORI.b	#$39, D1	;Predicted (Code-scan)
	ORI.b	#$FF, D7	;Predicted (Code-scan)
	dc.b	$27, $DA, $66, $10, $51, $C8, $FF, $F0, $42, $79, $00, $FF, $00, $00, $4E, $F9, $00, $00, $15, $6A ;0x0 (0x00001304-0x00001318, Entry count: 0x14) [Unknown data]
loc_00001318:
	MOVE.w	#$00FE, D0
	BSR.w	loc_00002350
	MOVE.w	#2, $00FF0000
	JMP	loc_0000156A
loc_0000132E:
	dc.w	$000C
	dc.b	$00, $20, $0E, $00, $00, $64, $00, $20, $00, $20, $0E, $00, $00, $58, $00, $00, $00, $20, $0E, $00, $00, $4C, $FF, $E0, $00, $20, $0E, $00, $00, $40, $FF, $C0 ;0x0 (0x00001330-0x00001390, Entry count: 0x60) [Unknown data]
	dc.b	$00, $00, $0F, $00, $00, $30, $00, $20, $00, $00, $0F, $00, $00, $20, $00, $00, $00, $00, $0F, $00, $00, $10, $FF, $E0, $00, $00, $0F, $00, $00, $00, $FF, $C0 ;0x20
	dc.b	$00, $20, $06, $00, $00, $94, $00, $60, $00, $20, $0E, $00, $00, $88, $00, $40, $00, $00, $07, $00, $00, $80, $00, $60, $00, $00, $0F, $00, $00, $70, $00, $40 ;0x40
loc_00001390:
	dc.w	$0004
	dc.b	$00, $00, $08, $00, $00, $A6, $00, $20, $00, $00, $0C, $00, $00, $A2, $00, $00, $00, $00, $0C, $00, $00, $9E, $FF, $E0, $00, $00, $0C, $00, $00, $9A, $FF, $C0 ;0x0 (0x00001392-0x000013B2, Entry count: 0x20) [Unknown data]
loc_000013B2:
	dc.w	$0004
	dc.b	$00, $00, $0D, $00, $00, $C1, $00, $20, $00, $00, $0D, $00, $00, $B9, $00, $00, $00, $00, $0D, $00, $00, $B1, $FF, $E0, $00, $00, $0D, $00, $00, $A9, $FF, $C0 ;0x0 (0x000013B4-0x000013D6, Entry count: 0x22) [Unknown data]
	dc.b	$00, $0F ;0x20
	dc.l	loc_0000132E
	dc.b	$FF, $FF, $00, $0F ;0x0 (0x000013DA-0x000013DE, Entry count: 0x4) [Unknown data]
	dc.l	loc_00001390
	dc.b	$FF, $FF, $00, $0F ;0x0 (0x000013E2-0x000013E6, Entry count: 0x4) [Unknown data]
	dc.l	loc_000013B2
	dc.b	$FF, $FF, $00, $20, $0E, $00, $41, $F9, $00, $FF, $07, $D6, $70, $0F, $42, $98, $42, $90, $D1, $FC, $00, $00, $01, $FC, $51, $C8, $FF, $F4, $41, $F9, $00, $FF ;0x0 (0x000013EA-0x00001458, Entry count: 0x6E) [Unknown data]
	dc.b	$07, $C6, $70, $07, $42, $58, $51, $C8, $FF, $FC, $4E, $75, $23, $CD, $00, $FF, $07, $C2, $23, $CE, $00, $FF, $07, $BE, $2C, $5F, $2A, $5E, $2F, $0E, $2F, $00 ;0x20
	dc.b	$3F, $3C, $00, $00, $70, $0F, $4D, $F9, $00, $FF, $07, $D6, $4A, $96, $67, $00, $00, $60, $DD, $FC, $00, $00, $02, $00, $51, $C8, $FF, $F2, $30, $1F, $20, $1F ;0x40
	dc.b	$2A, $79, $00, $FF, $07, $C2, $2C, $79, $00, $FF, $07, $BE, $4E, $75 ;0x60
	MOVE.l	A5, $00FF07C2
	MOVE.l	A6, $00FF07BE
	MOVEA.l	(A7)+, A6
	MOVEA.l	(A6)+, A5
	MOVE.l	A6, -(A7)
	MOVE.l	D0, -(A7)
	MOVE.w	#1, -(A7)
	MOVEQ	#$0000000F, D0
	LEA	$00FF25D6, A6
loc_00001478:
	TST.l	(A6)
	BEQ.w	loc_0000149A
	SUBA.l	#$00000200, A6
	DBF	D0, loc_00001478
	MOVE.w	(A7)+, D0	;Predicted (Code-scan)
	MOVE.l	(A7)+, D0	;Predicted (Code-scan)
	MOVEA.l	$00FF07C2, A5	;Predicted (Code-scan)
	MOVEA.l	$00FF07BE, A6	;Predicted (Code-scan)
	RTS	;Predicted (Code-scan)
loc_0000149A:
	MOVE.w	(A7)+, $A(A6)
	MOVE.l	(A7)+, D0
	MOVE.l	(A5)+, (A6)
	MOVE.l	(A5), $4(A6)
	MOVEA.l	$00FF07C2, A5
	MOVE.l	D0, $00FF07C2
	MOVE	SR, D0
	ANDI.w	#$0F00, D0
	MOVE.w	D0, $50(A6)
	MOVE.l	$00FF07C2, D0
	MOVE.w	#1, $8(A6)
	MOVE.l	(A7), $10(A6)
	SUBI.l	#$0000000A, $10(A6)
	MOVE.l	A6, $C(A6)
	ADDI.l	#$00000200, $C(A6)
	MOVE.w	#$0500, $50(A6)
	ADDA.l	#$00000050, A6
	MOVEM.l	A5/A4/A3/A2/A1/A0/D7/D6/D5/D4/D3/D2/D1/D0, -(A6)
	MOVE.l	$00FF07BE, -(A6)
	MOVEA.l	$00FF07BE, A6
	RTS
	CLR.w	$00FF07BC
	CLR.w	$00FF07B6
	LEA	$00FF07D6, A6
	MOVE.l	A6, $00FF07B8
loc_00001516:
	MOVEA.l	$00FF07B8, A6
	TST.l	(A6)
	BEQ.w	loc_000015CC
	MOVE.w	$00FF07C6, D0
	BEQ.w	loc_0000153E
	TST.w	$A(A6)	;Predicted (Code-scan)
	BNE.w	loc_0000153E	;Predicted (Code-scan)
	CMP.w	$00FF07B6, D0	;Predicted (Code-scan)
	BNE.w	loc_000015CC	;Predicted (Code-scan)
loc_0000153E:
	SUBQ.w	#1, $8(A6)
	BNE.w	loc_000015CC
	MOVEA.l	$C(A6), A5
	MOVE.l	A5, USP
	MOVE.l	(A6), -(A7)
	MOVE.w	$50(A6), -(A7)
	ADDA.l	#$00000014, A6
	MOVE.l	(A6)+, $00FF07BE
	MOVEM.l	(A6)+, D0/D1/D2/D3/D4/D5/D6/D7/A0/A1/A2/A3/A4/A5
	MOVEA.l	$00FF07BE, A6
	RTE
loc_0000156A:
	PEA	loc_00001586(PC)
	MOVE.l	A6, $00FF07BE
	MOVEA.l	$00FF07B8, A6
	MOVE.l	$4(A6), -(A7)
	MOVEA.l	$00FF07BE, A6
	RTS
loc_00001586:
	TRAP	#4
	MOVEA.l	$00FF07B8, A6
	CLR.l	(A6)
	CLR.l	$4(A6)
	BRA.w	loc_000015CC
	MOVE.l	A6, $00FF07BE
	MOVEA.l	$00FF07B8, A6
	ADDA.l	#$00000050, A6
	MOVEM.l	A5/A4/A3/A2/A1/A0/D7/D6/D5/D4/D3/D2/D1/D0, -(A6)
	MOVE.l	$00FF07BE, -(A6)
	MOVEA.l	$00FF07B8, A6
	MOVE.l	USP, A5
	MOVE.l	A5, $C(A6)
	MOVE.w	(A7)+, $50(A6)
	MOVEA.l	(A7)+, A5
	MOVE.w	(A5)+, $8(A6)
	MOVE.l	A5, (A6)
loc_000015CC:
	MOVE.w	$00FF0018, $52(A6)
	ADDA.l	#$00000200, A6
	MOVE.l	A6, $00FF07B8
	MOVE.w	$00FF07B6, D0
	ADDQ.w	#1, D0
	MOVE.w	D0, $00FF07B6
	CMPI.w	#$0010, D0
	BCS.w	loc_00001516
	RTS
	MOVE.l	A6, $00FF07BE
	MOVEA.l	$00FF07B8, A6
	ADDA.l	#$00000050, A6
	MOVEM.l	A5/A4/A3/A2/A1/A0/D7/D6/D5/D4/D3/D2/D1/D0, -(A6)
	MOVE.l	$00FF07BE, -(A6)
	MOVEA.l	$00FF07B8, A6
	MOVE.l	USP, A5
	MOVE.l	A5, $C(A6)
	MOVE.w	(A7)+, $50(A6)
	MOVEA.l	(A7)+, A5
	MOVEA.l	(A5)+, A4
	MOVE.l	A5, (A6)
	LEA	$00FF07D6, A6
	MOVEA.l	$4(A4), A5
	CLR.w	D0
loc_00001636:
	CMPA.l	$4(A6), A5
	BEQ.w	loc_00001650
	ADDA.l	#$00000200, A6
	ADDQ.w	#1, D0
	CMPI.w	#$0010, D0
	BCS.b	loc_00001636
	BRA.w	loc_00001698	;Predicted (Code-scan)
loc_00001650:
	MOVE.l	$00FF07B8, -(A7)
	MOVE.w	$00FF07B6, -(A7)
	MOVE.l	A6, $00FF07B8
	MOVE.w	D0, $00FF07B6
	MOVEA.l	$C(A6), A5
	LEA	loc_0000167E(PC), A4
	MOVE.l	A4, -(A5)
	MOVE.l	A5, USP
	MOVE.l	$4(A6), -(A7)
	MOVE.w	$50(A6), -(A7)
	RTE
loc_0000167E:
	TRAP	#4
	MOVEA.l	$00FF07B8, A6
	CLR.l	(A6)
	CLR.l	$4(A6)
	MOVE.w	(A7)+, $00FF07B6
	MOVE.l	(A7)+, $00FF07B8
loc_00001698:
	MOVEA.l	$00FF07B8, A6
	MOVEA.l	$C(A6), A5
	MOVE.l	A5, USP
	MOVE.l	(A6), -(A7)
	MOVE.w	$50(A6), -(A7)
	ADDA.l	#$00000014, A6
	MOVE.l	(A6)+, $00FF07BE
	MOVEM.l	(A6)+, D0/D1/D2/D3/D4/D5/D6/D7/A0/A1/A2/A3/A4/A5
	MOVEA.l	$00FF07BE, A6
	RTE
	dc.b	$48, $E7, $80, $80, $41, $F9, $00, $FF, $07, $D2, $70, $06, $31, $50, $00, $02, $55, $48, $51, $C8, $FF, $F8, $31, $79, $00, $FF, $07, $B6, $00, $02, $4C, $DF ;0x0 (0x000016C2-0x00001704, Entry count: 0x42) [Unknown data]
	dc.b	$01, $01, $4E, $75, $48, $E7, $80, $80, $41, $F9, $00, $FF, $07, $C6, $70, $06, $30, $A8, $00, $02, $54, $48, $51, $C8, $FF, $F8, $42, $50, $4C, $DF, $01, $01 ;0x20
	dc.b	$4E, $75 ;0x40
	MOVE.w	#$0100, $00A11100
loc_0000170C:
	BTST.b	#0, $00A11100
	BNE.b	loc_0000170C
	BSR.w	loc_00001798
	BSR.b	loc_00001726
	MOVE.w	#0, $00A11100
	RTS
loc_00001726:
	LEA	$00FF27D8, A5
	LEA	$00A10003, A6
	BSR.b	loc_00001738
	ADDQ.w	#2, A6
	ADDQ.w	#1, A5
loc_00001738:
	CLR.w	D7
	CMPI.b	#$0D, -$2(A5)
	BNE.b	loc_00001760
	MOVE.b	#0, (A6)
	NOP
	NOP
	MOVE.b	(A6), D7
	ASL.b	#2, D7
	MOVE.b	#$40, (A6)
	ANDI.w	#$00C0, D7
	MOVE.b	(A6), D6
	ANDI.w	#$003F, D6
	OR.b	D6, D7
	NOT.b	D7
loc_00001760:
	MOVE.l	A5, -(A7)
	MOVE.b	(A5), D1
	EOR.b	D7, D1
	AND.b	D7, D1
	MOVE.b	D1, $2(A5)
	CMP.b	(A5), D7
	BNE.b	loc_0000177C
	SUBQ.b	#1, $6(A5)
	BEQ.b	loc_00001788
	CLR.b	$4(A5)
	BRA.b	loc_00001792
loc_0000177C:
	MOVE.b	D1, $4(A5)
	MOVE.b	#$1E, $6(A5)
	BRA.b	loc_00001792
loc_00001788:
	MOVE.b	D7, $4(A5)
	MOVE.b	#$0A, $6(A5)
loc_00001792:
	MOVE.b	D7, (A5)
	MOVEA.l	(A7)+, A5
	RTS
loc_00001798:
	LEA	$00FF27D6, A0
	CLR.w	D1
	BSR.b	loc_000017A4
	ADDQ.w	#1, D1
loc_000017A4:
	MOVEM.l	A0/D3/D2/D1, -(A7)
	LEA	$00A10003, A0
	MOVEQ	#0, D0
	MOVE.b	D1, D0
	ADD.l	D0, D0
	ADDA.l	D0, A0
	MOVEQ	#0, D0
	MOVE.l	D0, D1
	MOVE.b	$6(A0), D3
	SWAP	D3
	MOVE.b	(A0), D3
	MOVE.b	#$40, $6(A0)
	MOVE.b	#$40, (A0)
	NOP
	MOVE.b	(A0), D0
	MOVE.b	#0, (A0)
	NOP
	MOVE.b	(A0), D1
	MOVE.b	#$40, (A0)
	MOVE.w	D0, D2
	LSR.b	#1, D0
	ROR.w	#1, D0
	LSR.b	#1, D0
	ROL.w	#1, D0
	ROR.w	#1, D2
	LSR.b	#1, D2
	ROL.w	#1, D2
	OR.b	D2, D0
	ANDI.w	#3, D0
	LSL.b	#2, D0
	MOVE.w	D1, D2
	LSR.b	#1, D1
	ROR.w	#1, D1
	LSR.b	#1, D1
	ROL.w	#1, D1
	ROR.w	#1, D2
	LSR.b	#1, D2
	ROL.w	#1, D2
	OR.b	D2, D1
	ANDI.w	#3, D1
	OR.b	D1, D0
	MOVE.b	(A0), D3
	SWAP	D3
	MOVE.b	$6(A0), D3
	MOVEM.l	(A7)+, D1/D2/D3/A0
	MOVE.b	D0, (A0,D1.w)
	RTS
loc_0000181E:
	MOVE.l	D0, -(A7)
loc_00001820:
	MOVE.w	$00C00004, D0
	BTST.l	#1, D0
	BNE.b	loc_00001820
	MOVE.l	(A7)+, D0
	RTS
loc_00001830:
	MOVE.l	D0, -(A7)
	MOVE.w	$00FF27E2, D0
	BSET.l	#4, D0
	MOVE.w	D0, $00FF27E2
	MOVE.w	D0, $00C00004
	MOVE.l	(A7)+, D0
	RTS
loc_0000184C:
	MOVE.l	D0, -(A7)
	MOVE.w	$00FF27E2, D0
	BCLR.l	#4, D0
	MOVE.w	D0, $00FF27E2
	MOVE.w	D0, $00C00004
	MOVE.l	(A7)+, D0
	RTS
	MOVE.l	D0, -(A7)
	MOVE.w	$00FF27E2, D0
	BSET.l	#6, D0
	MOVE.w	D0, $00FF27E2
	MOVE.w	D0, $00C00004
	MOVE.l	(A7)+, D0
	RTS
	dc.b	$2F, $00, $30, $39, $00, $FF, $27, $E2, $08, $80, $00, $06, $33, $C0, $00, $FF, $27, $E2, $33, $C0, $00, $C0, $00, $04, $20, $1F, $4E, $75, $2F, $00, $30, $39 ;0x0 (0x00001884-0x000019CE, Entry count: 0x14A) [Unknown data]
	dc.b	$00, $FF, $27, $E2, $08, $C0, $00, $05, $33, $C0, $00, $FF, $27, $E2, $33, $C0, $00, $C0, $00, $04, $20, $1F, $4E, $75, $2F, $00, $30, $39, $00, $FF, $27, $E2 ;0x20
	dc.b	$08, $80, $00, $05, $33, $C0, $00, $FF, $27, $E2, $33, $C0, $00, $C0, $00, $04, $20, $1F, $4E, $75, $61, $00, $FF, $44, $4D, $F9, $00, $C0, $00, $04, $4B, $F9 ;0x40
	dc.b	$00, $FF, $27, $E0, $41, $FA, $00, $7C, $30, $16, $70, $17, $32, $3C, $80, $00, $12, $18, $3A, $C1, $3C, $81, $06, $41, $01, $00, $51, $C8, $FF, $F4, $23, $FC ;0x60
	dc.b	$40, $00, $00, $80, $00, $C0, $00, $04, $33, $FC, $00, $00, $00, $C0, $00, $00, $61, $00, $FF, $08, $61, $00, $FF, $32, $23, $FC, $C0, $00, $00, $00, $00, $C0 ;0x80
	dc.b	$00, $04, $41, $F9, $00, $FF, $00, $1A, $70, $3F, $33, $FC, $00, $00, $00, $C0, $00, $00, $42, $58, $51, $C8, $FF, $F4, $23, $FC, $40, $00, $00, $10, $00, $C0 ;0xA0
	dc.b	$00, $04, $70, $27, $33, $FC, $00, $00, $00, $C0, $00, $00, $51, $C8, $FF, $F6, $20, $7C, $00, $FF, $03, $9C, $30, $3C, $01, $E0, $42, $58, $51, $C8, $FF, $FC ;0xC0
	dc.b	$4E, $75, $04, $14, $30, $34, $07, $5C, $00, $00, $00, $00, $FF, $00, $81, $2F, $00, $01, $01, $00, $00, $FF, $FF, $00, $00, $80, $33, $FC, $01, $00, $00, $A1 ;0xE0
	dc.b	$12, $00, $33, $FC, $00, $1E, $00, $FF, $27, $DE, $42, $79, $00, $FF, $00, $18, $42, $79, $00, $FF, $01, $1A, $4E, $B9, $00, $00, $13, $F0, $4E, $B9, $00, $00 ;0x100
	dc.b	$26, $2C, $4E, $B9, $00, $00, $3B, $0A, $08, $F9, $00, $01, $00, $FF, $00, $18, $61, $00, $1E, $40, $4E, $75, $3F, $00, $30, $39, $00, $FF, $00, $16, $B0, $79 ;0x120
	dc.b	$00, $FF, $00, $16, $67, $F8, $30, $1F, $4E, $75 ;0x140
loc_000019CE:
	TRAP	#2	;Predicted (Code-scan)
	MOVEM.l	A1/A0/D1/D0, -(A7)	;Predicted (Code-scan)
	MOVE.w	#$8F02, $00C00004	;Predicted (Code-scan)
	MOVE.w	A1, D1	;Predicted (Code-scan)
	ANDI.w	#$3FFF, D1	;Predicted (Code-scan)
	ORI.w	#$4000, D1	;Predicted (Code-scan)
	MOVE.w	D1, $00C00004	;Predicted (Code-scan)
	MOVE.w	A1, D1	;Predicted (Code-scan)
	LSR.w	#8, D1	;Predicted (Code-scan)
	LSR.w	#6, D1	;Predicted (Code-scan)
	MOVE.w	D1, $00C00004	;Predicted (Code-scan)
	LEA	$00C00000, A1	;Predicted (Code-scan)
	SUBQ.l	#1, D0	;Predicted (Code-scan)
loc_00001A00:
	MOVE.w	(A0)+, (A1)	;Predicted (Code-scan)
	DBF	D0, loc_00001A00	;Predicted (Code-scan)
	MOVEM.l	(A7)+, D0/D1/A0/A1	;Predicted (Code-scan)
	TRAP	#3	;Predicted (Code-scan)
	RTS	;Predicted (Code-scan)
loc_00001A0E:
	MOVE.w	#$0100, $00A11100
loc_00001A16:
	BTST.b	#0, $00A11100
	BNE.b	loc_00001A16
	BSR.w	loc_00001830
	MOVE.w	(A3)+, (A2)
	MOVE.w	(A3)+, (A2)
	MOVE.w	(A3)+, (A2)
	MOVE.w	(A3)+, (A2)
	MOVE.w	(A3)+, (A2)
	MOVE.w	(A3)+, (A2)
	MOVE.w	(A3)+, (A2)
	MOVE.w	(A3)+, (A2)
	MOVE.w	#0, $00A11100
	BSR.w	loc_0000181E
	RTS
loc_00001A42:
	MOVEM.l	A2/A1/A0/D3/D2/D1/D0, -(A7)
	CLR.l	D2
	MOVE.w	D0, D2
	LSL.l	#1, D2
	MOVE.l	A0, D3
	ADD.l	D3, D2
	EOR.l	D3, D2
	BTST.l	#$11, D2
	BEQ.b	loc_00001A60
	BSR.w	loc_000019CE	;Predicted (Code-scan)
	BRA.w	loc_00001AF4	;Predicted (Code-scan)
loc_00001A60:
	LINK.w	A3, #-$00000010
	TRAP	#2
	MOVE.w	A1, D1
	LSR.w	#8, D1
	LSR.w	#6, D1
	ORI.w	#$0080, D1
	MOVE.w	D1, -(A3)
	MOVE.w	A1, D1
	ANDI.w	#$3FFF, D1
	ORI.w	#$4000, D1
	MOVE.w	D1, -(A3)
	MOVE.l	A0, D1
	SWAP	D1
	LSR.w	#1, D1
	ANDI.w	#$007F, D1
	ORI.w	#$9700, D1
	MOVE.w	D1, -(A3)
	MOVE.l	A0, D1
	LSR.l	#1, D1
	LSR.w	#8, D1
	ANDI.w	#$00FF, D1
	ORI.w	#$9600, D1
	MOVE.w	D1, -(A3)
	MOVE.w	A0, D1
	LSR.w	#1, D1
	ANDI.w	#$00FF, D1
	ORI.w	#$9500, D1
	MOVE.w	D1, -(A3)
	MOVE.w	D0, D1
	LSR.w	#8, D1
	ANDI.w	#$00FF, D1
	ORI.w	#$9400, D1
	MOVE.w	D1, -(A3)
	ANDI.w	#$00FF, D0
	ORI.w	#$9300, D0
	MOVE.w	D0, -(A3)
	MOVE.w	#$8F02, -(A3)
	LEA	$00C00004, A2
	BSR.w	loc_00001A0E
	MOVE.w	A1, D1
	ANDI.w	#$3FFF, D1
	ORI.w	#$4000, D1
	MOVE.w	D1, (A2)
	MOVE.w	A1, D1
	LSR.w	#8, D1
	LSR.w	#6, D1
	MOVE.w	D1, (A2)
	MOVE.w	(A0), $00C00000
	BSR.w	loc_0000184C
	TRAP	#3
	UNLK	A3
loc_00001AF4:
	MOVEM.l	(A7)+, D0/D1/D2/D3/A0/A1/A2
	RTS
	MOVEM.l	A2/A1/A0/D1/D0, -(A7)
	LINK.w	A3, #-$00000010
	TRAP	#2
	MOVE.w	#$0080, -(A3)
	MOVE.w	A1, D1
	ANDI.w	#$007F, D1
	ORI.w	#$C000, D1
	MOVE.w	D1, -(A3)
	MOVE.l	A0, D1
	SWAP	D1
	LSR.w	#1, D1
	ANDI.w	#$007F, D1
	ORI.w	#$9700, D1
	MOVE.w	D1, -(A3)
	MOVE.l	A0, D1
	LSR.l	#1, D1
	LSR.w	#8, D1
	ANDI.w	#$00FF, D1
	ORI.w	#$9600, D1
	MOVE.w	D1, -(A3)
	MOVE.w	A0, D1
	LSR.w	#1, D1
	ANDI.w	#$00FF, D1
	ORI.w	#$9500, D1
	MOVE.w	D1, -(A3)
	MOVE.w	D0, D1
	LSR.w	#8, D1
	ANDI.w	#$00FF, D1
	ORI.w	#$9400, D1
	MOVE.w	D1, -(A3)
	ANDI.w	#$00FF, D0
	ORI.w	#$9300, D0
	MOVE.w	D0, -(A3)
	MOVE.w	#$8F02, -(A3)
	LEA	$00C00004, A2
	BSR.w	loc_00001A0E
	CMPA.l	#$00F00000, A0
	BCS.w	loc_00001B88
	MOVE.w	A1, D1
	ANDI.w	#$007F, D1
	ORI.w	#$C000, D1
	MOVE.w	D1, (A2)
	MOVE.w	#0, (A2)
	MOVE.w	(A0), $00C00000
loc_00001B88:
	BSR.w	loc_0000184C
	TRAP	#3
	UNLK	A3
	MOVEM.l	(A7)+, D0/D1/A0/A1/A2
	RTS
	dc.b	$48, $E7, $80, $E0, $4E, $53, $FF, $F0, $4E, $42, $37, $3C, $00, $90, $37, $3C, $40, $00, $20, $08, $48, $40, $E2, $48, $02, $40, $00, $7F, $00, $40, $97, $00 ;0x0 (0x00001B96-0x00001C10, Entry count: 0x7A) [Unknown data]
	dc.b	$37, $00, $20, $08, $E2, $88, $E0, $48, $02, $40, $00, $FF, $00, $40, $96, $00, $37, $00, $30, $08, $E2, $48, $02, $40, $00, $FF, $00, $40, $95, $00, $37, $00 ;0x20
	dc.b	$37, $3C, $94, $00, $37, $3C, $93, $28, $37, $3C, $8F, $02, $24, $7C, $00, $C0, $00, $04, $61, $00, $FE, $24, $B1, $FC, $00, $F0, $00, $00, $65, $0E, $34, $BC ;0x40
	dc.b	$40, $00, $34, $BC, $00, $10, $33, $D0, $00, $C0, $00, $00, $61, $00, $FC, $48, $4E, $43, $4E, $5B, $4C, $DF, $07, $01, $4E, $75 ;0x60
loc_00001C10:
	MOVEM.l	A2/A1/A0/D1/D0, -(A7)
	LINK.w	A3, #-$00000010
	TRAP	#2
	MOVE.w	D1, -(A3)
	MOVE.w	A1, D1
	LSR.w	#8, D1
	LSR.w	#6, D1
	ORI.w	#$0080, D1
	MOVE.w	D1, -(A3)
	MOVE.w	A1, D1
	ANDI.w	#$3FFF, D1
	ORI.w	#$4000, D1
	MOVE.w	D1, -(A3)
	MOVE.w	#$9780, -(A3)
	MOVE.w	D0, D1
	LSR.w	#8, D1
	ANDI.w	#$00FF, D1
	ORI.w	#$9400, D1
	MOVE.w	D1, -(A3)
	ANDI.w	#$00FF, D0
	ORI.w	#$9300, D0
	MOVE.w	D0, -(A3)
	MOVE.w	#$8F01, -(A3)
	LEA	$00C00004, A2
	MOVE.w	#$0100, $00A11100
loc_00001C62:
	BTST.b	#0, $00A11100
	BNE.b	loc_00001C62
	BSR.w	loc_00001830
	MOVE.w	(A3)+, (A2)
	MOVE.w	(A3)+, (A2)
	MOVE.w	(A3)+, (A2)
	MOVE.w	(A3)+, (A2)
	MOVE.w	(A3)+, (A2)
	MOVE.w	(A3)+, (A2)
	MOVE.w	(A3)+, $00C00000
	MOVE.w	#0, $00A11100
	BSR.w	loc_0000181E
	BSR.w	loc_0000184C
	MOVE.w	#$8F02, $00C00004
	TRAP	#3
	UNLK	A3
	MOVEM.l	(A7)+, D0/D1/A0/A1/A2
	RTS
	dc.b	$7E, $40, $13, $C7, $00, $A1, $00, $09, $13, $C7, $00, $A1, $00, $0B, $13, $C7, $00, $A1, $00, $0D, $4E, $75 ;0x0 (0x00001CA4-0x00001CBA, Entry count: 0x16) [Unknown data]
loc_00001CBA:
	TRAP	#2	;Predicted (Code-scan)
	MOVEM.l	A5/D3/D2, -(A7)	;Predicted (Code-scan)
	CLR.l	D3	;Predicted (Code-scan)
	MOVE.w	D5, D3	;Predicted (Code-scan)
	BSET.l	#$0E, D3	;Predicted (Code-scan)
	BCLR.l	#$0F, D3	;Predicted (Code-scan)
	LSL.l	#2, D5	;Predicted (Code-scan)
	ANDI.l	#$00030000, D5	;Predicted (Code-scan)
	MOVE.w	D3, D5	;Predicted (Code-scan)
	SWAP	D5	;Predicted (Code-scan)
	LEA	$00C00000, A5	;Predicted (Code-scan)
	MOVE.l	#$00800000, D3	;Predicted (Code-scan)
loc_00001CE4:
	MOVE.l	D5, $4(A5)	;Predicted (Code-scan)
	MOVE.w	D7, D2	;Predicted (Code-scan)
loc_00001CEA:
	MOVE.w	(A6)+, (A5)	;Predicted (Code-scan)
	DBF	D2, loc_00001CEA	;Predicted (Code-scan)
	ADD.l	D3, D5	;Predicted (Code-scan)
	DBF	D6, loc_00001CE4	;Predicted (Code-scan)
	MOVEM.l	(A7)+, D2/D3/A5	;Predicted (Code-scan)
	TRAP	#3	;Predicted (Code-scan)
	RTS	;Predicted (Code-scan)
	dc.b	$48, $E7, $37, $04, $42, $85, $3A, $00, $3C, $01, $E3, $4D, $EF, $4E, $DA, $46, $06, $45, $C0, $00, $3E, $02, $53, $47, $3C, $03, $53, $46, $4E, $42, $42, $83 ;0x0 (0x00001CFE-0x00001D5A, Entry count: 0x5C) [Unknown data]
	dc.b	$36, $05, $08, $C3, $00, $0E, $08, $83, $00, $0F, $E5, $8D, $02, $85, $00, $03, $00, $00, $3A, $03, $48, $45, $4B, $F9, $00, $C0, $00, $00, $26, $3C, $00, $80 ;0x20
	dc.b	$00, $00, $2B, $45, $00, $04, $34, $07, $3A, $84, $51, $CA, $FF, $FC, $DA, $83, $51, $CE, $FF, $F0, $4E, $43, $4C, $DF, $20, $EC, $4E, $75 ;0x40
loc_00001D5A:
	TRAP	#2	;Predicted (Code-scan)
	MOVEM.l	D2/D1/D0, -(A7)	;Predicted (Code-scan)
	MOVE.w	#$8F02, $00C00004	;Predicted (Code-scan)
	MOVE.w	D0, D2	;Predicted (Code-scan)
	LSR.w	#8, D2	;Predicted (Code-scan)
	LSR.w	#6, D2	;Predicted (Code-scan)
	ANDI.w	#3, D2	;Predicted (Code-scan)
	ANDI.w	#$3FFF, D0	;Predicted (Code-scan)
	MOVE.w	D0, $00C00004	;Predicted (Code-scan)
	MOVE.w	D2, $00C00004	;Predicted (Code-scan)
	SUBQ.w	#1, D1	;Predicted (Code-scan)
loc_00001D84:
	MOVE.w	$00C00000, (A0)+	;Predicted (Code-scan)
	DBF	D1, loc_00001D84	;Predicted (Code-scan)
	MOVEM.l	(A7)+, D0/D1/D2	;Predicted (Code-scan)
	TRAP	#3	;Predicted (Code-scan)
	RTS	;Predicted (Code-scan)
loc_00001D96:
	TRAP	#2
	MOVEM.l	D2/D0, -(A7)
	MOVE.w	D0, D2
	ANDI.w	#$3FFF, D2
	ORI.w	#$4000, D2
	MOVE.w	D2, $00C00004
	LSR.w	#8, D0
	LSR.w	#6, D0
	MOVE.w	D0, $00C00004
	MOVE.w	D1, $00C00000
	MOVEM.l	(A7)+, D0/D2
	TRAP	#3
	RTS
loc_00001DC4:
	TRAP	#2
	MOVE.l	D0, -(A7)
	MOVE.w	D0, D1
	LSR.w	#8, D1
	LSR.w	#6, D1
	ANDI.w	#3, D1
	ANDI.w	#$3FFF, D0
	MOVE.w	D0, $00C00004
	MOVE.w	D1, $00C00004
	MOVE.w	$00C00000, D1
	MOVE.l	(A7)+, D0
	TRAP	#3
	RTS
loc_00001DEE:
	MOVEM.l	D1/D0, -(A7)
	LSL.w	#1, D0
	LSL.w	#7, D1
	ADD.w	D1, D0
	ADD.w	A0, D0
	MOVE.w	D2, D1
	BSR.b	loc_00001D96
	MOVEM.l	(A7)+, D0/D1
	RTS
	dc.b	$48, $E7, $C0, $00, $E3, $48, $EF, $49, $D0, $41, $D0, $48, $61, $B2, $34, $01, $4C, $DF, $00, $03, $4E, $75, $48, $E7, $FC, $00, $3A, $3C, $C0, $00, $60, $08 ;0x0 (0x00001E04-0x00001E60, Entry count: 0x5C) [Unknown data]
	dc.b	$48, $E7, $FC, $00, $3A, $3C, $E0, $00, $EF, $49, $E3, $48, $D0, $41, $D0, $45, $E1, $4C, $EB, $4C, $48, $A7, $A0, $00, $61, $86, $02, $41, $9F, $FF, $82, $44 ;0x20
	dc.b	$61, $00, $FF, $50, $54, $40, $51, $CA, $FF, $F0, $4C, $9F, $00, $05, $06, $40, $00, $80, $51, $CB, $FF, $E0, $4C, $DF, $00, $3F, $4E, $75 ;0x40
	MOVEM.l	A1/D1/D0, -(A7)
	MOVE.w	#$1000, D0
	CLR.w	D1
	MOVEA.w	#$C000, A1
	BSR.w	loc_00001C10
	MOVEM.l	(A7)+, D0/D1/A1
	RTS
	MOVEM.l	A1/D1/D0, -(A7)
	MOVE.w	#$1000, D0
	CLR.w	D1
	MOVEA.w	#$E000, A1
	BSR.w	loc_00001C10
	MOVEM.l	(A7)+, D0/D1/A1
	RTS
loc_00001E90:
	MOVEM.l	A2/D7/D6/D5/D4/D3/D2, -(A7)
	MOVEM.l	A0/D0, -(A7)
	MOVE.w	#$0080, D0
	BSR.w	loc_00003B24
	MOVEA.l	A0, A2
	MOVEM.l	(A7)+, D0/A0
	ANDI.b	#$0F, D0
	ANDI.b	#$0F, D1
	MOVE.l	A2, -(A7)
	MOVE.l	A2, -(A7)
	MOVEQ	#7, D4
loc_00001EB4:
	MOVE.l	(A0)+, D3
	MOVEQ	#3, D5
loc_00001EB8:
	MOVEQ	#7, D6
	CLR.l	D7
loc_00001EBC:
	LSL.l	#4, D7
	LSL.l	#1, D3
	BCS.b	loc_00001EC6
	ADD.b	D1, D7
	BRA.b	loc_00001EC8
loc_00001EC6:
	ADD.b	D0, D7
loc_00001EC8:
	DBF	D6, loc_00001EBC
	MOVE.l	D7, (A2)+
	DBF	D5, loc_00001EB8
	DBF	D4, loc_00001EB4
	MOVEA.l	(A7)+, A2
	MOVEQ	#$0000001F, D4
loc_00001EDA:
	MOVE.l	(A2)+, (A1)+
	DBF	D4, loc_00001EDA
	MOVEA.l	(A7)+, A2
	MOVE.l	A0, -(A7)
	MOVEA.l	A2, A0
	BSR.w	loc_00003B98
	MOVEA.l	(A7)+, A0
	MOVEM.l	(A7)+, D2/D3/D4/D5/D6/D7/A2
	RTS
	MOVEM.l	A6/A5/A4/A3/A2/A1/A0/D2/D1/D0, -(A7)
	MOVEM.l	A0/D0, -(A7)
	MOVE.w	#$0080, D0
	BSR.w	loc_00003B24
	MOVEA.l	A0, A2
	MOVEM.l	(A7)+, D0/A0
	MOVEA.w	A0, A3
	LEA	$00060000, A4
	MOVEQ	#$0000002B, D2
loc_00001F12:
	MOVEA.l	A4, A0
	MOVEA.l	A2, A1
	MOVE.b	#$0F, D0
	MOVE.b	#$0E, D1
	BSR.w	loc_00001E90
	MOVEA.l	A0, A4
	MOVEA.l	A2, A0
	MOVEA.w	A3, A1
	MOVE.w	#$0040, D0
	BSR.w	loc_00001A42
	ADDA.w	#$0080, A3
	DBF	D2, loc_00001F12
	CLR.l	D0
	MOVE.w	A3, D0
	MOVEA.l	D0, A5
	LEA	$00060580, A6
	BSR.w	loc_00002384
	MOVE.l	A0, -(A7)
	MOVEA.l	A2, A0
	BSR.w	loc_00003B98
	MOVEA.l	(A7)+, A0
	MOVEM.l	(A7)+, D0/D1/D2/A0/A1/A2/A3/A4/A5/A6
	RTS
loc_00001F58:
	MOVEM.l	A1/A0/D0, -(A7)
	LEA	$00FF001A, A1
	ADDA.w	D1, A1
	SUBQ.w	#1, D0
loc_00001F66:
	MOVE.w	(A0)+, (A1)+
	DBF	D0, loc_00001F66
	BSET.b	#0, $00FF0018
	MOVEM.l	(A7)+, D0/A0/A1
	RTS
	dc.b	$48, $E7, $80, $40, $43, $F9, $00, $FF, $00, $1A, $D2, $C1, $53, $40, $32, $C2, $51, $C8, $FF, $FC, $08, $F9, $00, $00, $00, $FF, $00, $18, $4C, $DF, $02, $01 ;0x0 (0x00001F7A-0x00001FE8, Entry count: 0x6E) [Unknown data]
	dc.b	$4E, $75, $48, $E7, $40, $80, $70, $00, $41, $FA, $01, $18, $30, $39, $00, $FF, $28, $10, $02, $40, $00, $FF, $12, $30, $00, $00, $E1, $49, $30, $39, $00, $FF ;0x20
	dc.b	$00, $16, $02, $40, $00, $FF, $12, $30, $00, $00, $30, $39, $00, $FF, $28, $10, $D0, $41, $33, $C0, $00, $FF, $28, $10, $4C, $DF, $01, $02, $4E, $75, $61, $C2 ;0x40
	dc.b	$C0, $C1, $48, $40, $06, $40, $01, $00, $C0, $C2, $E0, $88, $4E, $75 ;0x60
loc_00001FE8:
	MOVEM.l	A1/A0/D2/D1/D0, -(A7)
	MOVE.w	A1, D2
	SUBI.w	#$0010, D0
	BMI.b	loc_0000203A
	EXT.l	D0
	LSL.w	#5, D0
	LEA	$000648E6, A0
	ADDA.l	D0, A0
	MOVEM.l	A0/D0, -(A7)
	MOVE.w	#$0080, D0
	BSR.w	loc_00003B24
	MOVEA.l	A0, A1
	MOVEM.l	(A7)+, D0/A0
	MOVE.l	A1, -(A7)
	MOVE.b	#$0F, D0
	MOVE.b	#$0E, D1
	BSR.w	loc_00001E90
	MOVEA.l	(A7)+, A0
	MOVEA.w	D2, A1
	MOVE.w	#$0040, D0
	BSR.w	loc_00001A42
	BSR.w	loc_00003B98
	LSR.w	#5, D2
	ORI.w	#$E000, D2
	BRA.w	loc_00002068
loc_0000203A:
	MOVE.w	#$E52F, D2	;Predicted (Code-scan)
	MOVEA.w	#$C000, A0	;Predicted (Code-scan)
	MOVE.w	D6, D0	;Predicted (Code-scan)
	MOVE.w	D7, D1	;Predicted (Code-scan)
	BSR.w	loc_00001DEE	;Predicted (Code-scan)
	ADDQ.w	#1, D0	;Predicted (Code-scan)
	BSR.w	loc_00001DEE	;Predicted (Code-scan)
	MOVE.w	D6, D0	;Predicted (Code-scan)
	ADDQ.w	#1, D1	;Predicted (Code-scan)
	BSR.w	loc_00001DEE	;Predicted (Code-scan)
	ADDQ.w	#1, D0	;Predicted (Code-scan)
	BSR.w	loc_00001DEE	;Predicted (Code-scan)
	MOVEM.l	(A7)+, D0/D1/D2/A0/A1	;Predicted (Code-scan)
	RTS	;Predicted (Code-scan)
	dc.b	$4C, $DF, $03, $07 ;0x0 (0x00002064-0x00002068, Entry count: 0x4) [Unknown data]
loc_00002068:
	MOVEA.w	#$C000, A0
	MOVE.w	D6, D0
	MOVE.w	D7, D1
	BSR.w	loc_00001DEE
	ADDQ.w	#1, D0
	ADDQ.w	#1, D2
	BSR.w	loc_00001DEE
	MOVE.w	D6, D0
	ADDQ.w	#1, D1
	ADDQ.w	#1, D2
	BSR.w	loc_00001DEE
	ADDQ.w	#1, D0
	ADDQ.w	#1, D2
	BSR.w	loc_00001DEE
	MOVEM.l	(A7)+, D0/D1/D2/A0/A1
	RTS
	dc.b	$2F, $0E, $23, $CE, $00, $FF, $28, $12, $4D, $F9, $00, $FF, $28, $4E, $48, $E6, $FF, $FC, $2C, $5F, $4E, $75, $4D, $F9, $00, $FF, $28, $16, $4C, $DE, $3F, $FF ;0x0 (0x00002094-0x000021BC, Entry count: 0x128) [Unknown data]
	dc.b	$2C, $79, $00, $FF, $28, $12, $4E, $75, $07, $9B, $F5, $FD, $62, $D5, $D6, $C6, $E4, $5A, $22, $1D, $0F, $93, $3C, $5B, $F1, $75, $1C, $78, $FB, $70, $2D, $69 ;0x20
	dc.b	$02, $E5, $5F, $23, $DB, $DE, $2F, $FF, $9F, $53, $05, $EC, $99, $17, $AA, $18, $B6, $19, $C8, $26, $DA, $B4, $C1, $90, $56, $98, $88, $74, $2B, $E9, $D3, $34 ;0x40
	dc.b	$55, $E1, $8B, $C5, $01, $2C, $D9, $41, $48, $EE, $0B, $71, $B9, $DF, $82, $A9, $30, $42, $29, $85, $BE, $6B, $F3, $58, $B1, $54, $7A, $15, $CF, $50, $F6, $0C ;0x60
	dc.b	$3A, $51, $E2, $C2, $B8, $9D, $57, $67, $06, $CD, $AF, $66, $2A, $0D, $11, $6E, $1A, $F0, $E7, $CB, $ED, $31, $24, $94, $F7, $A0, $FC, $D8, $6D, $F2, $80, $76 ;0x80
	dc.b	$65, $60, $8E, $B2, $4B, $96, $A3, $79, $59, $BD, $10, $A1, $44, $28, $3F, $89, $46, $64, $8F, $EB, $F9, $08, $9C, $D7, $A4, $E8, $AE, $C9, $EF, $63, $B0, $45 ;0xA0
	dc.b	$43, $61, $38, $C7, $09, $BB, $52, $16, $21, $1E, $0E, $7B, $4C, $04, $25, $47, $B5, $B7, $DD, $1F, $3D, $6C, $03, $5E, $D0, $35, $86, $39, $DC, $7E, $E3, $20 ;0xC0
	dc.b	$A6, $A8, $CC, $84, $7C, $6A, $C0, $E6, $83, $40, $0A, $2E, $B3, $CA, $5C, $81, $AB, $A2, $49, $F8, $27, $97, $8D, $BF, $37, $FE, $91, $3B, $32, $7F, $9E, $72 ;0xE0
	dc.b	$4E, $92, $95, $3E, $87, $77, $14, $73, $CE, $BC, $A7, $4D, $D1, $D4, $6F, $AD, $33, $4A, $C3, $8C, $FA, $13, $5D, $E0, $12, $F4, $8A, $C4, $A5, $BA, $36, $1B ;0x100
	dc.b	$68, $EA, $9A, $D2, $7D, $AC, $00, $4F ;0x120
loc_000021BC:
	MOVEM.l	A2/A1/A0/D3/D2/D1/D0, -(A7)
	CLR.l	D2
	MOVE.w	D0, D2
	LSL.l	#1, D2
	MOVE.l	A0, D3
	ADD.l	D3, D2
	EOR.l	D3, D2
	BTST.l	#$11, D2
	BEQ.w	loc_0000220A
	MOVE.w	#$8F02, $00C00004	;Predicted (Code-scan)
	MOVE.w	A1, D1	;Predicted (Code-scan)
	ANDI.w	#$3FFF, D1	;Predicted (Code-scan)
	ORI.w	#$4000, D1	;Predicted (Code-scan)
	MOVE.w	D1, $00C00004	;Predicted (Code-scan)
	MOVE.w	A1, D1	;Predicted (Code-scan)
	LSR.w	#8, D1	;Predicted (Code-scan)
	LSR.w	#6, D1	;Predicted (Code-scan)
	MOVE.w	D1, $00C00004	;Predicted (Code-scan)
	LEA	$00C00000, A1	;Predicted (Code-scan)
	SUBQ.l	#1, D0	;Predicted (Code-scan)
loc_00002200:
	MOVE.w	(A0)+, (A1)	;Predicted (Code-scan)
	DBF	D0, loc_00002200	;Predicted (Code-scan)
	BRA.w	loc_0000229A	;Predicted (Code-scan)
loc_0000220A:
	LINK.w	A3, #-$00000010
	MOVE.w	A1, D1
	LSR.w	#8, D1
	LSR.w	#6, D1
	ORI.w	#$0080, D1
	MOVE.w	D1, -(A3)
	MOVE.w	A1, D1
	ANDI.w	#$3FFF, D1
	ORI.w	#$4000, D1
	MOVE.w	D1, -(A3)
	MOVE.l	A0, D1
	SWAP	D1
	LSR.w	#1, D1
	ANDI.w	#$007F, D1
	ORI.w	#$9700, D1
	MOVE.w	D1, -(A3)
	MOVE.l	A0, D1
	LSR.l	#1, D1
	LSR.w	#8, D1
	ANDI.w	#$00FF, D1
	ORI.w	#$9600, D1
	MOVE.w	D1, -(A3)
	MOVE.w	A0, D1
	LSR.w	#1, D1
	ANDI.w	#$00FF, D1
	ORI.w	#$9500, D1
	MOVE.w	D1, -(A3)
	MOVE.w	D0, D1
	LSR.w	#8, D1
	ANDI.w	#$00FF, D1
	ORI.w	#$9400, D1
	MOVE.w	D1, -(A3)
	ANDI.w	#$00FF, D0
	ORI.w	#$9300, D0
	MOVE.w	D0, -(A3)
	MOVE.w	#$8F02, -(A3)
	LEA	$00C00004, A2
	BSR.w	loc_00001A0E
	MOVE.w	A1, D1
	ANDI.w	#$3FFF, D1
	ORI.w	#$4000, D1
	MOVE.w	D1, (A2)
	MOVE.w	A1, D1
	LSR.w	#8, D1
	LSR.w	#6, D1
	MOVE.w	D1, (A2)
	MOVE.w	(A0), $00C00000
	BSR.w	loc_0000184C
	UNLK	A3
loc_0000229A:
	MOVEM.l	(A7)+, D0/D1/D2/D3/A0/A1/A2
	RTS
	dc.b	$48, $E7, $C0, $C0, $33, $FC, $8F, $02, $00, $C0, $00, $04, $32, $09, $02, $41, $3F, $FF, $00, $41, $40, $00, $33, $C1, $00, $C0, $00, $04, $32, $09, $E0, $49 ;0x0 (0x000022A0-0x00002350, Entry count: 0xB0) [Unknown data]
	dc.b	$EC, $49, $33, $C1, $00, $C0, $00, $04, $43, $F9, $00, $C0, $00, $00, $53, $80, $32, $98, $51, $C8, $FF, $FC, $4C, $DF, $03, $03, $4E, $75, $4E, $42, $22, $7C ;0x20
	dc.b	$00, $0F, $60, $00, $32, $3C, $1F, $FF, $20, $7C, $00, $A0, $00, $00, $33, $FC, $01, $00, $00, $A1, $12, $00, $33, $FC, $01, $00, $00, $A1, $11, $00, $08, $39 ;0x40
	dc.b	$00, $00, $00, $A1, $11, $00, $66, $F6, $10, $19, $10, $80, $B0, $10, $66, $FA, $52, $88, $51, $C9, $FF, $F4, $33, $FC, $00, $00, $00, $A0, $1F, $FE, $33, $FC ;0x60
	dc.b	$00, $00, $00, $A1, $11, $00, $33, $FC, $00, $00, $00, $A1, $12, $00, $4E, $71, $4E, $71, $4E, $71, $4E, $71, $33, $FC, $01, $00, $00, $A1, $12, $00, $30, $3C ;0x80
	dc.b	$C3, $4F, $51, $C8, $FF, $FE, $42, $79, $00, $FF, $28, $52, $4E, $43, $4E, $75 ;0xA0
loc_00002350:
	TST.w	D0
	BEQ.b	loc_0000235C
	CMP.w	$00FF2852, D0
	BNE.b	loc_0000235E
loc_0000235C:
	RTS	;Predicted (Code-scan)
loc_0000235E:
	CMPI.w	#$00FF, D0
	BEQ.b	loc_00002376
	MOVE.w	D0, $00FF2852
	CMPI.w	#$00FD, D0
	BCS.b	loc_00002376
	CLR.w	$00FF2852
loc_00002376:
	MOVE.l	A0, -(A7)
	MOVEA.l	#$00A01FFF, A0
	TRAP	#1
	MOVEA.l	(A7)+, A0
	RTS
loc_00002384:
	MOVEM.l	A6/A5/A4/A3/A2/A1/A0/D7/D6/D5/D4/D3/D2/D1/D0, -(A7)
	MOVE.l	D0, -(A7)
	MOVE.w	#$0C00, D0
	BSR.w	loc_00003B24
	MOVE.l	(A7)+, D0
	MOVE.l	A0, -(A7)
	MOVE.w	(A6), D0
	ANDI.w	#$C000, D0
	CMPI.w	#$8000, D0
	BEQ.b	loc_000023AE
	MOVEA.l	(A7)+, A0	;Predicted (Code-scan)
	BSR.w	loc_00003B98	;Predicted (Code-scan)
	MOVEM.l	(A7)+, D0/D1/D2/D3/D4/D5/D6/D7/A0/A1/A2/A3/A4/A5/A6	;Predicted (Code-scan)
	RTS	;Predicted (Code-scan)
loc_000023AE:
	TRAP	#2
	MOVEA.l	A6, A4
	CLR.l	D0
	MOVE.w	(A6)+, D0
	ANDI.w	#$3FFF, D0
	LSL.w	#1, D0
	ADDA.l	D0, A4
	MOVEA.l	A0, A1
	CLR.w	D1
	MOVE.w	(A6)+, D0
	MOVEQ	#$00000010, D7
	MOVE.w	(A6)+, D6
loc_000023C8:
	LSL.w	#1, D6
	BCS.w	loc_0000240C
	SUBQ.w	#1, D7
	BNE.w	loc_000023D8
	MOVE.w	(A6)+, D6
	MOVEQ	#$00000010, D7
loc_000023D8:
	LSL.w	#1, D6
	BCS.w	loc_0000241A
	SUBQ.w	#1, D7
	BNE.w	loc_000023E8
	MOVE.w	(A6)+, D6
	MOVEQ	#$00000010, D7
loc_000023E8:
	LSL.w	#1, D6
	BCS.w	loc_00002446
	SUBQ.w	#1, D7
	BNE.w	loc_000023F8
	MOVE.w	(A6)+, D6
	MOVEQ	#$00000010, D7
loc_000023F8:
	LSL.w	#1, D6
	BCC.w	loc_000025FA
	SUBQ.w	#1, D7
	BNE.w	loc_0000245E
	MOVE.w	(A6)+, D6
	MOVEQ	#$00000010, D7
	BRA.w	loc_0000245E
loc_0000240C:
	SUBQ.w	#1, D7
	BNE.w	loc_00002454
	MOVE.w	(A6)+, D6
	MOVEQ	#$00000010, D7
	BRA.w	loc_00002454
loc_0000241A:
	SUBQ.w	#1, D7
	BNE.w	loc_00002424
	MOVE.w	(A6)+, D6	;Predicted (Code-scan)
	MOVEQ	#$00000010, D7	;Predicted (Code-scan)
loc_00002424:
	CLR.w	D5
	LSL.w	#1, D6
	ROXL.w	#1, D5
	SUBQ.w	#1, D7
	BNE.w	loc_00002434
	MOVE.w	(A6)+, D6	;Predicted (Code-scan)
	MOVEQ	#$00000010, D7	;Predicted (Code-scan)
loc_00002434:
	LSL.w	#1, D6
	ROXL.w	#1, D5
	SUBQ.w	#1, D7
	BNE.w	loc_00002490
	MOVE.w	(A6)+, D6	;Predicted (Code-scan)
	MOVEQ	#$00000010, D7	;Predicted (Code-scan)
	BRA.w	loc_00002490	;Predicted (Code-scan)
loc_00002446:
	SUBQ.w	#1, D7
	BNE.w	loc_0000246A
	MOVE.w	(A6)+, D6
	MOVEQ	#$00000010, D7
	BRA.w	loc_0000246A
loc_00002454:
	MOVE.w	(A4)+, D0
	MOVE.w	D0, (A1)+
	ADDQ.w	#1, D1
	BRA.w	loc_000025A6
loc_0000245E:
	MOVEA.l	A1, A3
	SUBQ.l	#2, A3
	MOVE.w	(A3), (A1)+
	ADDQ.w	#1, D1
	BRA.w	loc_000025A6
loc_0000246A:
	CLR.l	D5
	MOVEQ	#8, D2
loc_0000246E:
	LSL.w	#1, D6
	ROXL.w	#1, D5
	SUBQ.w	#1, D7
	BNE.w	loc_0000247C
	MOVE.w	(A6)+, D6
	MOVEQ	#$00000010, D7
loc_0000247C:
	DBF	D2, loc_0000246E
	ADDQ.w	#1, D5
	LSL.w	#1, D5
	MOVEA.l	A1, A3
	SUBA.l	D5, A3
	MOVE.w	(A3), (A1)+
	ADDQ.w	#1, D1
	BRA.w	loc_000025A6
loc_00002490:
	TST.w	D5
	BEQ.w	loc_0000252E
	SUBQ.w	#1, D5
	BEQ.w	loc_00002566
	SUBQ.w	#1, D5
	BEQ.w	loc_000024F4
	CLR.l	D5
	MOVEQ	#2, D2
loc_000024A6:
	LSL.w	#1, D6
	ROXL.w	#1, D5
	SUBQ.w	#1, D7
	BNE.w	loc_000024B4
	MOVE.w	(A6)+, D6
	MOVEQ	#$00000010, D7
loc_000024B4:
	DBF	D2, loc_000024A6
	MOVE.w	D5, D4
	ADDQ.w	#1, D4
	CLR.l	D5
	MOVEQ	#3, D2
loc_000024C0:
	LSL.w	#1, D6
	ROXL.w	#1, D5
	SUBQ.w	#1, D7
	BNE.w	loc_000024CE
	MOVE.w	(A6)+, D6
	MOVEQ	#$00000010, D7
loc_000024CE:
	DBF	D2, loc_000024C0
	MOVE.w	D5, D3
	ADDQ.w	#1, D3
	CLR.l	D5
	MOVEQ	#8, D2
loc_000024DA:
	LSL.w	#1, D6
	ROXL.w	#1, D5
	SUBQ.w	#1, D7
	BNE.w	loc_000024E8
	MOVE.w	(A6)+, D6
	MOVEQ	#$00000010, D7
loc_000024E8:
	DBF	D2, loc_000024DA
	ADDQ.w	#1, D5
	LSL.w	#1, D5
	BRA.w	loc_0000254C
loc_000024F4:
	CLR.w	D4
	CLR.l	D5
	MOVEQ	#3, D2
loc_000024FA:
	LSL.w	#1, D6
	ROXL.w	#1, D5
	SUBQ.w	#1, D7
	BNE.w	loc_00002508
	MOVE.w	(A6)+, D6
	MOVEQ	#$00000010, D7
loc_00002508:
	DBF	D2, loc_000024FA
	MOVE.w	D5, D3
	ADDQ.w	#1, D3
	CLR.l	D5
	MOVEQ	#8, D2
loc_00002514:
	LSL.w	#1, D6
	ROXL.w	#1, D5
	SUBQ.w	#1, D7
	BNE.w	loc_00002522
	MOVE.w	(A6)+, D6
	MOVEQ	#$00000010, D7
loc_00002522:
	DBF	D2, loc_00002514
	ADDQ.w	#1, D5
	LSL.w	#1, D5
	BRA.w	loc_0000254C
loc_0000252E:
	CLR.w	D4	;Predicted (Code-scan)
	MOVEQ	#1, D3	;Predicted (Code-scan)
	CLR.l	D5	;Predicted (Code-scan)
	MOVEQ	#8, D2	;Predicted (Code-scan)
loc_00002536:
	LSL.w	#1, D6	;Predicted (Code-scan)
	ROXL.w	#1, D5	;Predicted (Code-scan)
	SUBQ.w	#1, D7	;Predicted (Code-scan)
	BNE.w	loc_00002544	;Predicted (Code-scan)
	MOVE.w	(A6)+, D6	;Predicted (Code-scan)
	MOVEQ	#$00000010, D7	;Predicted (Code-scan)
loc_00002544:
	DBF	D2, loc_00002536	;Predicted (Code-scan)
	ADDQ.w	#1, D5	;Predicted (Code-scan)
	LSL.w	#1, D5	;Predicted (Code-scan)
loc_0000254C:
	MOVEA.l	A1, A3
	SUBA.w	D5, A3
loc_00002550:
	MOVE.l	A3, -(A7)
	MOVE.l	D3, D2
loc_00002554:
	MOVE.w	(A3)+, (A1)+
	ADDQ.w	#1, D1
	DBF	D2, loc_00002554
	MOVEA.l	(A7)+, A3
	DBF	D4, loc_00002550
	BRA.w	loc_000025A6
loc_00002566:
	CLR.l	D5
	MOVEQ	#2, D2
loc_0000256A:
	LSL.w	#1, D6
	ROXL.w	#1, D5
	SUBQ.w	#1, D7
	BNE.w	loc_00002578
	MOVE.w	(A6)+, D6
	MOVEQ	#$00000010, D7
loc_00002578:
	DBF	D2, loc_0000256A
	MOVE.w	D5, D4
	ADDQ.w	#1, D4
	CLR.l	D5
	MOVEQ	#8, D2
loc_00002584:
	LSL.w	#1, D6
	ROXL.w	#1, D5
	SUBQ.w	#1, D7
	BNE.w	loc_00002592
	MOVE.w	(A6)+, D6
	MOVEQ	#$00000010, D7
loc_00002592:
	DBF	D2, loc_00002584
	ADDQ.w	#1, D5
	LSL.w	#1, D5
	MOVEA.l	A1, A3
	SUBA.l	D5, A3
loc_0000259E:
	MOVE.w	(A3), (A1)+
	ADDQ.w	#1, D1
	DBF	D4, loc_0000259E
loc_000025A6:
	CMPI.w	#$0514, D1
	BCS.w	loc_000023C8
	MOVE.w	D1, D2	;Predicted (Code-scan)
	SUBI.w	#$0200, D2	;Predicted (Code-scan)
	CMPA.l	#$00010000, A5	;Predicted (Code-scan)
	BCC.w	loc_000025DC	;Predicted (Code-scan)
	MOVEM.l	A1/D0, -(A7)	;Predicted (Code-scan)
	MOVE.w	D2, D0	;Predicted (Code-scan)
	MOVEA.w	A5, A1	;Predicted (Code-scan)
	JSR	loc_000021BC	;Predicted (Code-scan)
	MOVEM.l	(A7)+, D0/A1	;Predicted (Code-scan)
	LSL.w	#1, D2	;Predicted (Code-scan)
	ADDA.w	D2, A5	;Predicted (Code-scan)
	MOVEA.l	A0, A2	;Predicted (Code-scan)
	ADDA.w	D2, A2	;Predicted (Code-scan)
	BRA.w	loc_000025E6	;Predicted (Code-scan)
loc_000025DC:
	SUBQ.w	#1, D2	;Predicted (Code-scan)
	MOVEA.l	A0, A2	;Predicted (Code-scan)
loc_000025E0:
	MOVE.w	(A2)+, (A5)+	;Predicted (Code-scan)
	DBF	D2, loc_000025E0	;Predicted (Code-scan)
loc_000025E6:
	MOVE.w	#$01FF, D2	;Predicted (Code-scan)
	MOVEA.l	A0, A1	;Predicted (Code-scan)
loc_000025EC:
	MOVE.w	(A2)+, (A1)+	;Predicted (Code-scan)
	DBF	D2, loc_000025EC	;Predicted (Code-scan)
	MOVE.w	#$0200, D1	;Predicted (Code-scan)
	BRA.w	loc_000023C8	;Predicted (Code-scan)
loc_000025FA:
	TST.w	D1
	BEQ.b	loc_0000261E
	CMPA.l	#$00010000, A5
	BCC.w	loc_00002616
	MOVE.w	D1, D0
	MOVEA.w	A5, A1
	JSR	loc_000021BC
	BRA.w	loc_0000261E
loc_00002616:
	SUBQ.w	#1, D1	;Predicted (Code-scan)
loc_00002618:
	MOVE.w	(A0)+, (A5)+	;Predicted (Code-scan)
	DBF	D1, loc_00002618	;Predicted (Code-scan)
loc_0000261E:
	TRAP	#3
	MOVEA.l	(A7)+, A0
	BSR.w	loc_00003B98
	MOVEM.l	(A7)+, D0/D1/D2/D3/D4/D5/D6/D7/A0/A1/A2/A3/A4/A5/A6
	RTS
	LEA	$00FF011C, A0
	MOVE.w	#1, (A0)+
	CLR.l	(A0)+
	MOVE.w	#1, (A0)+
	MOVE.w	#$009D, D0
loc_00002640:
	CLR.l	(A0)+
	DBF	D0, loc_00002640
	MOVE.w	#1, $00FF2854
	CLR.w	$00FF2856
	RTS
loc_00002656:
	TST.w	(A0)
	BNE.b	loc_0000265C
loc_0000265A:
	RTS	;Predicted (Code-scan)
loc_0000265C:
	CMPI.w	#$0200, D0
	BCC.b	loc_0000265A
	CMPI.w	#$0200, D1
	BCC.b	loc_0000265A
	MOVEM.l	A2/A1/A0/D7/D6/D5/D4/D3/D2/D1/D0, -(A7)
	LEA	$00FF011C, A1
	MOVEA.l	A1, A2
	MOVE.w	$00FF2854, D6
	MOVE.w	D6, D5
	LSL.w	#3, D6
	ANDI.l	#$000003FF, D6
	ADDA.l	D6, A1
	MOVE.w	$00FF2856, D6
	LSL.w	#3, D6
	ANDI.l	#$000003FF, D6
	ADDA.l	D6, A2
	ADDQ.l	#2, A2
	MOVE.w	(A2), D6
	ANDI.w	#$0F00, D6
	OR.w	D5, D6
	MOVE.w	D6, (A2)
	CLR.w	D7
	BSR.b	loc_00002710
	MOVE.w	D5, $00FF2854
	SUBQ.w	#1, D5
	MOVE.w	D5, $00FF2856
	MOVEM.l	(A7)+, D0/D1/D2/D3/D4/D5/D6/D7/A0/A1/A2
	RTS
	dc.b	$4A, $50, $66, $02, $4E, $75, $0C, $40, $02, $00, $64, $F8, $0C, $41, $02, $00, $64, $F2, $48, $E7, $FF, $E0, $43, $F9, $00, $FF, $01, $1C, $24, $49, $3C, $39 ;0x0 (0x000026BA-0x00002710, Entry count: 0x56) [Unknown data]
	dc.b	$00, $FF, $28, $54, $3A, $06, $E7, $4E, $02, $86, $00, $00, $03, $FF, $D3, $C6, $3C, $39, $00, $FF, $01, $1E, $3E, $06, $02, $47, $00, $7F, $02, $46, $0F, $00 ;0x20
	dc.b	$8C, $45, $33, $C6, $00, $FF, $01, $1E, $61, $0C, $33, $C5, $00, $FF, $28, $54, $4C, $DF, $07, $FF, $4E, $75 ;0x40
loc_00002710:
	MOVE.w	(A0)+, D4
	SUBQ.w	#1, D4
	LSR.w	#5, D2
loc_00002716:
	MOVE.w	(A0)+, D6
	ADD.w	D1, D6
	ADDQ.w	#1, D5
	MOVE.w	D6, (A1)+
	MOVE.w	(A0)+, D6
	TST.w	D4
	BEQ.b	loc_00002728
	OR.w	D5, D6
	BRA.b	loc_0000272A
loc_00002728:
	OR.w	D7, D6
loc_0000272A:
	MOVE.w	D6, (A1)+
	MOVE.w	(A0)+, D6
	ADD.w	D2, D6
	OR.w	D3, D6
	MOVE.w	D6, (A1)+
	MOVE.w	(A0)+, D6
	ADD.w	D0, D6
	TST.w	D6
	BNE.b	loc_0000273E
	ADDQ.w	#1, D6	;Predicted (Code-scan)
loc_0000273E:
	MOVE.w	D6, (A1)+
	DBF	D4, loc_00002716
	RTS
	dc.b	$2F, $00, $45, $F9, $00, $FF, $28, $5E, $47, $F9, $00, $FF, $28, $9E, $42, $80, $30, $08, $E3, $88, $D5, $C0, $E3, $88, $D7, $C0, $E5, $88, $D7, $C0, $20, $1F ;0x0 (0x00002746-0x00002872, Entry count: 0x12C) [Unknown data]
	dc.b	$4E, $75, $48, $E7, $F8, $70, $45, $F9, $00, $FF, $28, $5E, $47, $F9, $00, $FF, $28, $9E, $42, $43, $0C, $52, $FF, $FF, $67, $1A, $52, $43, $54, $8A, $D7, $FC ;0x20
	dc.b	$00, $00, $00, $14, $0C, $43, $00, $20, $66, $EA, $30, $7C, $FF, $FF, $4C, $DF, $0E, $0F, $4E, $75, $26, $C8, $36, $FC, $00, $02, $36, $C9, $48, $C0, $ED, $88 ;0x40
	dc.b	$26, $C0, $E1, $5A, $EB, $5A, $36, $C2, $42, $5B, $48, $C1, $ED, $89, $26, $C1, $34, $90, $30, $43, $4C, $DF, $0E, $1F, $4E, $75, $48, $E7, $00, $30, $61, $80 ;0x60
	dc.b	$34, $BC, $FF, $FF, $4C, $DF, $0C, $00, $4E, $75, $33, $C0, $00, $FF, $28, $5A, $33, $C1, $00, $FF, $28, $5C, $4E, $75, $48, $E7, $C0, $30, $61, $00, $FF, $62 ;0x80
	dc.b	$48, $C0, $D1, $AB, $00, $08, $48, $C1, $D3, $AB, $00, $10, $4C, $DF, $0C, $03, $4E, $75, $48, $E7, $C0, $30, $61, $00, $FF, $48, $48, $C0, $ED, $88, $27, $40 ;0xA0
	dc.b	$00, $08, $48, $C1, $ED, $89, $27, $41, $00, $10, $4C, $DF, $0C, $03, $4E, $75, $48, $E7, $40, $30, $61, $00, $FF, $2A, $32, $2B, $00, $0E, $08, $C1, $00, $0D ;0xC0
	dc.b	$08, $C1, $00, $0C, $02, $41, $FF, $00, $4A, $40, $66, $08, $50, $41, $08, $81, $00, $0B, $60, $06, $58, $41, $08, $C1, $00, $0B, $37, $41, $00, $0E, $4C, $DF ;0xE0
	dc.b	$0C, $02, $4E, $75, $48, $E7, $80, $30, $61, $00, $FE, $F6, $30, $2B, $00, $0E, $08, $80, $00, $0D, $08, $80, $00, $0C, $37, $40, $00, $0E, $08, $AB, $00, $04 ;0x100
	dc.b	$00, $0E, $4C, $DF, $0C, $01, $4E, $75, $00, $00, $28, $80 ;0x120
	dc.l	$00002876
	BSET.b	#1, $00FF0018
	RTS
	LEA	$00FF285E, A0
	MOVEQ	#$0000001F, D0
loc_00002888:
	MOVE.w	#$FFFF, (A0)+
	DBF	D0, loc_00002888
	MOVE.w	#$013F, D0
	LEA	$00FF289E, A0
loc_0000289A:
	CLR.w	(A0)+
	DBF	D0, loc_0000289A
	MOVE.w	#$0080, $00FF285A
	MOVE.w	#$0080, $00FF285C
	CLR.w	$00FF2858
loc_000028B6:
	TRAP	#5
	ORI.b	#$1F, D1	;Predicted (Code-scan)
loc_000028BC:
	CLR.l	D3
	CLR.w	D2
	LEA	$00FF289C, A4
	LEA	$00FF2B0A, A5
	MOVEA.l	#$FFFFFFFF, A2
loc_000028D2:
	CMPI.w	#$FFFF, (A4)
	BEQ.b	loc_00002906
	MOVE.w	$E(A5), D0
	BTST.l	#$0F, D0
	BNE.b	loc_00002906
	BTST.l	#$0E, D0
	BNE.b	loc_00002906
	MOVE.w	$C(A5), D0
	ANDI.w	#$1FFF, D0
	CMP.w	D0, D2
	BCS.b	loc_000028FC
	BNE.b	loc_00002906
	CMP.l	$10(A5), D3
	BGT.b	loc_00002906
loc_000028FC:
	MOVEA.l	A4, A2
	MOVEA.l	A5, A3
	MOVE.l	$10(A5), D3
	MOVE.w	D0, D2
loc_00002906:
	SUBQ.l	#2, A4
	SUBA.l	#$00000014, A5
	DBF	D7, loc_000028D2
	CMPA.l	#$FFFFFFFF, A2
	BNE.b	loc_0000293E
	LEA	$00FF289E, A5
	MOVEQ	#$0000001F, D0
loc_00002922:
	BCLR.b	#6, $E(A5)
	ADDA.l	#$00000014, A5
	DBF	D0, loc_00002922
	BSET.b	#1, $00FF0018
	BRA.w	loc_000028B6
loc_0000293E:
	MOVE.w	$E(A3), D0
	BTST.l	#$0D, D0
	BEQ.b	loc_00002968
	TST.b	D0	;Predicted (Code-scan)
	BNE.b	loc_0000295C	;Predicted (Code-scan)
	MOVE.b	#4, D0	;Predicted (Code-scan)
	BCHG.l	#$0C, D0	;Predicted (Code-scan)
	BTST.l	#$0B, D0	;Predicted (Code-scan)
	BEQ.b	loc_0000295C	;Predicted (Code-scan)
	ADDQ.w	#4, D0	;Predicted (Code-scan)
loc_0000295C:
	SUBQ.w	#1, D0	;Predicted (Code-scan)
	MOVE.w	D0, $E(A3)	;Predicted (Code-scan)
	BTST.l	#$0C, D0	;Predicted (Code-scan)
	BNE.b	loc_0000296A	;Predicted (Code-scan)
loc_00002968:
	BSR.b	loc_00002974
loc_0000296A:
	BSET.b	#6, $E(A3)
	BRA.w	loc_000028BC-2
loc_00002974:
	TST.w	$00FF2858
	BNE.b	loc_000029AC
	SUBQ.w	#1, (A2)
	BNE.b	loc_000029AC
	MOVEA.l	A3, A4
	MOVEA.l	(A4)+, A0
	ADDQ.w	#4, (A4)
	CLR.l	D0
	MOVE.w	(A4), D0
	ADDA.l	D0, A0
	MOVE.w	(A0)+, D1
	TST.w	D1
	BNE.b	loc_0000299A
	MOVE.w	#$FFFF, (A2)	;Predicted (Code-scan)
	BRA.w	loc_000029E6	;Predicted (Code-scan)
loc_0000299A:
	CMPI.w	#$FFFF, D1
	BNE.b	loc_000029A8
	MOVEA.l	A3, A4
	MOVEA.l	(A4)+, A0
	CLR.w	(A4)
	MOVE.w	(A0)+, D1
loc_000029A8:
	MOVE.w	D1, (A2)
	ADDQ.w	#2, (A4)
loc_000029AC:
	MOVEA.l	A3, A4
	MOVEA.l	(A4)+, A1
	CLR.l	D0
	MOVE.w	(A4)+, D0
	ADDA.l	D0, A1
	TST.l	(A1)
	BEQ.b	loc_000029E6
	MOVEA.l	(A1), A0
	MOVE.w	(A4)+, D2
	MOVE.l	(A4)+, D0
	LSR.l	#6, D0
	ADDI.w	#$0080, D0
	SUB.w	$00FF285A, D0
	MOVE.w	(A4)+, D3
	ANDI.w	#$E000, D3
	ADDQ.l	#2, A4
	MOVE.l	(A4)+, D1
	LSR.l	#6, D1
	ADDI.w	#$0080, D1
	SUB.w	$00FF285C, D1
	BSR.w	loc_00002656
loc_000029E6:
	RTS
	dc.b	$48, $E7, $E0, $30, $45, $F9, $00, $FF, $28, $5E, $47, $F9, $00, $FF, $28, $9E, $48, $C0, $48, $C1, $74, $1F, $0C, $5A, $FF, $FF, $67, $08, $D1, $AB, $00, $08 ;0x0 (0x000029E8-0x00002B36, Entry count: 0x14E) [Unknown data]
	dc.b	$D3, $AB, $00, $10, $D7, $FC, $00, $00, $00, $14, $51, $CA, $FF, $EA, $4C, $DF, $0C, $07, $4E, $75, $48, $E7, $18, $F0, $4A, $42, $67, $2A, $61, $00, $FD, $20 ;0x20
	dc.b	$36, $00, $38, $01, $48, $C3, $48, $C4, $ED, $8B, $ED, $8C, $96, $AB, $00, $08, $98, $AB, $00, $10, $87, $C2, $89, $C2, $48, $C3, $48, $C4, $D7, $AB, $00, $08 ;0x40
	dc.b	$D9, $AB, $00, $10, $53, $42, $4C, $DF, $0F, $18, $4E, $75, $48, $E7, $00, $30, $61, $00, $FC, $EC, $26, $C9, $36, $FC, $00, $02, $36, $C0, $34, $91, $4C, $DF ;0x60
	dc.b	$0C, $00, $4E, $75, $48, $E7, $00, $30, $61, $00, $FC, $D4, $E1, $58, $EB, $58, $37, $40, $00, $0C, $4C, $DF, $0C, $00, $4E, $75, $48, $E7, $80, $30, $61, $00 ;0x80
	dc.b	$FC, $BE, $30, $2B, $00, $0E, $08, $C0, $00, $0F, $37, $40, $00, $0E, $4C, $DF, $0C, $01, $4E, $75, $48, $E7, $80, $30, $61, $00, $FC, $A4, $30, $2B, $00, $0E ;0xA0
	dc.b	$08, $80, $00, $0F, $37, $40, $00, $0E, $4C, $DF, $0C, $01, $4E, $75, $48, $E7, $00, $30, $61, $00, $FC, $8A, $20, $53, $32, $6B, $00, $06, $4C, $DF, $0C, $00 ;0xC0
	dc.b	$4E, $75, $48, $E7, $60, $30, $45, $F9, $00, $FF, $28, $5E, $47, $F9, $00, $FF, $28, $9E, $74, $1F, $0C, $5A, $FF, $FF, $67, $0C, $32, $2B, $00, $0E, $08, $C1 ;0xE0
	dc.b	$00, $0F, $37, $41, $00, $0E, $D7, $FC, $00, $00, $00, $14, $51, $CA, $FF, $E6, $4C, $DF, $0C, $06, $4E, $75, $48, $E7, $60, $30, $45, $F9, $00, $FF, $28, $5E ;0x100
	dc.b	$47, $F9, $00, $FF, $28, $9E, $74, $1F, $0C, $5A, $FF, $FF, $67, $0C, $32, $2B, $00, $0E, $08, $81, $00, $0F, $37, $41, $00, $0E, $D7, $FC, $00, $00, $00, $14 ;0x120
	dc.b	$51, $CA, $FF, $E6, $4C, $DF, $0C, $06, $4E, $75, $00, $00, $2B, $42 ;0x140
	dc.l	$00002B3A
	CLR.w	$00FF011A
	RTS
	MOVEQ	#3, D0
	LEA	$00FF2B20, A0
loc_00002B4A:
	MOVE.w	#$FFFF, (A0)+
	CLR.w	(A0)+
	CLR.l	(A0)+
	DBF	D0, loc_00002B4A
	MOVEQ	#$0000003F, D0
	LEA	$00FF001A, A6
	LEA	$00FF009A, A5
loc_00002B64:
	MOVE.w	(A6)+, (A5)+
	DBF	D0, loc_00002B64
	MOVE.w	#1, $00FF011A
	CLR.w	$00FF2B1E
loc_00002B78:
	TRAP	#5
	ORI.b	#$B9, D1	;Predicted (Code-scan)
	ORI.b	#$FF, D0	;Predicted (Code-scan)
	ORI.b	#8, (A0)+	;Predicted (Code-scan)
	MOVE.w	#1, $00FF2B1E
loc_00002B8E:
	LEA	$00FF001A, A6
	LEA	$00FF009A, A5
	MOVEQ	#$0000003F, D0
loc_00002B9C:
	MOVE.w	(A6)+, (A5)+
	DBF	D0, loc_00002B9C
	LEA	$00FF001A, A6
	LEA	$00FF009A, A5
	LEA	$00FF2B20, A0
	MOVEQ	#3, D7
loc_00002BB6:
	CMPI.b	#$FF, (A0)
	BEQ.w	loc_00002C5C
	CLR.w	D0	;Predicted (Code-scan)
	MOVE.b	(A0), D0	;Predicted (Code-scan)
	MOVE.w	$4(A0), D1	;Predicted (Code-scan)
loc_00002BC6:
	MOVE.w	(A6,D0.w), D2	;Predicted (Code-scan)
	MOVE.w	D2, D4	;Predicted (Code-scan)
	ANDI.w	#$000F, D4	;Predicted (Code-scan)
	MULU.w	D1, D4	;Predicted (Code-scan)
	LSR.w	#8, D4	;Predicted (Code-scan)
	LSR.w	#4, D2	;Predicted (Code-scan)
	MOVE.w	D2, D3	;Predicted (Code-scan)
	ANDI.w	#$000F, D3	;Predicted (Code-scan)
	MULU.w	D1, D3	;Predicted (Code-scan)
	LSR.w	#4, D3	;Predicted (Code-scan)
	ANDI.w	#$00F0, D3	;Predicted (Code-scan)
	OR.w	D3, D4	;Predicted (Code-scan)
	LSR.w	#4, D2	;Predicted (Code-scan)
	MULU.w	D1, D2	;Predicted (Code-scan)
	ANDI.w	#$0F00, D2	;Predicted (Code-scan)
	OR.w	D2, D4	;Predicted (Code-scan)
	MOVE.w	D4, (A5,D0.w)	;Predicted (Code-scan)
	CMP.b	$1(A0), D0	;Predicted (Code-scan)
	BEQ.w	loc_00002C00	;Predicted (Code-scan)
	ADDQ.w	#2, D0	;Predicted (Code-scan)
	BRA.b	loc_00002BC6	;Predicted (Code-scan)
loc_00002C00:
	TST.b	$6(A0)	;Predicted (Code-scan)
	BEQ.b	loc_00002C54	;Predicted (Code-scan)
	BPL.b	loc_00002C34	;Predicted (Code-scan)
	SUB.w	$2(A0), D1	;Predicted (Code-scan)
	BPL.b	loc_00002C2E	;Predicted (Code-scan)
	CLR.w	D1	;Predicted (Code-scan)
	MOVE.b	(A0), D1	;Predicted (Code-scan)
	CLR.w	D2	;Predicted (Code-scan)
	MOVE.b	$1(A0), D2	;Predicted (Code-scan)
loc_00002C18:
	CLR.w	(A6,D1.w)	;Predicted (Code-scan)
	CMP.w	D2, D1	;Predicted (Code-scan)
	BEQ.b	loc_00002C24	;Predicted (Code-scan)
	ADDQ.w	#2, D1	;Predicted (Code-scan)
	BRA.b	loc_00002C18	;Predicted (Code-scan)
loc_00002C24:
	BSR.w	loc_00002E1C	;Predicted (Code-scan)
	MOVE.w	#$FFFF, (A0)	;Predicted (Code-scan)
	CLR.w	D1	;Predicted (Code-scan)
loc_00002C2E:
	MOVE.w	D1, $4(A0)	;Predicted (Code-scan)
	BRA.b	loc_00002C54	;Predicted (Code-scan)
loc_00002C34:
	CMPI.w	#$0100, D1	;Predicted (Code-scan)
	BCC.b	loc_00002C4A	;Predicted (Code-scan)
	ADD.w	$2(A0), D1	;Predicted (Code-scan)
	CMPI.w	#$0100, D1	;Predicted (Code-scan)
	BCS.b	loc_00002C50	;Predicted (Code-scan)
	MOVE.w	#$0100, D1	;Predicted (Code-scan)
	BRA.b	loc_00002C50	;Predicted (Code-scan)
loc_00002C4A:
	MOVE.w	#$FFFF, (A0)	;Predicted (Code-scan)
	CLR.w	D1	;Predicted (Code-scan)
loc_00002C50:
	MOVE.w	D1, $4(A0)	;Predicted (Code-scan)
loc_00002C54:
	MOVE.w	#1, $00FF2B1E	;Predicted (Code-scan)
loc_00002C5C:
	ADDQ.l	#8, A0
	DBF	D7, loc_00002BB6
	TST.w	$00FF2B1E
	BEQ.w	loc_00002B78
	BSET.b	#0, $00FF0018
	CLR.w	$00FF2B1E
	BRA.w	loc_00002B78
	dc.b	$48, $E7, $10, $80, $61, $40, $4A, $43, $6B, $10, $E3, $48, $10, $C0, $E3, $49, $10, $C1, $30, $C2, $42, $58, $10, $BC, $00, $01, $30, $03, $4C, $DF, $01, $08 ;0x0 (0x00002C7E-0x00002D4E, Entry count: 0xD0) [Unknown data]
	dc.b	$4E, $75, $48, $E7, $10, $80, $61, $1E, $4A, $43, $6B, $12, $E3, $48, $10, $C0, $E3, $49, $10, $C1, $30, $C2, $30, $FC, $01, $00, $10, $BC, $00, $FF, $30, $03 ;0x20
	dc.b	$4C, $DF, $01, $08, $4E, $75, $41, $F9, $00, $FF, $2B, $38, $76, $03, $0C, $10, $00, $FF, $67, $06, $51, $48, $51, $CB, $FF, $F6, $4E, $75, $48, $E7, $40, $86 ;0x40
	dc.b	$41, $F9, $00, $FF, $2B, $20, $E7, $48, $D0, $C0, $4D, $F9, $00, $FF, $00, $1A, $4B, $F9, $00, $FF, $00, $9A, $42, $40, $10, $10, $42, $41, $12, $28, $00, $01 ;0x60
	dc.b	$3D, $B5, $00, $00, $00, $00, $B2, $40, $67, $04, $54, $40, $60, $F2, $30, $BC, $FF, $FF, $4C, $DF, $61, $02, $4E, $75, $48, $E7, $40, $86, $41, $F9, $00, $FF ;0x80
	dc.b	$2B, $20, $E7, $48, $D0, $C0, $30, $BC, $FF, $FF, $4C, $DF, $61, $02, $4E, $75, $48, $E7, $80, $80, $41, $F9, $00, $FF, $2B, $20, $70, $03, $30, $BC, $FF, $FF ;0xA0
	dc.b	$50, $88, $51, $C8, $FF, $F8, $4C, $DF, $01, $01, $4E, $75, $00, $00, $2D, $54 ;0xC0
	dc.l	$00002D52
	RTS
	LEA	$00FF2B40, A0
	MOVEQ	#$0000000F, D0
loc_00002D5C:
	CLR.l	(A0)+
	DBF	D0, loc_00002D5C
loc_00002D62:
	TRAP	#5
	ORI.b	#$F9, D1	;Predicted (Code-scan)
	dc.b	$00, $FF, $2B, $40 ;0x0 (0x00002D68-0x00002D6C, Entry count: 0x4) [Unknown data]
	MOVEQ	#3, D7
loc_00002D6E:
	TST.w	(A0)
	BEQ.w	loc_00002DBE
	SUBQ.w	#1, $2(A0)
	BNE.w	loc_00002DBE
	MOVEA.l	$C(A0), A1
	MOVE.w	(A1)+, D0
	BNE.b	loc_00002D90
	MOVEA.l	$8(A0), A1	;Predicted (Code-scan)
	MOVE.w	(A1)+, D0	;Predicted (Code-scan)
	LSL.w	#1, D0	;Predicted (Code-scan)
	ADDA.w	D0, A1	;Predicted (Code-scan)
	MOVE.w	(A1)+, D0	;Predicted (Code-scan)
loc_00002D90:
	MOVE.w	D0, $2(A0)
	MOVEA.l	$8(A0), A2
	MOVE.w	(A2)+, D0
	SUBQ.w	#1, D0
loc_00002D9C:
	LEA	$00FF001A, A3
	ADDA.w	$4(A0), A3
	MOVE.w	(A2)+, D1
	LSL.w	#1, D1
	ADDA.w	D1, A3
	MOVE.w	(A1)+, (A3)
	DBF	D0, loc_00002D9C
	MOVE.l	A1, $C(A0)
	BSET.b	#0, $00FF0018
loc_00002DBE:
	ADDA.w	#$0010, A0
	DBF	D7, loc_00002D6E
	BRA.b	loc_00002D62
	dc.b	$48, $E7, $40, $40, $32, $00, $43, $F9, $00, $FF, $2B, $70, $70, $03, $4A, $51, $67, $0E, $92, $FC, $00, $10, $51, $C8, $FF, $F6, $4C, $DF, $02, $02, $4E, $75 ;0x0 (0x00002DC8-0x00002E1C, Entry count: 0x54) [Unknown data]
	dc.b	$EB, $49, $33, $41, $00, $04, $23, $48, $00, $08, $32, $18, $32, $81, $E3, $49, $D0, $C1, $23, $48, $00, $0C, $33, $7C, $00, $01, $00, $02, $4C, $DF, $02, $02 ;0x20
	dc.b	$4E, $75, $2F, $08, $41, $F9, $00, $FF, $2B, $40, $E9, $48, $D0, $C0, $42, $50, $20, $5F, $4E, $75 ;0x40
loc_00002E1C:
	MOVEM.l	A0/D0, -(A7)	;Predicted (Code-scan)
	LEA	$00FF2B40, A0	;Predicted (Code-scan)
	MOVEQ	#$0000000F, D0	;Predicted (Code-scan)
loc_00002E28:
	CLR.l	(A0)+	;Predicted (Code-scan)
	DBF	D0, loc_00002E28	;Predicted (Code-scan)
	MOVEM.l	(A7)+, D0/A0	;Predicted (Code-scan)
	RTS	;Predicted (Code-scan)
	dc.b	$00, $00, $2E, $42 ;0x0 (0x00002E34-0x00002E38, Entry count: 0x4) [Unknown data]
	dc.l	$00002E3C
	dc.b	$61, $00, $F0, $22, $4E, $75 ;0x0 (0x00002E3C-0x00002E42, Entry count: 0x6) [Unknown data]
	LEA	$00060580, A6
	MOVEA.l	#$0000B600, A5
	BSR.w	loc_00002384
	BSR.w	loc_00002FCA
	LEA	$00FF3036, A0
	MOVEQ	#7, D0
loc_00002E5E:
	CLR.w	(A0)
	ADDA.w	#$000C, A0
	DBF	D0, loc_00002E5E
	LEA	$00FF2B80, A0
	MOVE.l	A0, $00FF3030
loc_00002E74:
	TRAP	#5
	ORI.b	#$F9, D1	;Predicted (Code-scan)
	dc.b	$00, $FF, $30, $36 ;0x0 (0x00002E7A-0x00002E7E, Entry count: 0x4) [Unknown data]
	MOVEQ	#7, D7
loc_00002E80:
	TST.w	(A6)
	BEQ.w	loc_00002F66
	MOVE.b	$6(A6), D0	;Predicted (Code-scan)
	BEQ.w	loc_00002F66	;Predicted (Code-scan)
	SUBQ.b	#1, D0	;Predicted (Code-scan)
	BEQ.w	loc_00002EE0	;Predicted (Code-scan)
	SUBQ.b	#1, D0	;Predicted (Code-scan)
	BEQ.w	loc_00002F16	;Predicted (Code-scan)
	BSR.w	loc_00002F72	;Predicted (Code-scan)
	MOVE.b	$7(A6), D4	;Predicted (Code-scan)
	BTST.l	#7, D4	;Predicted (Code-scan)
	BEQ.b	loc_00002EB6	;Predicted (Code-scan)
	MOVEA.l	$8(A6), A0	;Predicted (Code-scan)
	BSR.w	loc_00003146	;Predicted (Code-scan)
	CLR.w	(A6)	;Predicted (Code-scan)
	BRA.w	loc_00002F66	;Predicted (Code-scan)
loc_00002EB6:
	BSR.w	loc_00003168	;Predicted (Code-scan)
	SUBQ.w	#1, D2	;Predicted (Code-scan)
	SUBQ.w	#1, D3	;Predicted (Code-scan)
	CLR.w	D1	;Predicted (Code-scan)
loc_00002EC0:
	MOVEM.l	D2/D0, -(A7)	;Predicted (Code-scan)
loc_00002EC4:
	BSR.w	loc_00001D96	;Predicted (Code-scan)
	ADDQ.w	#2, D0	;Predicted (Code-scan)
	DBF	D2, loc_00002EC4	;Predicted (Code-scan)
	MOVEM.l	(A7)+, D0/D2	;Predicted (Code-scan)
	ADDI.w	#$0080, D0	;Predicted (Code-scan)
	DBF	D3, loc_00002EC0	;Predicted (Code-scan)
	CLR.w	(A6)	;Predicted (Code-scan)
	BRA.w	loc_00002F66	;Predicted (Code-scan)
loc_00002EE0:
	BSR.w	loc_00002F72	;Predicted (Code-scan)
	MOVE.b	$7(A6), D4	;Predicted (Code-scan)
	BTST.l	#7, D4	;Predicted (Code-scan)
	BEQ.b	loc_00002EF6	;Predicted (Code-scan)
	BSR.w	loc_00003116	;Predicted (Code-scan)
	MOVE.l	A0, $8(A6)	;Predicted (Code-scan)
loc_00002EF6:
	BTST.l	#6, D4	;Predicted (Code-scan)
	BEQ.b	loc_00002F0C	;Predicted (Code-scan)
	ANDI.w	#3, D4	;Predicted (Code-scan)
	BSR.w	loc_00002FEC	;Predicted (Code-scan)
	CLR.b	$6(A6)	;Predicted (Code-scan)
	BRA.w	loc_00002F66	;Predicted (Code-scan)
loc_00002F0C:
	MOVE.b	#2, $6(A6)	;Predicted (Code-scan)
	CLR.w	$4(A6)	;Predicted (Code-scan)
loc_00002F16:
	BSR.w	loc_00002F72	;Predicted (Code-scan)
	CLR.w	D5	;Predicted (Code-scan)
	CLR.w	D6	;Predicted (Code-scan)
	MOVE.b	$4(A6), D5	;Predicted (Code-scan)
	MOVE.b	$5(A6), D6	;Predicted (Code-scan)
	ADDQ.w	#2, D5	;Predicted (Code-scan)
	CMP.w	D5, D2	;Predicted (Code-scan)
	BCC.b	loc_00002F2E	;Predicted (Code-scan)
	MOVE.w	D2, D5	;Predicted (Code-scan)
loc_00002F2E:
	ADDQ.w	#2, D6	;Predicted (Code-scan)
	CMP.w	D6, D3	;Predicted (Code-scan)
	BCC.b	loc_00002F36	;Predicted (Code-scan)
	MOVE.w	D3, D6	;Predicted (Code-scan)
loc_00002F36:
	MOVE.b	D5, $4(A6)	;Predicted (Code-scan)
	MOVE.b	D6, $5(A6)	;Predicted (Code-scan)
	CMP.w	D2, D5	;Predicted (Code-scan)
	BNE.b	loc_00002F4A	;Predicted (Code-scan)
	CMP.w	D3, D6	;Predicted (Code-scan)
	BNE.b	loc_00002F4A	;Predicted (Code-scan)
	CLR.b	$6(A6)	;Predicted (Code-scan)
loc_00002F4A:
	SUB.w	D5, D2	;Predicted (Code-scan)
	LSR.w	#1, D2	;Predicted (Code-scan)
	ADD.w	D2, D0	;Predicted (Code-scan)
	SUB.w	D6, D3	;Predicted (Code-scan)
	LSR.w	#1, D3	;Predicted (Code-scan)
	ADD.w	D3, D1	;Predicted (Code-scan)
	MOVE.w	D5, D2	;Predicted (Code-scan)
	MOVE.w	D6, D3	;Predicted (Code-scan)
	MOVE.b	$7(A6), D4	;Predicted (Code-scan)
	ANDI.w	#3, D4	;Predicted (Code-scan)
	BSR.w	loc_00002FEC	;Predicted (Code-scan)
loc_00002F66:
	ADDA.w	#$000C, A6
	DBF	D7, loc_00002E80
	BRA.w	loc_00002E74
loc_00002F72:
	CLR.w	D0	;Predicted (Code-scan)
	CLR.w	D1	;Predicted (Code-scan)
	CLR.w	D2	;Predicted (Code-scan)
	CLR.w	D3	;Predicted (Code-scan)
	MOVE.b	$2(A6), D0	;Predicted (Code-scan)
	MOVE.b	$3(A6), D1	;Predicted (Code-scan)
	MOVE.b	(A6), D2	;Predicted (Code-scan)
	MOVE.b	$1(A6), D3	;Predicted (Code-scan)
	RTS	;Predicted (Code-scan)
	dc.b	$0E, $E0, $00, $2C, $00, $0E ;0x0 (0x00002F8A-0x00002F90, Entry count: 0x6) [Unknown data]
loc_00002F90:
	dc.b	$0E, $EE, $04, $00, $0E, $E0, $00, $2C, $0E, $EE, $04, $00, $00, $EE, $0E, $E0, $00, $2C, $00, $EE ;0x0 (0x00002F90-0x00002FA4, Entry count: 0x14) [Unknown data]
loc_00002FA4:
	dc.b	$04, $00, $0E, $EE, $48, $E7, $C0, $80, $41, $FA, $FF, $DC, $70, $05, $72, $56, $61, $00, $EF, $A2, $41, $FA, $FF, $E4, $70, $05, $72, $76, $61, $00, $EF, $96 ;0x0 (0x00002FA4-0x00002FCA, Entry count: 0x26) [Unknown data]
	dc.b	$4C, $DF, $01, $03, $4E, $75 ;0x20
loc_00002FCA:
	MOVEM.l	A0/D1/D0, -(A7)
	LEA	loc_00002F90(PC), A0
	MOVEQ	#2, D0
	MOVEQ	#$0000005C, D1
	BSR.w	loc_00001F58
	LEA	loc_00002FA4(PC), A0
	MOVEQ	#2, D0
	MOVEQ	#$0000007C, D1
	BSR.w	loc_00001F58
	MOVEM.l	(A7)+, D0/D1/A0
	RTS
loc_00002FEC:
	MOVEM.l	D5/D4/D3/D2/D1/D0, -(A7)
	BSR.w	loc_00003168
	LSL.w	#8, D4
	LSL.w	#5, D4
	SUBQ.w	#3, D2
	SUBQ.w	#3, D3
	MOVEM.w	D2/D1/D0, -(A7)
	CLR.w	D5
	BSR.w	loc_0000308A
	ADDQ.w	#2, D0
	TST.w	D2
	BMI.b	loc_0000301C
	MOVE.w	#$85B2, D1
	OR.w	D4, D1
loc_00003012:
	BSR.w	loc_00001D96
	ADDQ.w	#2, D0
	DBF	D2, loc_00003012
loc_0000301C:
	MOVEQ	#1, D5
	BSR.b	loc_0000308A
	MOVEM.w	(A7)+, D0/D1/D2
	ADDI.w	#$0080, D0
	TST.w	D3
	BMI.b	loc_00003066
loc_0000302C:
	MOVEM.w	D2/D0, -(A7)
	MOVE.w	#$85B3, D1
	OR.w	D4, D1
	BSR.w	loc_00001D96
	ADDQ.w	#2, D0
	TST.w	D2
	BMI.b	loc_00003050
	MOVE.w	#$85B0, D1
	OR.w	D4, D1
loc_00003046:
	BSR.w	loc_00001D96
	ADDQ.w	#2, D0
	DBF	D2, loc_00003046
loc_00003050:
	MOVE.w	#$8DB3, D1
	OR.w	D4, D1
	BSR.w	loc_00001D96
	MOVEM.w	(A7)+, D0/D2
	ADDI.w	#$0080, D0
	DBF	D3, loc_0000302C
loc_00003066:
	MOVEQ	#2, D5
	BSR.b	loc_0000308A
	ADDQ.w	#2, D0
	TST.w	D2
	BMI.b	loc_00003080
	MOVE.w	#$95B2, D1
	OR.w	D4, D1
loc_00003076:
	BSR.w	loc_00001D96
	ADDQ.w	#2, D0
	DBF	D2, loc_00003076
loc_00003080:
	MOVEQ	#3, D5
	BSR.b	loc_0000308A
	MOVEM.l	(A7)+, D0/D1/D2/D3/D4/D5
	RTS
loc_0000308A:
	MOVEM.l	A0/D6/D5/D4/D3/D2/D1/D0, -(A7)
	BSR.w	loc_00001DC4
	TST.w	D1
	BEQ.b	loc_000030CA
	LEA	loc_000030E6(PC), A0	;Predicted (Code-scan)
	MOVE.w	D5, D3	;Predicted (Code-scan)
	LSL.w	#2, D3	;Predicted (Code-scan)
	MOVE.w	D1, D6	;Predicted (Code-scan)
	ANDI.w	#$1800, D6	;Predicted (Code-scan)
	LSR.w	#8, D6	;Predicted (Code-scan)
	LSR.w	#3, D6	;Predicted (Code-scan)
	ADD.w	D6, D3	;Predicted (Code-scan)
	CLR.w	D6	;Predicted (Code-scan)
	MOVE.b	(A0,D3.w), D6	;Predicted (Code-scan)
	LSL.w	#3, D6	;Predicted (Code-scan)
	ANDI.w	#$07FF, D1	;Predicted (Code-scan)
	SUBI.w	#$05B0, D1	;Predicted (Code-scan)
	BMI.b	loc_000030CA	;Predicted (Code-scan)
	CMPI.w	#6, D1	;Predicted (Code-scan)
	BCC.b	loc_000030CA	;Predicted (Code-scan)
	ADD.w	D1, D6	;Predicted (Code-scan)
	MOVE.b	$10(A0,D6.w), D3	;Predicted (Code-scan)
	BRA.b	loc_000030CE	;Predicted (Code-scan)
loc_000030CA:
	MOVE.b	#1, D3
loc_000030CE:
	MOVE.w	D5, D1
	LSL.w	#8, D1
	LSL.w	#3, D1
	ADDI.w	#$85B0, D1
	ADD.b	D3, D1
	OR.w	D4, D1
	BSR.w	loc_00001D96
	MOVEM.l	(A7)+, D0/D1/D2/D3/D4/D5/D6/A0
	RTS
loc_000030E6:
	dc.b	$00, $01, $02, $03, $01, $00, $03, $02, $02, $03, $00, $01, $03, $02, $01, $00, $04, $01, $05, $05, $04, $05, $00, $00, $04, $05, $05, $04, $05, $05, $00, $00 ;0x0 (0x000030E6-0x00003116, Entry count: 0x30) [Unknown data]
	dc.b	$04, $05, $04, $05, $05, $05, $00, $00, $04, $04, $04, $04, $04, $04, $00, $00 ;0x20
loc_00003116:
	MOVEM.l	D3/D2/D1/D0, -(A7)	;Predicted (Code-scan)
	MOVEA.l	$00FF3030, A0	;Predicted (Code-scan)
	MOVE.l	A0, -(A7)	;Predicted (Code-scan)
	BSR.b	loc_00003168	;Predicted (Code-scan)
	SUBQ.w	#1, D3	;Predicted (Code-scan)
loc_00003126:
	MOVE.w	D0, -(A7)	;Predicted (Code-scan)
	MOVE.w	D2, D1	;Predicted (Code-scan)
	BSR.w	loc_00001D5A	;Predicted (Code-scan)
	MOVE.w	(A7)+, D0	;Predicted (Code-scan)
	ADDI.w	#$0080, D0	;Predicted (Code-scan)
	DBF	D3, loc_00003126	;Predicted (Code-scan)
	MOVE.l	A0, $00FF3030	;Predicted (Code-scan)
	MOVEA.l	(A7)+, A0	;Predicted (Code-scan)
	MOVEM.l	(A7)+, D0/D1/D2/D3	;Predicted (Code-scan)
	RTS	;Predicted (Code-scan)
loc_00003146:
	MOVEM.l	A6/A5/A0/D7/D6/D5/D3/D2/D1/D0, -(A7)	;Predicted (Code-scan)
	BSR.b	loc_00003168	;Predicted (Code-scan)
	MOVE.w	D0, D5	;Predicted (Code-scan)
	MOVE.w	D2, D7	;Predicted (Code-scan)
	SUBQ.w	#1, D7	;Predicted (Code-scan)
	MOVE.w	D3, D6	;Predicted (Code-scan)
	SUBQ.w	#1, D6	;Predicted (Code-scan)
	MOVEA.l	A0, A6	;Predicted (Code-scan)
	MOVE.l	A0, $00FF3030	;Predicted (Code-scan)
	BSR.w	loc_00001CBA	;Predicted (Code-scan)
	MOVEM.l	(A7)+, D0/D1/D2/D3/D5/D6/D7/A0/A5/A6	;Predicted (Code-scan)
	RTS	;Predicted (Code-scan)
loc_00003168:
	LSL.w	#7, D1
	LSL.w	#1, D0
	ADD.w	D1, D0
	ADDI.w	#$C000, D0
	RTS
	dc.b	$48, $E7, $02, $80, $41, $F9, $00, $FF, $30, $8A, $7C, $07, $4A, $50, $67, $10, $90, $FC, $00, $0C, $51, $CE, $FF, $F6, $30, $06, $4C, $DF, $01, $40, $60, $FE ;0x0 (0x00003174-0x000036F2, Entry count: 0x57E) [Unknown data]
	dc.b	$11, $40, $00, $02, $11, $41, $00, $03, $10, $82, $11, $43, $00, $01, $11, $44, $00, $07, $11, $7C, $00, $01, $00, $06, $30, $06, $4C, $DF, $01, $40, $4E, $75 ;0x20
	dc.b	$2F, $08, $C0, $FC, $00, $0C, $41, $F9, $00, $FF, $30, $36, $D0, $C0, $11, $7C, $00, $03, $00, $06, $20, $5F, $4E, $75, $48, $E7, $F8, $02, $C0, $FC, $00, $0C ;0x40
	dc.b	$4D, $F9, $00, $FF, $30, $36, $DD, $C0, $61, $00, $FD, $94, $18, $2E, $00, $07, $02, $44, $00, $03, $61, $00, $FE, $02, $4C, $DF, $40, $1F, $4E, $75, $48, $E7 ;0x60
	dc.b	$FC, $02, $C0, $FC, $00, $0C, $4D, $F9, $00, $FF, $30, $36, $DD, $C0, $61, $00, $FD, $6E, $02, $04, $00, $03, $1A, $2E, $00, $07, $02, $05, $00, $FC, $8A, $04 ;0x80
	dc.b	$1D, $45, $00, $07, $61, $00, $FF, $4E, $02, $45, $00, $03, $E1, $4D, $EB, $4D, $53, $42, $53, $43, $48, $E7, $A0, $00, $61, $00, $EB, $96, $02, $41, $9F, $FF ;0xA0
	dc.b	$82, $45, $61, $00, $EB, $5E, $54, $40, $51, $CA, $FF, $EE, $4C, $DF, $00, $05, $06, $40, $00, $80, $51, $CB, $FF, $DE, $4C, $DF, $40, $3F, $4E, $75, $48, $E7 ;0xC0
	dc.b	$FC, $00, $61, $00, $FF, $10, $C8, $FC, $00, $05, $53, $42, $53, $43, $48, $E7, $A0, $00, $61, $00, $EB, $5C, $3A, $01, $02, $45, $07, $F0, $0C, $45, $05, $B0 ;0xE0
	dc.b	$66, $24, $3A, $01, $02, $45, $00, $0F, $67, $1C, $0C, $45, $00, $06, $65, $0A, $5B, $45, $0C, $45, $00, $06, $65, $02, $5B, $45, $DA, $44, $02, $41, $FF, $F0 ;0x100
	dc.b	$D2, $45, $61, $00, $EA, $FE, $54, $40, $51, $CA, $FF, $C8, $4C, $DF, $00, $05, $06, $40, $00, $80, $51, $CB, $FF, $B8, $4C, $DF, $00, $3F, $4E, $75, $2F, $0E ;0x120
	dc.b	$C0, $FC, $00, $0C, $4D, $F9, $00, $FF, $30, $36, $DD, $C0, $42, $40, $4A, $56, $67, $00, $00, $0A, $10, $2E, $00, $06, $2C, $5F, $4E, $75, $70, $FF, $2C, $5F ;0x140
	dc.b	$4E, $75, $2F, $04, $61, $00, $FE, $9A, $38, $00, $4E, $45, $00, $01, $30, $04, $61, $CC, $4A, $40, $66, $F4, $30, $04, $28, $1F, $4E, $75, $48, $E7, $FE, $80 ;0x160
	dc.b	$2F, $00, $30, $3C, $00, $20, $61, $00, $08, $28, $20, $1F, $42, $68, $00, $10, $31, $7C, $FF, $FF, $00, $12, $60, $34, $48, $E7, $FE, $80, $2F, $00, $30, $3C ;0x180
	dc.b	$00, $20, $61, $00, $08, $0C, $20, $1F, $31, $7C, $FF, $FF, $00, $10, $42, $68, $00, $12, $60, $18, $48, $E7, $FE, $80, $2F, $00, $30, $3C, $00, $20, $61, $00 ;0x1A0
	dc.b	$07, $F0, $20, $1F, $42, $68, $00, $10, $42, $68, $00, $12, $BC, $47, $64, $02, $3E, $06, $30, $87, $4A, $46, $6B, $00, $01, $98, $31, $40, $00, $02, $31, $41 ;0x1C0
	dc.b	$00, $04, $31, $42, $00, $06, $31, $43, $00, $08, $31, $46, $00, $0A, $3C, $04, $3E, $05, $34, $10, $3A, $02, $8A, $C6, $28, $05, $48, $44, $31, $46, $00, $0C ;0x1E0
	dc.b	$31, $47, $00, $0E, $42, $46, $30, $06, $02, $40, $00, $07, $66, $16, $08, $06, $00, $03, $66, $0A, $7E, $02, $61, $00, $01, $12, $60, $00, $00, $08, $7E, $03 ;0x200
	dc.b	$61, $00, $01, $08, $4E, $45, $00, $01, $10, $39, $00, $FF, $27, $DA, $08, $00, $00, $06, $66, $00, $01, $2E, $08, $00, $00, $05, $66, $00, $01, $26, $08, $00 ;0x220
	dc.b	$00, $04, $66, $00, $01, $50, $10, $39, $00, $FF, $27, $DC, $08, $00, $00, $00, $66, $16, $08, $00, $00, $01, $66, $2A, $08, $00, $00, $02, $66, $50, $08, $00 ;0x240
	dc.b	$00, $03, $66, $7E, $52, $46, $60, $9E, $4A, $45, $67, $F8, $7E, $03, $61, $00, $00, $BA, $53, $45, $94, $68, $00, $0C, $42, $46, $70, $67, $61, $00, $EF, $84 ;0x260
	dc.b	$60, $84, $36, $28, $00, $0E, $53, $43, $BA, $43, $64, $D8, $36, $28, $00, $0C, $D6, $42, $B6, $68, $00, $0A, $62, $CC, $34, $03, $7E, $03, $61, $00, $00, $8C ;0x280
	dc.b	$52, $45, $42, $46, $70, $67, $61, $00, $EF, $5A, $60, $00, $FF, $5A, $4A, $44, $67, $00, $00, $16, $7E, $03, $61, $72, $53, $44, $53, $42, $42, $46, $70, $67 ;0x2A0
	dc.b	$61, $00, $EF, $40, $60, $00, $FF, $40, $4A, $68, $00, $10, $67, $96, $7E, $03, $61, $58, $70, $67, $61, $00, $EF, $2C, $00, $42, $80, $00, $30, $82, $60, $00 ;0x2C0
	dc.b	$00, $CA, $36, $28, $00, $0C, $53, $43, $B8, $43, $64, $00, $00, $22, $36, $02, $52, $43, $B6, $68, $00, $0A, $62, $00, $00, $16, $34, $03, $7E, $03, $61, $2A ;0x2E0
	dc.b	$52, $44, $42, $46, $70, $67, $61, $00, $EE, $FA, $60, $00, $FE, $FA, $4A, $68, $00, $10, $67, $00, $FF, $50, $7E, $03, $61, $10, $70, $67, $61, $00, $EE, $E4 ;0x300
	dc.b	$00, $42, $C0, $00, $30, $82, $60, $00, $00, $82, $48, $E7, $28, $00, $30, $28, $00, $06, $54, $40, $C0, $C4, $D0, $68, $00, $02, $32, $28, $00, $08, $52, $41 ;0x320
	dc.b	$0C, $41, $00, $01, $66, $02, $52, $41, $C2, $C5, $D2, $68, $00, $04, $34, $28, $00, $06, $36, $28, $00, $08, $28, $07, $61, $00, $E9, $4C, $4C, $DF, $00, $14 ;0x340
	dc.b	$4E, $75, $7E, $02, $61, $C4, $30, $82, $70, $66, $61, $00, $EE, $96, $60, $3A, $4E, $45, $00, $01, $10, $39, $00, $FF, $27, $DA, $08, $00, $00, $06, $66, $00 ;0x360
	dc.b	$00, $20, $08, $00, $00, $05, $66, $00, $00, $18, $08, $00, $00, $04, $66, $00, $00, $10, $60, $DC, $4A, $68, $00, $12, $6B, $00, $FE, $CA, $7E, $03, $61, $8A ;0x380
	dc.b	$7A, $FF, $30, $85, $70, $68, $61, $00, $EE, $5A, $3E, $10, $61, $00, $06, $76, $4C, $DF, $01, $7F, $4E, $75, $48, $E7, $40, $80, $42, $40, $12, $18, $67, $16 ;0x3A0
	dc.b	$0C, $01, $00, $0A, $65, $F6, $0C, $01, $00, $7B, $67, $F0, $0C, $01, $00, $7C, $67, $EA, $52, $40, $60, $E6, $4C, $DF, $01, $02, $4E, $75, $48, $E7, $C0, $E0 ;0x3C0
	dc.b	$45, $FA, $00, $92, $42, $40, $10, $18, $66, $0A, $12, $BC, $00, $00, $4C, $DF, $07, $03, $4E, $75, $0C, $40, $00, $1A, $65, $36, $0C, $40, $00, $3F, $65, $24 ;0x3E0
	dc.b	$67, $1E, $0C, $40, $00, $7B, $65, $36, $0C, $40, $00, $7D, $67, $1E, $0C, $40, $00, $80, $65, $0C, $0C, $40, $00, $B7, $65, $30, $0C, $40, $00, $B8, $67, $14 ;0x400
	dc.b	$72, $0F, $60, $4A, $32, $00, $06, $41, $00, $BE, $60, $42, $72, $1F, $60, $3E, $32, $00, $60, $3A, $12, $FC, $00, $01, $32, $3C, $00, $83, $60, $30, $04, $40 ;0x420
	dc.b	$00, $40, $42, $41, $12, $32, $00, $00, $60, $0E, $04, $40, $00, $80, $42, $41, $12, $32, $00, $00, $06, $41, $00, $50, $10, $10, $0C, $00, $00, $7B, $67, $0A ;0x440
	dc.b	$0C, $00, $00, $7C, $66, $08, $54, $41, $60, $02, $52, $41, $52, $88, $12, $C1, $60, $00, $FF, $72, $21, $23, $25, $27, $29, $2A, $2C, $2E, $30, $32, $34, $36 ;0x460
	dc.b	$38, $3A, $3C, $3E, $40, $43, $45, $47, $49, $4A, $4B, $4C, $4D, $4E, $51, $54, $57, $5A, $5D, $5E, $5F, $60, $61, $63, $65, $67, $68, $69, $6A, $6B, $6C, $6D ;0x480
	dc.b	$6E, $6F, $20, $22, $24, $26, $28, $42, $62, $64, $66, $1B, $1A, $4C, $4D, $0F, $0F, $0F, $0F, $0F, $48, $E7, $F0, $C0, $22, $48, $30, $7C, $C0, $00, $36, $00 ;0x4A0
	dc.b	$42, $42, $14, $19, $67, $42, $0C, $02, $00, $7B, $67, $12, $0C, $02, $00, $7C, $67, $0C, $0C, $02, $00, $0D, $66, $18, $54, $41, $30, $03, $60, $E2, $53, $40 ;0x4C0
	dc.b	$53, $41, $06, $42, $E4, $F0, $61, $00, $E7, $92, $52, $40, $52, $41, $60, $D0, $06, $42, $E4, $F0, $61, $00, $E7, $84, $53, $41, $34, $3C, $E5, $2F, $61, $00 ;0x4E0
	dc.b	$E7, $7A, $52, $41, $52, $40, $60, $B8, $4C, $DF, $03, $0F, $4E, $75, $48, $E7, $F0, $C0, $22, $48, $30, $7C, $C0, $00, $36, $00, $42, $42, $14, $19, $67, $24 ;0x500
	dc.b	$0C, $02, $00, $7B, $67, $F4, $0C, $02, $00, $7C, $67, $EE, $0C, $02, $00, $0D, $66, $06, $54, $41, $30, $03, $60, $E2, $06, $42, $E4, $F0, $61, $00, $E7, $3C ;0x520
	dc.b	$52, $40, $60, $D6, $4C, $DF, $03, $0F, $4E, $75, $48, $E7, $00, $A0, $48, $E7, $80, $80, $30, $3C, $00, $10, $61, $00, $04, $58, $24, $48, $4C, $DF, $01, $01 ;0x540
	dc.b	$2F, $09, $22, $4A, $61, $00, $FE, $76, $20, $49, $22, $5F, $61, $10, $2F, $08, $20, $4A, $61, $00, $04, $B0, $20, $5F, $4C, $DF, $05, $00, $4E, $75 ;0x560
	MOVEM.l	A0/D7/D6/D5/D4/D3/D2/D1/D0, -(A7)
	MOVE.w	D0, D6
	MOVE.w	D0, D4
	MOVE.w	D1, D7
loc_000036FC:
	CLR.w	D0
	MOVE.b	(A0)+, D0
	BEQ.b	loc_0000372E
	CMPI.b	#$0D, D0
	BNE.b	loc_0000370E
	MOVE.w	D4, D6	;Predicted (Code-scan)
	ADDQ.w	#2, D7	;Predicted (Code-scan)
	BRA.b	loc_000036FC	;Predicted (Code-scan)
loc_0000370E:
	CMPI.b	#$0E, D0
	BNE.b	loc_00003718
	ADDQ.w	#1, D6	;Predicted (Code-scan)
	BRA.b	loc_000036FC	;Predicted (Code-scan)
loc_00003718:
	CMPI.b	#3, D0
	BCC.b	loc_00003722
	LSL.w	#8, D0
	MOVE.b	(A0)+, D0
loc_00003722:
	BSR.w	loc_00001FE8
	ADDQ.w	#2, D6
	ADDA.w	#$0080, A1
	BRA.b	loc_000036FC
loc_0000372E:
	MOVEM.l	(A7)+, D0/D1/D2/D3/D4/D5/D6/D7/A0
	RTS
	dc.b	$48, $E7, $08, $C0, $2F, $00, $30, $3C, $00, $10, $61, $00, $03, $E4, $20, $1F, $78, $3F, $61, $56, $61, $00, $FF, $38, $61, $00, $04, $4A, $4C, $DF, $03, $10 ;0x0 (0x00003734-0x00003B24, Entry count: 0x3F0) [Unknown data]
	dc.b	$4E, $75, $48, $E7, $08, $C0, $2F, $00, $30, $3C, $00, $10, $61, $00, $03, $C2, $20, $1F, $78, $10, $61, $34, $61, $00, $FF, $16, $61, $00, $04, $28, $4C, $DF ;0x20
	dc.b	$03, $10, $4E, $75, $48, $E7, $08, $80, $2F, $00, $30, $3C, $00, $10, $61, $00, $03, $A0, $20, $1F, $2F, $09, $78, $0F, $61, $10, $22, $5F, $61, $00, $FF, $60 ;0x40
	dc.b	$61, $00, $04, $02, $4C, $DF, $01, $10, $4E, $75, $48, $E7, $FC, $00, $1A, $04, $22, $48, $30, $03, $66, $02, $76, $06, $0C, $43, $00, $07, $65, $02, $76, $06 ;0x60
	dc.b	$78, $01, $53, $43, $67, $06, $C8, $FC, $00, $0A, $60, $F6, $26, $04, $28, $02, $42, $41, $74, $10, $98, $83, $6B, $06, $52, $42, $72, $01, $60, $F6, $D8, $83 ;0x80
	dc.b	$4A, $41, $66, $0C, $0C, $43, $00, $01, $67, $06, $4A, $40, $67, $04, $14, $05, $12, $C2, $86, $FC, $00, $0A, $66, $DA, $12, $BC, $00, $00, $4C, $DF, $00, $3F ;0xA0
	dc.b	$4E, $75, $33, $FC, $FF, $FF, $00, $FF, $30, $96, $4E, $75, $4A, $79, $00, $FF, $30, $96, $6A, $24, $48, $E7, $F8, $00, $70, $01, $72, $14, $74, $26, $36, $3C ;0xC0
	dc.b	$00, $07, $38, $3C, $00, $C3, $61, $00, $F9, $58, $33, $C0, $00, $FF, $30, $96, $4E, $45, $00, $01, $4C, $DF, $00, $1F, $4E, $75, $48, $E7, $80, $00, $30, $39 ;0xE0
	dc.b	$00, $FF, $30, $96, $6B, $0C, $61, $00, $F9, $78, $33, $FC, $FF, $FF, $00, $FF, $30, $96, $4C, $DF, $00, $01, $4E, $45, $00, $01, $4E, $75, $48, $E7, $FF, $FE ;0x100
	dc.b	$3A, $00, $4D, $F9, $00, $FF, $30, $98, $48, $E7, $80, $80, $30, $3C, $00, $A0, $61, $00, $02, $BE, $2A, $48, $4C, $DF, $01, $01, $30, $39, $00, $FF, $30, $96 ;0x120
	dc.b	$6B, $00, $01, $7C, $61, $00, $F9, $52, $78, $04, $08, $05, $00, $01, $67, $02, $42, $44, $34, $7C, $F0, $00, $7E, $15, $3B, $7C, $00, $02, $00, $9E, $22, $4D ;0x140
	dc.b	$72, $01, $61, $00, $01, $D2, $7C, $03, $26, $4D, $4A, $13, $67, $66, $0C, $46, $00, $25, $64, $00, $00, $94, $42, $40, $10, $1B, $0C, $00, $00, $03, $64, $04 ;0x160
	dc.b	$E1, $48, $10, $1B, $22, $4A, $61, $00, $E7, $2C, $54, $46, $D4, $FC, $00, $80, $B4, $FC, $E0, $00, $66, $06, $34, $7C, $F0, $00, $60, $0A, $B4, $FC, $00, $00 ;0x180
	dc.b	$66, $04, $34, $7C, $DF, $00, $30, $04, $4E, $45, $00, $01, $08, $39, $00, $06, $00, $FF, $27, $DA, $66, $14, $08, $39, $00, $04, $00, $FF, $27, $DA, $66, $0A ;0x1A0
	dc.b	$08, $39, $00, $05, $00, $FF, $27, $DA, $67, $04, $42, $40, $42, $44, $51, $C8, $FF, $D8, $60, $96, $10, $10, $67, $50, $0C, $00, $00, $0C, $66, $06, $61, $00 ;0x1C0
	dc.b	$01, $46, $60, $50, $53, $6D, $00, $9E, $54, $47, $0C, $47, $00, $19, $67, $06, $52, $88, $60, $00, $FF, $6A, $4A, $6D, $00, $9E, $67, $38, $61, $00, $00, $D0 ;0x1E0
	dc.b	$7E, $17, $52, $88, $60, $00, $FF, $58, $7C, $03, $53, $6D, $00, $9E, $54, $47, $0C, $47, $00, $19, $66, $00, $FF, $54, $4A, $6D, $00, $9E, $67, $16, $61, $00 ;0x200
	dc.b	$00, $AE, $7E, $17, $60, $00, $FF, $44, $61, $00, $00, $FC, $08, $05, $00, $00, $66, $00, $00, $8C, $2F, $08, $42, $43, $70, $24, $72, $19, $30, $7C, $C0, $00 ;0x220
	dc.b	$08, $05, $00, $02, $67, $06, $0C, $43, $00, $32, $64, $36, $34, $3C, $E5, $2F, $08, $03, $00, $04, $66, $04, $34, $3C, $E5, $6E, $61, $00, $E4, $5E, $4E, $45 ;0x240
	dc.b	$00, $01, $52, $43, $08, $39, $00, $06, $00, $FF, $27, $DA, $66, $14, $08, $39, $00, $04, $00, $FF, $27, $DA, $66, $0A, $08, $39, $00, $05, $00, $FF, $27, $DA ;0x260
	dc.b	$67, $BE, $70, $24, $72, $19, $30, $7C, $C0, $00, $34, $3C, $E5, $2F, $61, $00, $E4, $2A, $20, $5F, $4A, $13, $66, $0E, $14, $10, $67, $22, $52, $88, $0C, $02 ;0x280
	dc.b	$00, $0C, $67, $00, $FE, $96, $3B, $7C, $00, $02, $00, $9E, $61, $20, $38, $3C, $00, $06, $7E, $17, $4A, $13, $66, $00, $FE, $B2, $60, $00, $FE, $A2, $2F, $08 ;0x2A0
	dc.b	$20, $4D, $61, $00, $01, $A0, $20, $5F, $4C, $DF, $7F, $FF, $4E, $75, $74, $01, $48, $E7, $FF, $8A, $48, $E7, $80, $80, $30, $3C, $00, $50, $61, $00, $01, $12 ;0x2C0
	dc.b	$28, $48, $4C, $DF, $01, $01, $42, $80, $30, $3C, $CB, $06, $72, $22, $74, $03, $20, $4C, $61, $00, $E3, $32, $2A, $00, $04, $45, $00, $80, $7E, $21, $42, $46 ;0x2E0
	dc.b	$2C, $4C, $61, $00, $E2, $82, $06, $40, $00, $80, $51, $CA, $FF, $E4, $2F, $08, $20, $4C, $61, $00, $01, $50, $20, $5F, $4C, $DF, $51, $FF, $4E, $45, $00, $04 ;0x300
	dc.b	$51, $CA, $FF, $AE, $4E, $75, $0C, $6D, $00, $02, $00, $9E, $65, $08, $0C, $47, $00, $15, $67, $02, $61, $98, $48, $E7, $F8, $60, $24, $48, $42, $42, $14, $1A ;0x320
	dc.b	$67, $00, $00, $88, $0C, $02, $00, $03, $64, $06, $12, $C2, $12, $DA, $60, $EC, $66, $16, $20, $5E, $16, $18, $67, $0E, $0C, $03, $00, $03, $64, $04, $12, $C3 ;0x340
	dc.b	$16, $18, $12, $C3, $60, $EE, $60, $D4, $0C, $02, $00, $04, $66, $10, $24, $1E, $42, $43, $16, $1A, $20, $49, $78, $0F, $61, $00, $FC, $F0, $60, $BE, $0C, $02 ;0x360
	dc.b	$00, $05, $66, $14, $14, $1A, $61, $00, $67, $20, $61, $00, $FA, $90, $4A, $11, $67, $04, $52, $89, $60, $F8, $60, $A4, $0C, $02, $00, $06, $66, $10, $20, $5E ;0x380
	dc.b	$61, $00, $FA, $7A, $4A, $11, $67, $04, $52, $89, $60, $F8, $60, $8E, $0C, $02, $00, $0F, $64, $10, $0C, $02, $00, $0D, $67, $06, $0C, $02, $00, $0C, $66, $FE ;0x3A0
	dc.b	$4A, $41, $66, $06, $12, $C2, $60, $00, $FF, $74, $42, $11, $20, $4A, $53, $88, $4C, $DF, $06, $1F, $4E, $75, $48, $E7, $80, $80, $30, $3C, $01, $FF, $41, $F9 ;0x3C0
	dc.b	$00, $FF, $30, $B8, $42, $18, $51, $C8, $FF, $FC, $4C, $DF, $01, $01, $4E, $75 ;0x3E0
loc_00003B24:
	MOVEM.l	A3/A2/A1/D2/D1/D0, -(A7)
	LEA	$00FF32B8, A0
	LEA	$00FF30B8, A1
	MOVE.w	#$01FF, D1
	ADDI.w	#$000F, D0
	LSR.w	#4, D0
loc_00003B3E:
	TST.b	(A1)
	BEQ.b	loc_00003B50
loc_00003B42:
	ADDQ.l	#1, A1
	ADDA.w	#$0010, A0
	DBF	D1, loc_00003B3E
	BRA.w	loc_00003B96	;Predicted (Code-scan)
loc_00003B50:
	MOVEA.l	A0, A2
	MOVEA.l	A1, A3
	MOVE.w	D0, D2
loc_00003B56:
	TST.b	(A1)
	BNE.b	loc_00003B42
	SUBQ.w	#1, D2
	BEQ.b	loc_00003B6C
	ADDQ.l	#1, A1
	ADDA.w	#$0010, A0
	DBF	D1, loc_00003B56
	BRA.w	loc_00003B96	;Predicted (Code-scan)
loc_00003B6C:
	MOVEQ	#1, D2
loc_00003B6E:
	LEA	$00FF30B8, A1
	MOVE.w	#$01FF, D1
loc_00003B78:
	CMP.b	(A1)+, D2
	BEQ.b	loc_00003B82
	DBF	D1, loc_00003B78
	BRA.b	loc_00003B86
loc_00003B82:
	ADDQ.b	#1, D2
	BRA.b	loc_00003B6E
loc_00003B86:
	SUBQ.w	#1, D0
loc_00003B88:
	MOVE.b	D2, (A3)+
	DBF	D0, loc_00003B88
	MOVEA.l	A2, A0
	MOVEM.l	(A7)+, D0/D1/D2/A1/A2/A3
	RTS
loc_00003B96:
	BRA.b	loc_00003B96	;Predicted (Code-scan)
loc_00003B98:
	MOVEM.l	A0/D0, -(A7)
	SUBA.l	#$00FF32B8, A0
	MOVE.l	A0, D0
	LSR.l	#4, D0
	LEA	$00FF30B8, A0
	ADDA.l	D0, A0
	MOVE.b	(A0), D0
	BEQ.b	loc_00003BC0
loc_00003BB2:
	CMP.b	(A0), D0
	BNE.b	loc_00003BBA
	CLR.b	(A0)+
	BRA.b	loc_00003BB2
loc_00003BBA:
	MOVEM.l	(A7)+, D0/A0
	RTS
loc_00003BC0:
	BRA.b	loc_00003BC0	;Predicted (Code-scan)
	dc.b	$20, $39, $00, $FF, $CE, $D2, $02, $40, $07, $FF, $0C, $40, $01, $00, $64, $04, $70, $03, $4E, $75, $0C, $40, $04, $00, $64, $04, $42, $40, $4E, $75, $0C, $40 ;0x0 (0x00003BC2-0x00003C8A, Entry count: 0xC8) [Unknown data]
	dc.b	$05, $00, $64, $04, $70, $01, $4E, $75, $70, $02, $4E, $75, $48, $E7, $C0, $00, $02, $80, $00, $00, $07, $FF, $22, $39, $00, $FF, $CE, $D2, $02, $41, $07, $FF ;0x20
	dc.b	$B2, $40, $65, $14, $06, $80, $00, $00, $08, $00, $4A, $79, $00, $FF, $D6, $52, $67, $06, $53, $79, $00, $FF, $D6, $52, $22, $39, $00, $FF, $CE, $D2, $02, $81 ;0x40
	dc.b	$FF, $FF, $F8, $00, $D2, $80, $23, $C1, $00, $FF, $CE, $D2, $4C, $DF, $00, $03, $4E, $75, $48, $E7, $C0, $80, $61, $3A, $03, $D0, $4C, $DF, $01, $03, $4E, $75 ;0x60
	dc.b	$48, $E7, $C0, $80, $61, $2C, $03, $90, $4C, $DF, $01, $03, $4E, $75, $48, $E7, $40, $80, $61, $1E, $08, $01, $00, $0F, $66, $08, $03, $10, $67, $0C, $70, $01 ;0x80
	dc.b	$60, $0A, $03, $10, $66, $04, $70, $01, $60, $02, $42, $40, $4C, $DF, $01, $02, $4E, $75, $41, $F9, $00, $FF, $52, $B8, $53, $40, $32, $00, $08, $80, $00, $0F ;0xA0
	dc.b	$E6, $48, $48, $C0, $D1, $C0, $4E, $75 ;0xC0
	MOVEM.l	A0/D0, -(A7)
	LEA	$00FF52B8, A0
	MOVEQ	#$00000027, D0
loc_00003C96:
	CLR.l	(A0)+
	DBF	D0, loc_00003C96
	MOVEM.l	(A7)+, D0/A0
	RTS
	dc.b	$48, $E7, $80, $80, $53, $40, $02, $40, $00, $FF, $48, $C0, $41, $F9, $00, $FF, $53, $58, $D1, $C0, $10, $81, $4C, $DF, $01, $01, $4E, $75, $2F, $08, $53, $40 ;0x0 (0x00003CA2-0x00003E00, Entry count: 0x15E) [Unknown data]
	dc.b	$02, $40, $00, $FF, $48, $C0, $41, $F9, $00, $FF, $53, $58, $D1, $C0, $42, $80, $10, $10, $20, $5F, $4E, $75, $2F, $08, $53, $40, $02, $40, $00, $FF, $48, $C0 ;0x20
	dc.b	$41, $F9, $00, $FF, $53, $58, $D1, $C0, $52, $10, $20, $5F, $4E, $75, $2F, $08, $53, $40, $02, $40, $00, $FF, $48, $C0, $41, $F9, $00, $FF, $53, $58, $D1, $C0 ;0x40
	dc.b	$53, $10, $20, $5F, $4E, $75, $48, $E7, $60, $C0, $42, $42, $20, $7C, $00, $20, $00, $01, $01, $48, $00, $02, $0C, $80, $41, $42, $59, $00, $67, $20, $01, $48 ;0x60
	dc.b	$20, $02, $0C, $80, $41, $42, $59, $00, $67, $14, $42, $80, $32, $3C, $07, $FF, $22, $48, $01, $C9, $00, $00, $50, $89, $51, $C9, $FF, $F8, $74, $FF, $20, $3C ;0x80
	dc.b	$41, $42, $59, $00, $01, $C8, $00, $02, $01, $C8, $20, $02, $30, $02, $4C, $DF, $03, $06, $4E, $75, $23, $FC, $00, $20, $00, $0B, $00, $FF, $53, $9A, $4E, $75 ;0xA0
	dc.b	$48, $E7, $C0, $C0, $53, $40, $22, $79, $00, $FF, $53, $9A, $03, $09, $00, $00, $30, $C1, $58, $89, $51, $C8, $FF, $F6, $23, $C9, $00, $FF, $53, $9A, $4C, $DF ;0xC0
	dc.b	$03, $03, $4E, $75, $48, $E7, $C0, $C0, $53, $40, $22, $79, $00, $FF, $53, $9A, $58, $89, $51, $C8, $FF, $FC, $23, $C9, $00, $FF, $53, $9A, $4C, $DF, $03, $03 ;0xE0
	dc.b	$4E, $75, $48, $E7, $C0, $C0, $53, $40, $22, $79, $00, $FF, $53, $9A, $32, $18, $03, $89, $00, $00, $58, $89, $51, $C8, $FF, $F6, $23, $C9, $00, $FF, $53, $9A ;0x100
	dc.b	$4C, $DF, $03, $03, $4E, $75, $48, $E7, $E0, $C0, $20, $7C, $00, $20, $00, $0B, $22, $48, $D3, $FC, $00, $00, $20, $00, $42, $42, $32, $3C, $07, $FB, $01, $08 ;0x120
	dc.b	$00, $00, $01, $89, $00, $00, $D4, $40, $58, $88, $58, $89, $51, $C9, $FF, $F0, $05, $88, $00, $00, $05, $89, $00, $00, $4C, $DF, $03, $07, $4E, $75 ;0x140
	MOVEM.l	A1/A0/D2, -(A7)
	MOVEA.l	#$0020000B, A0
	CLR.w	D2
	MOVE.w	#$07FB, D1
loc_00003E10:
	MOVEP.w	$0(A0), D0
	ADD.w	D0, D2
	ADDQ.l	#4, A0
	DBF	D1, loc_00003E10
	MOVEP.w	$0(A0), D0
	CMP.w	D0, D2
	BEQ.b	loc_00003E7E
	MOVEA.l	#$0020000B, A0
	MOVEA.l	A0, A1
	ADDA.l	#$00002000, A1
	CLR.w	D2
	MOVE.w	#$07FB, D1
loc_00003E38:
	MOVEP.w	$0(A1), D0
	MOVEP.w	D0, $0(A0)
	ADD.w	D0, D2
	ADDQ.l	#4, A0
	ADDQ.l	#4, A1
	DBF	D1, loc_00003E38
	MOVEP.w	$0(A1), D0
	MOVEP.w	D0, $0(A0)
	CMP.w	D0, D2
	BEQ.b	loc_00003E7E
	MOVEA.l	#$0020000B, A0
	MOVEA.l	A0, A1
	ADDA.l	#$00002000, A1
	CLR.w	D2
	MOVE.w	#$07FC, D1
loc_00003E6A:
	MOVEP.w	D2, $0(A0)
	MOVEP.w	D2, $0(A1)
	ADDQ.l	#4, A0
	ADDQ.l	#4, A1
	DBF	D1, loc_00003E6A
	MOVEQ	#-1, D0
	BRA.b	loc_00003E80
loc_00003E7E:
	CLR.w	D0	;Predicted (Code-scan)
loc_00003E80:
	MOVEA.l	#$0020000B, A0
	MOVEP.l	$0(A0), D1
	MOVEM.l	(A7)+, D2/A0/A1
	RTS
	dc.b	$48, $E7, $80, $80, $61, $00, $FE, $C0, $41, $F9, $00, $00, $3E, $FE, $70, $02, $61, $00, $FF, $02, $41, $F9, $00, $FF, $CA, $6E, $70, $01, $61, $00, $FE, $F6 ;0x0 (0x00003E90-0x00004000, Entry count: 0x170) [Unknown data]
	dc.b	$41, $F9, $00, $FF, $CA, $9E, $70, $03, $61, $00, $FE, $EA, $41, $F9, $00, $FF, $CA, $B2, $70, $03, $61, $00, $FE, $DE, $41, $F9, $00, $FF, $DB, $66, $70, $02 ;0x20
	dc.b	$61, $00, $FE, $D2, $41, $F9, $00, $FF, $CE, $CE, $30, $3C, $0B, $D4, $E2, $48, $61, $00, $FE, $C2, $41, $F9, $00, $FF, $52, $B8, $30, $3C, $00, $E0, $E2, $48 ;0x40
	dc.b	$61, $00, $FE, $B2, $61, $00, $FE, $D2, $4C, $DF, $01, $01, $4E, $75, $61, $62, $79, $00, $48, $E7, $80, $80, $61, $00, $FE, $4E, $70, $02, $61, $00, $FE, $78 ;0x60
	dc.b	$41, $F9, $00, $FF, $CA, $6E, $70, $01, $61, $00, $FE, $48, $41, $F9, $00, $FF, $CA, $9E, $70, $03, $61, $00, $FE, $3C, $41, $F9, $00, $FF, $CA, $B2, $70, $03 ;0x80
	dc.b	$61, $00, $FE, $30, $41, $F9, $00, $FF, $DB, $66, $70, $02, $61, $00, $FE, $24, $41, $F9, $00, $FF, $CE, $CE, $30, $3C, $0B, $D4, $E2, $48, $61, $00, $FE, $14 ;0xA0
	dc.b	$41, $F9, $00, $FF, $52, $B8, $30, $3C, $00, $E0, $E2, $48, $61, $00, $FE, $04, $4C, $DF, $01, $01, $4E, $75, $48, $E7, $F8, $40, $2F, $08, $48, $E7, $80, $80 ;0xC0
	dc.b	$30, $3C, $00, $20, $61, $00, $FB, $AE, $22, $48, $4C, $DF, $01, $01, $20, $49, $70, $07, $42, $98, $51, $C8, $FF, $FC, $70, $01, $72, $01, $74, $26, $76, $1A ;0xE0
	dc.b	$38, $3C, $00, $43, $61, $00, $F3, $40, $33, $40, $00, $1E, $70, $1D, $72, $16, $74, $08, $76, $04, $78, $03, $61, $00, $F0, $44, $70, $04, $72, $03, $41, $FA ;0x100
	dc.b	$03, $2C, $61, $00, $F6, $74, $70, $10, $72, $03, $41, $FA, $03, $98, $61, $00, $F6, $68, $70, $1C, $72, $03, $41, $FA, $04, $04, $61, $00, $F6, $5C, $70, $1C ;0x120
	dc.b	$72, $11, $34, $3C, $E5, $6B, $30, $7C, $C0, $00, $61, $00, $DE, $12, $70, $1E, $52, $42, $61, $00, $DE, $0A, $42, $69, $00, $14, $42, $69, $00, $16, $42, $69 ;0x140
	dc.b	$00, $18, $33, $7C, $00, $03, $00, $1A, $33, $7C, $00, $03, $00, $1C, $61, $00 ;0x160
