; ########################################################################################
; # Generated by the active disassembly feature of the Exodus emulation platform
; #
; # Creation Date:   2020-11-25 22:30:31
; # Analysis Region: 0x00001FE8 - 0x0000200C
; ########################################################################################

 org $00001FE8

	MOVEM.l	A1/A0/D2/D1/D0, -(A7)
	MOVE.w	A1, D2			 ; $F000
	SUBI.w	#$0010, D0 ; control codes are $00~$0F
;	BMI.b	*+$46 ; branch to $203A if control code
	BMI.b	*+$48 ; add 2 cuz exodus adds it in maybe. 
	EXT.l	D0 ; contains character code from table
;	LSL.w	#5, D0 ; multiply character code by 32 for 16x16 font
	LSL.w	#4, D0	; 8x16 font so we only do half that much
	LEA	$000648E6, A0	; ROM offset for font
	ADDA.l	D0, A0
	MOVEM.l	A0/D0, -(A7)
	MOVE.w	#$0080, D0 
;	BSR.w *+$1B1A	; jump to $3B24