; ########################################################################################
; # Generated by the active disassembly feature of the Exodus emulation platform
; #
; # Creation Date:   2020-11-29 23:24:11
; # Analysis Region: 0x00001F00 - 0x00004000
; ########################################################################################

 org $00001F00

	dc.b	$1C, $24, $24, $48, $4C, $DF, $01, $01, $36, $48, $49, $F9, $00, $06, $00, $00, $74, $2B, $20, $4C, $22, $4A, $10, $3C, $00, $0F, $12, $3C, $00, $0E, $61, $00 ;0x0 (0x00001F00-0x00001FE8, Entry count: 0xE8) [Unknown data]
	dc.b	$FF, $70, $28, $48, $20, $4A, $32, $4B, $30, $3C, $00, $40, $61, $00, $FB, $14, $D6, $FC, $00, $80, $51, $CA, $FF, $DC, $42, $80, $30, $0B, $2A, $40, $4D, $F9 ;0x20
	dc.b	$00, $06, $05, $80, $61, $00, $04, $3E, $2F, $08, $20, $4A, $61, $00, $1C, $4A, $20, $5F, $4C, $DF, $7F, $07, $4E, $75, $48, $E7, $80, $C0, $43, $F9, $00, $FF ;0x40
	dc.b	$00, $1A, $D2, $C1, $53, $40, $32, $D8, $51, $C8, $FF, $FC, $08, $F9, $00, $00, $00, $FF, $00, $18, $4C, $DF, $03, $01, $4E, $75, $48, $E7, $80, $40, $43, $F9 ;0x60
	dc.b	$00, $FF, $00, $1A, $D2, $C1, $53, $40, $32, $C2, $51, $C8, $FF, $FC, $08, $F9, $00, $00, $00, $FF, $00, $18, $4C, $DF, $02, $01, $4E, $75, $48, $E7, $40, $80 ;0x80
	dc.b	$70, $00, $41, $FA, $01, $18, $30, $39, $00, $FF, $28, $10, $02, $40, $00, $FF, $12, $30, $00, $00, $E1, $49, $30, $39, $00, $FF, $00, $16, $02, $40, $00, $FF ;0xA0
	dc.b	$12, $30, $00, $00, $30, $39, $00, $FF, $28, $10, $D0, $41, $33, $C0, $00, $FF, $28, $10, $4C, $DF, $01, $02, $4E, $75, $61, $C2, $C0, $C1, $48, $40, $06, $40 ;0xC0
	dc.b	$01, $00, $C0, $C2, $E0, $88, $4E, $75 ;0xE0
loc_00001FE8:
	MOVEM.l	A1/A0/D2/D1/D0, -(A7)
	MOVE.w	A1, D2
	SUBI.w	#$0010, D0
	BMI.b	loc_0000203A
	EXT.l	D0
	LSL.w	#5, D0
	LEA	$000648E6, A0
	ADDA.l	D0, A0
	MOVEM.l	A0/D0, -(A7)
	MOVE.w	#$0080, D0
	BSR.w	loc_00003B24
	MOVEA.l	A0, A1
	MOVEM.l	(A7)+, D0/A0
	MOVE.l	A1, -(A7)
	MOVE.b	#$0F, D0
	MOVE.b	#$0E, D1
	BSR.w	*+$FE72
	MOVEA.l	(A7)+, A0
	MOVEA.w	D2, A1
	MOVE.w	#$0040, D0
	BSR.w	*+$FA18
	BSR.w	loc_00003B98
	LSR.w	#5, D2
	ORI.w	#$E000, D2
	BRA.w	loc_00002068
loc_0000203A:
	MOVE.w	#$E52F, D2	;Predicted (Code-scan)
	MOVEA.w	#$C000, A0	;Predicted (Code-scan)
	MOVE.w	D6, D0	;Predicted (Code-scan)
	MOVE.w	D7, D1	;Predicted (Code-scan)
	BSR.w	*+$FDA6	;Predicted (Code-scan)
	ADDQ.w	#1, D0	;Predicted (Code-scan)
	BSR.w	*+$FDA0	;Predicted (Code-scan)
	MOVE.w	D6, D0	;Predicted (Code-scan)
	ADDQ.w	#1, D1	;Predicted (Code-scan)
	BSR.w	*+$FD98	;Predicted (Code-scan)
	ADDQ.w	#1, D0	;Predicted (Code-scan)
	BSR.w	*+$FD92	;Predicted (Code-scan)
	MOVEM.l	(A7)+, D0/D1/D2/A0/A1	;Predicted (Code-scan)
	RTS	;Predicted (Code-scan)
	dc.b	$4C, $DF, $03, $07 ;0x0 (0x00002064-0x00002068, Entry count: 0x4) [Unknown data]
loc_00002068:
	MOVEA.w	#$C000, A0
	MOVE.w	D6, D0
	MOVE.w	D7, D1
	BSR.w	*+$FD7C
	ADDQ.w	#1, D1
	ADDQ.w	#1, D2
	BSR.w	*+$FD74
	ADDQ.w	#1, D6
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	MOVEM.l	(A7)+, D0/D1/D2/A0/A1
	RTS
	MOVE.l	A6, -(A7)
	MOVE.l	A6, $00FF2812
	LEA	$00FF284E, A6
	MOVEM.l	A5/A4/A3/A2/A1/A0/D7/D6/D5/D4/D3/D2/D1/D0, -(A6)
	MOVEA.l	(A7)+, A6
	RTS
	LEA	$00FF2816, A6
	MOVEM.l	(A6)+, D0/D1/D2/D3/D4/D5/D6/D7/A0/A1/A2/A3/A4/A5
	MOVEA.l	$00FF2812, A6
	RTS
	dc.b	$07, $9B, $F5, $FD, $62, $D5, $D6, $C6, $E4, $5A, $22, $1D, $0F, $93, $3C, $5B, $F1, $75, $1C, $78, $FB, $70, $2D, $69, $02, $E5, $5F, $23, $DB, $DE, $2F, $FF ;0x0 (0x000020BC-0x0000262C, Entry count: 0x570) [Unknown data]
	dc.b	$9F, $53, $05, $EC, $99, $17, $AA, $18, $B6, $19, $C8, $26, $DA, $B4, $C1, $90, $56, $98, $88, $74, $2B, $E9, $D3, $34, $55, $E1, $8B, $C5, $01, $2C, $D9, $41 ;0x20
	dc.b	$48, $EE, $0B, $71, $B9, $DF, $82, $A9, $30, $42, $29, $85, $BE, $6B, $F3, $58, $B1, $54, $7A, $15, $CF, $50, $F6, $0C, $3A, $51, $E2, $C2, $B8, $9D, $57, $67 ;0x40
	dc.b	$06, $CD, $AF, $66, $2A, $0D, $11, $6E, $1A, $F0, $E7, $CB, $ED, $31, $24, $94, $F7, $A0, $FC, $D8, $6D, $F2, $80, $76, $65, $60, $8E, $B2, $4B, $96, $A3, $79 ;0x60
	dc.b	$59, $BD, $10, $A1, $44, $28, $3F, $89, $46, $64, $8F, $EB, $F9, $08, $9C, $D7, $A4, $E8, $AE, $C9, $EF, $63, $B0, $45, $43, $61, $38, $C7, $09, $BB, $52, $16 ;0x80
	dc.b	$21, $1E, $0E, $7B, $4C, $04, $25, $47, $B5, $B7, $DD, $1F, $3D, $6C, $03, $5E, $D0, $35, $86, $39, $DC, $7E, $E3, $20, $A6, $A8, $CC, $84, $7C, $6A, $C0, $E6 ;0xA0
	dc.b	$83, $40, $0A, $2E, $B3, $CA, $5C, $81, $AB, $A2, $49, $F8, $27, $97, $8D, $BF, $37, $FE, $91, $3B, $32, $7F, $9E, $72, $4E, $92, $95, $3E, $87, $77, $14, $73 ;0xC0
	dc.b	$CE, $BC, $A7, $4D, $D1, $D4, $6F, $AD, $33, $4A, $C3, $8C, $FA, $13, $5D, $E0, $12, $F4, $8A, $C4, $A5, $BA, $36, $1B, $68, $EA, $9A, $D2, $7D, $AC, $00, $4F ;0xE0
	dc.b	$48, $E7, $F0, $E0, $42, $82, $34, $00, $E3, $8A, $26, $08, $D4, $83, $B7, $82, $08, $02, $00, $11, $67, $00, $00, $38, $33, $FC, $8F, $02, $00, $C0, $00, $04 ;0x100
	dc.b	$32, $09, $02, $41, $3F, $FF, $00, $41, $40, $00, $33, $C1, $00, $C0, $00, $04, $32, $09, $E0, $49, $EC, $49, $33, $C1, $00, $C0, $00, $04, $43, $F9, $00, $C0 ;0x120
	dc.b	$00, $00, $53, $80, $32, $98, $51, $C8, $FF, $FC, $60, $00, $00, $92, $4E, $53, $FF, $F0, $32, $09, $E0, $49, $EC, $49, $00, $41, $00, $80, $37, $01, $32, $09 ;0x140
	dc.b	$02, $41, $3F, $FF, $00, $41, $40, $00, $37, $01, $22, $08, $48, $41, $E2, $49, $02, $41, $00, $7F, $00, $41, $97, $00, $37, $01, $22, $08, $E2, $89, $E0, $49 ;0x160
	dc.b	$02, $41, $00, $FF, $00, $41, $96, $00, $37, $01, $32, $08, $E2, $49, $02, $41, $00, $FF, $00, $41, $95, $00, $37, $01, $32, $00, $E0, $49, $02, $41, $00, $FF ;0x180
	dc.b	$00, $41, $94, $00, $37, $01, $02, $40, $00, $FF, $00, $40, $93, $00, $37, $00, $37, $3C, $8F, $02, $45, $F9, $00, $C0, $00, $04, $61, $00, $F7, $96, $32, $09 ;0x1A0
	dc.b	$02, $41, $3F, $FF, $00, $41, $40, $00, $34, $81, $32, $09, $E0, $49, $EC, $49, $34, $81, $33, $D0, $00, $C0, $00, $00, $61, $00, $F5, $B6, $4E, $5B, $4C, $DF ;0x1C0
	dc.b	$07, $0F, $4E, $75, $48, $E7, $C0, $C0, $33, $FC, $8F, $02, $00, $C0, $00, $04, $32, $09, $02, $41, $3F, $FF, $00, $41, $40, $00, $33, $C1, $00, $C0, $00, $04 ;0x1E0
	dc.b	$32, $09, $E0, $49, $EC, $49, $33, $C1, $00, $C0, $00, $04, $43, $F9, $00, $C0, $00, $00, $53, $80, $32, $98, $51, $C8, $FF, $FC, $4C, $DF, $03, $03, $4E, $75 ;0x200
	dc.b	$4E, $42, $22, $7C, $00, $0F, $60, $00, $32, $3C, $1F, $FF, $20, $7C, $00, $A0, $00, $00, $33, $FC, $01, $00, $00, $A1, $12, $00, $33, $FC, $01, $00, $00, $A1 ;0x220
	dc.b	$11, $00, $08, $39, $00, $00, $00, $A1, $11, $00, $66, $F6, $10, $19, $10, $80, $B0, $10, $66, $FA, $52, $88, $51, $C9, $FF, $F4, $33, $FC, $00, $00, $00, $A0 ;0x240
	dc.b	$1F, $FE, $33, $FC, $00, $00, $00, $A1, $11, $00, $33, $FC, $00, $00, $00, $A1, $12, $00, $4E, $71, $4E, $71, $4E, $71, $4E, $71, $33, $FC, $01, $00, $00, $A1 ;0x260
	dc.b	$12, $00, $30, $3C, $C3, $4F, $51, $C8, $FF, $FE, $42, $79, $00, $FF, $28, $52, $4E, $43, $4E, $75, $4A, $40, $67, $08, $B0, $79, $00, $FF, $28, $52, $66, $02 ;0x280
	dc.b	$4E, $75, $0C, $40, $00, $FF, $67, $12, $33, $C0, $00, $FF, $28, $52, $0C, $40, $00, $FD, $65, $06, $42, $79, $00, $FF, $28, $52, $2F, $08, $20, $7C, $00, $A0 ;0x2A0
	dc.b	$1F, $FF, $4E, $41, $20, $5F, $4E, $75, $48, $E7, $FF, $FE, $2F, $00, $30, $3C, $0C, $00, $61, $00, $17, $94, $20, $1F, $2F, $08, $30, $16, $02, $40, $C0, $00 ;0x2C0
	dc.b	$0C, $40, $80, $00, $67, $0C, $20, $5F, $61, $00, $17, $F2, $4C, $DF, $7F, $FF, $4E, $75, $4E, $42, $28, $4E, $42, $80, $30, $1E, $02, $40, $3F, $FF, $E3, $48 ;0x2E0
	dc.b	$D9, $C0, $22, $48, $42, $41, $30, $1E, $7E, $10, $3C, $1E, $E3, $4E, $65, $00, $00, $40, $53, $47, $66, $00, $00, $06, $3C, $1E, $7E, $10, $E3, $4E, $65, $00 ;0x300
	dc.b	$00, $3E, $53, $47, $66, $00, $00, $06, $3C, $1E, $7E, $10, $E3, $4E, $65, $00, $00, $5A, $53, $47, $66, $00, $00, $06, $3C, $1E, $7E, $10, $E3, $4E, $64, $00 ;0x320
	dc.b	$01, $FE, $53, $47, $66, $00, $00, $5C, $3C, $1E, $7E, $10, $60, $00, $00, $54, $53, $47, $66, $00, $00, $44, $3C, $1E, $7E, $10, $60, $00, $00, $3C, $53, $47 ;0x340
	dc.b	$66, $00, $00, $06, $3C, $1E, $7E, $10, $42, $45, $E3, $4E, $E3, $55, $53, $47, $66, $00, $00, $06, $3C, $1E, $7E, $10, $E3, $4E, $E3, $55, $53, $47, $66, $00 ;0x360
	dc.b	$00, $54, $3C, $1E, $7E, $10, $60, $00, $00, $4C, $53, $47, $66, $00, $00, $20, $3C, $1E, $7E, $10, $60, $00, $00, $18, $30, $1C, $32, $C0, $52, $41, $60, $00 ;0x380
	dc.b	$01, $4A, $26, $49, $55, $8B, $32, $D3, $52, $41, $60, $00, $01, $3E, $42, $85, $74, $08, $E3, $4E, $E3, $55, $53, $47, $66, $00, $00, $06, $3C, $1E, $7E, $10 ;0x3A0
	dc.b	$51, $CA, $FF, $F0, $52, $45, $E3, $4D, $26, $49, $97, $C5, $32, $D3, $52, $41, $60, $00, $01, $18, $4A, $45, $67, $00, $00, $9A, $53, $45, $67, $00, $00, $CC ;0x3C0
	dc.b	$53, $45, $67, $00, $00, $54, $42, $85, $74, $02, $E3, $4E, $E3, $55, $53, $47, $66, $00, $00, $06, $3C, $1E, $7E, $10, $51, $CA, $FF, $F0, $38, $05, $52, $44 ;0x3E0
	dc.b	$42, $85, $74, $03, $E3, $4E, $E3, $55, $53, $47, $66, $00, $00, $06, $3C, $1E, $7E, $10, $51, $CA, $FF, $F0, $36, $05, $52, $43, $42, $85, $74, $08, $E3, $4E ;0x400
	dc.b	$E3, $55, $53, $47, $66, $00, $00, $06, $3C, $1E, $7E, $10, $51, $CA, $FF, $F0, $52, $45, $E3, $4D, $60, $00, $00, $5A, $42, $44, $42, $85, $74, $03, $E3, $4E ;0x420
	dc.b	$E3, $55, $53, $47, $66, $00, $00, $06, $3C, $1E, $7E, $10, $51, $CA, $FF, $F0, $36, $05, $52, $43, $42, $85, $74, $08, $E3, $4E, $E3, $55, $53, $47, $66, $00 ;0x440
	dc.b	$00, $06, $3C, $1E, $7E, $10, $51, $CA, $FF, $F0, $52, $45, $E3, $4D, $60, $00, $00, $20, $42, $44, $76, $01, $42, $85, $74, $08, $E3, $4E, $E3, $55, $53, $47 ;0x460
	dc.b	$66, $00, $00, $06, $3C, $1E, $7E, $10, $51, $CA, $FF, $F0, $52, $45, $E3, $4D, $26, $49, $96, $C5, $2F, $0B, $24, $03, $32, $DB, $52, $41, $51, $CA, $FF, $FA ;0x480
	dc.b	$26, $5F, $51, $CC, $FF, $F0, $60, $00, $00, $42, $42, $85, $74, $02, $E3, $4E, $E3, $55, $53, $47, $66, $00, $00, $06, $3C, $1E, $7E, $10, $51, $CA, $FF, $F0 ;0x4A0
	dc.b	$38, $05, $52, $44, $42, $85, $74, $08, $E3, $4E, $E3, $55, $53, $47, $66, $00, $00, $06, $3C, $1E, $7E, $10, $51, $CA, $FF, $F0, $52, $45, $E3, $4D, $26, $49 ;0x4C0
	dc.b	$97, $C5, $32, $D3, $52, $41, $51, $CC, $FF, $FA, $0C, $41, $05, $14, $65, $00, $FE, $1C, $34, $01, $04, $42, $02, $00, $BB, $FC, $00, $01, $00, $00, $64, $00 ;0x4E0
	dc.b	$00, $20, $48, $E7, $80, $40, $30, $02, $32, $4D, $4E, $B9, $00, $00, $21, $BC, $4C, $DF, $02, $01, $E3, $4A, $DA, $C2, $24, $48, $D4, $C2, $60, $00, $00, $0C ;0x500
	dc.b	$53, $42, $24, $48, $3A, $DA, $51, $CA, $FF, $FC, $34, $3C, $01, $FF, $22, $48, $32, $DA, $51, $CA, $FF, $FC, $32, $3C, $02, $00, $60, $00, $FD, $D0, $4A, $41 ;0x520
	dc.b	$67, $20, $BB, $FC, $00, $01, $00, $00, $64, $00, $00, $10, $30, $01, $32, $4D, $4E, $B9, $00, $00, $21, $BC, $60, $00, $00, $0A, $53, $41, $3A, $D8, $51, $C9 ;0x540
	dc.b	$FF, $FC, $4E, $43, $20, $5F, $61, $00, $15, $74, $4C, $DF, $7F, $FF, $4E, $75 ;0x560
	LEA	$00FF011C, A0
	MOVE.w	#1, (A0)+
	CLR.l	(A0)+
	MOVE.w	#1, (A0)+
	MOVE.w	#$009D, D0
loc_00002640:
	CLR.l	(A0)+
	DBF	D0, loc_00002640
	MOVE.w	#1, $00FF2854
	CLR.w	$00FF2856
	RTS
loc_00002656:
	TST.w	(A0)
	BNE.b	loc_0000265C
loc_0000265A:
	RTS	;Predicted (Code-scan)
loc_0000265C:
	CMPI.w	#$0200, D0
	BCC.b	loc_0000265A
	CMPI.w	#$0200, D1
	BCC.b	loc_0000265A
	MOVEM.l	A2/A1/A0/D7/D6/D5/D4/D3/D2/D1/D0, -(A7)
	LEA	$00FF011C, A1
	MOVEA.l	A1, A2
	MOVE.w	$00FF2854, D6
	MOVE.w	D6, D5
	LSL.w	#3, D6
	ANDI.l	#$000003FF, D6
	ADDA.l	D6, A1
	MOVE.w	$00FF2856, D6
	LSL.w	#3, D6
	ANDI.l	#$000003FF, D6
	ADDA.l	D6, A2
	ADDQ.l	#2, A2
	MOVE.w	(A2), D6
	ANDI.w	#$0F00, D6
	OR.w	D5, D6
	MOVE.w	D6, (A2)
	CLR.w	D7
	BSR.b	loc_00002710
	MOVE.w	D5, $00FF2854
	SUBQ.w	#1, D5
	MOVE.w	D5, $00FF2856
	MOVEM.l	(A7)+, D0/D1/D2/D3/D4/D5/D6/D7/A0/A1/A2
	RTS
	dc.b	$4A, $50, $66, $02, $4E, $75, $0C, $40, $02, $00, $64, $F8, $0C, $41, $02, $00, $64, $F2, $48, $E7, $FF, $E0, $43, $F9, $00, $FF, $01, $1C, $24, $49, $3C, $39 ;0x0 (0x000026BA-0x00002710, Entry count: 0x56) [Unknown data]
	dc.b	$00, $FF, $28, $54, $3A, $06, $E7, $4E, $02, $86, $00, $00, $03, $FF, $D3, $C6, $3C, $39, $00, $FF, $01, $1E, $3E, $06, $02, $47, $00, $7F, $02, $46, $0F, $00 ;0x20
	dc.b	$8C, $45, $33, $C6, $00, $FF, $01, $1E, $61, $0C, $33, $C5, $00, $FF, $28, $54, $4C, $DF, $07, $FF, $4E, $75 ;0x40
loc_00002710:
	MOVE.w	(A0)+, D4
	SUBQ.w	#1, D4
	LSR.w	#5, D2
loc_00002716:
	MOVE.w	(A0)+, D6
	ADD.w	D1, D6
	ADDQ.w	#1, D5
	MOVE.w	D6, (A1)+
	MOVE.w	(A0)+, D6
	TST.w	D4
	BEQ.b	loc_00002728
	OR.w	D5, D6	;Predicted (Code-scan)
	BRA.b	loc_0000272A	;Predicted (Code-scan)
loc_00002728:
	OR.w	D7, D6
loc_0000272A:
	MOVE.w	D6, (A1)+
	MOVE.w	(A0)+, D6
	ADD.w	D2, D6
	OR.w	D3, D6
	MOVE.w	D6, (A1)+
	MOVE.w	(A0)+, D6
	ADD.w	D0, D6
	TST.w	D6
	BNE.b	loc_0000273E
	ADDQ.w	#1, D6	;Predicted (Code-scan)
loc_0000273E:
	MOVE.w	D6, (A1)+
	DBF	D4, loc_00002716
	RTS
loc_00002746:
	MOVE.l	D0, -(A7)
	LEA	$00FF285E, A2
	LEA	$00FF289E, A3
	CLR.l	D0
	MOVE.w	A0, D0
	LSL.l	#1, D0
	ADDA.l	D0, A2
	LSL.l	#1, D0
	ADDA.l	D0, A3
	LSL.l	#2, D0
	ADDA.l	D0, A3
	MOVE.l	(A7)+, D0
	RTS
	dc.b	$48, $E7, $F8, $70, $45, $F9, $00, $FF, $28, $5E, $47, $F9, $00, $FF, $28, $9E, $42, $43, $0C, $52, $FF, $FF, $67, $1A, $52, $43, $54, $8A, $D7, $FC, $00, $00 ;0x0 (0x00002768-0x000027DE, Entry count: 0x76) [Unknown data]
	dc.b	$00, $14, $0C, $43, $00, $20, $66, $EA, $30, $7C, $FF, $FF, $4C, $DF, $0E, $0F, $4E, $75, $26, $C8, $36, $FC, $00, $02, $36, $C9, $48, $C0, $ED, $88, $26, $C0 ;0x20
	dc.b	$E1, $5A, $EB, $5A, $36, $C2, $42, $5B, $48, $C1, $ED, $89, $26, $C1, $34, $90, $30, $43, $4C, $DF, $0E, $1F, $4E, $75, $48, $E7, $00, $30, $61, $80, $34, $BC ;0x40
	dc.b	$FF, $FF, $4C, $DF, $0C, $00, $4E, $75, $33, $C0, $00, $FF, $28, $5A, $33, $C1, $00, $FF, $28, $5C, $4E, $75 ;0x60
	MOVEM.l	A3/A2/D1/D0, -(A7)
	BSR.w	loc_00002746
	EXT.l	D0
	ADD.l	D0, $8(A3)
	EXT.l	D1
	ADD.l	D1, $10(A3)
	MOVEM.l	(A7)+, D0/D1/A2/A3
	RTS
	dc.b	$48, $E7, $C0, $30, $61, $00, $FF, $48, $48, $C0, $ED, $88, $27, $40, $00, $08, $48, $C1, $ED, $89, $27, $41, $00, $10, $4C, $DF, $0C, $03, $4E, $75, $48, $E7 ;0x0 (0x000027F8-0x000028B6, Entry count: 0xBE) [Unknown data]
	dc.b	$40, $30, $61, $00, $FF, $2A, $32, $2B, $00, $0E, $08, $C1, $00, $0D, $08, $C1, $00, $0C, $02, $41, $FF, $00, $4A, $40, $66, $08, $50, $41, $08, $81, $00, $0B ;0x20
	dc.b	$60, $06, $58, $41, $08, $C1, $00, $0B, $37, $41, $00, $0E, $4C, $DF, $0C, $02, $4E, $75, $48, $E7, $80, $30, $61, $00, $FE, $F6, $30, $2B, $00, $0E, $08, $80 ;0x40
	dc.b	$00, $0D, $08, $80, $00, $0C, $37, $40, $00, $0E, $08, $AB, $00, $04, $00, $0E, $4C, $DF, $0C, $01, $4E, $75, $00, $00, $28, $80, $00, $00, $28, $76, $08, $F9 ;0x60
	dc.b	$00, $01, $00, $FF, $00, $18, $4E, $75, $41, $F9, $00, $FF, $28, $5E, $70, $1F, $30, $FC, $FF, $FF, $51, $C8, $FF, $FA, $30, $3C, $01, $3F, $41, $F9, $00, $FF ;0x80
	dc.b	$28, $9E, $42, $58, $51, $C8, $FF, $FC, $33, $FC, $00, $80, $00, $FF, $28, $5A, $33, $FC, $00, $80, $00, $FF, $28, $5C, $42, $79, $00, $FF, $28, $58 ;0xA0
loc_000028B6:
	TRAP	#5
	ORI.b	#$1F, D1	;Predicted (Code-scan)
loc_000028BC:
	CLR.l	D3
	CLR.w	D2
	LEA	$00FF289C, A4
	LEA	$00FF2B0A, A5
	MOVEA.l	#$FFFFFFFF, A2
loc_000028D2:
	CMPI.w	#$FFFF, (A4)
	BEQ.b	loc_00002906
	MOVE.w	$E(A5), D0
	BTST.l	#$0F, D0
	BNE.b	loc_00002906
	BTST.l	#$0E, D0
	BNE.b	loc_00002906
	MOVE.w	$C(A5), D0
	ANDI.w	#$1FFF, D0
	CMP.w	D0, D2
	BCS.b	loc_000028FC
	BNE.b	loc_00002906
	CMP.l	$10(A5), D3
	BGT.b	loc_00002906
loc_000028FC:
	MOVEA.l	A4, A2
	MOVEA.l	A5, A3
	MOVE.l	$10(A5), D3
	MOVE.w	D0, D2
loc_00002906:
	SUBQ.l	#2, A4
	SUBA.l	#$00000014, A5
	DBF	D7, loc_000028D2
	CMPA.l	#$FFFFFFFF, A2
	BNE.b	loc_0000293E
	LEA	$00FF289E, A5
	MOVEQ	#$0000001F, D0
loc_00002922:
	BCLR.b	#6, $E(A5)
	ADDA.l	#$00000014, A5
	DBF	D0, loc_00002922
	BSET.b	#1, $00FF0018
	BRA.w	loc_000028B6
loc_0000293E:
	MOVE.w	$E(A3), D0
	BTST.l	#$0D, D0
	BEQ.b	loc_00002968
	TST.b	D0	;Predicted (Code-scan)
	BNE.b	loc_0000295C	;Predicted (Code-scan)
	MOVE.b	#4, D0	;Predicted (Code-scan)
	BCHG.l	#$0C, D0	;Predicted (Code-scan)
	BTST.l	#$0B, D0	;Predicted (Code-scan)
	BEQ.b	loc_0000295C	;Predicted (Code-scan)
	ADDQ.w	#4, D0	;Predicted (Code-scan)
loc_0000295C:
	SUBQ.w	#1, D0	;Predicted (Code-scan)
	MOVE.w	D0, $E(A3)	;Predicted (Code-scan)
	BTST.l	#$0C, D0	;Predicted (Code-scan)
	BNE.b	loc_0000296A	;Predicted (Code-scan)
loc_00002968:
	BSR.b	loc_00002974
loc_0000296A:
	BSET.b	#6, $E(A3)
	BRA.w	loc_000028BC-2
loc_00002974:
	TST.w	$00FF2858
	BNE.b	loc_000029AC
	SUBQ.w	#1, (A2)
	BNE.b	loc_000029AC
	MOVEA.l	A3, A4
	MOVEA.l	(A4)+, A0
	ADDQ.w	#4, (A4)
	CLR.l	D0
	MOVE.w	(A4), D0
	ADDA.l	D0, A0
	MOVE.w	(A0)+, D1
	TST.w	D1
	BNE.b	loc_0000299A
	MOVE.w	#$FFFF, (A2)	;Predicted (Code-scan)
	BRA.w	loc_000029E6	;Predicted (Code-scan)
loc_0000299A:
	CMPI.w	#$FFFF, D1
	BNE.b	loc_000029A8
	MOVEA.l	A3, A4
	MOVEA.l	(A4)+, A0
	CLR.w	(A4)
	MOVE.w	(A0)+, D1
loc_000029A8:
	MOVE.w	D1, (A2)
	ADDQ.w	#2, (A4)
loc_000029AC:
	MOVEA.l	A3, A4
	MOVEA.l	(A4)+, A1
	CLR.l	D0
	MOVE.w	(A4)+, D0
	ADDA.l	D0, A1
	TST.l	(A1)
	BEQ.b	loc_000029E6
	MOVEA.l	(A1), A0
	MOVE.w	(A4)+, D2
	MOVE.l	(A4)+, D0
	LSR.l	#6, D0
	ADDI.w	#$0080, D0
	SUB.w	$00FF285A, D0
	MOVE.w	(A4)+, D3
	ANDI.w	#$E000, D3
	ADDQ.l	#2, A4
	MOVE.l	(A4)+, D1
	LSR.l	#6, D1
	ADDI.w	#$0080, D1
	SUB.w	$00FF285C, D1
	BSR.w	loc_00002656
loc_000029E6:
	RTS
	dc.b	$48, $E7, $E0, $30, $45, $F9, $00, $FF, $28, $5E, $47, $F9, $00, $FF, $28, $9E, $48, $C0, $48, $C1, $74, $1F, $0C, $5A, $FF, $FF, $67, $08, $D1, $AB, $00, $08 ;0x0 (0x000029E8-0x00002A1C, Entry count: 0x34) [Unknown data]
	dc.b	$D3, $AB, $00, $10, $D7, $FC, $00, $00, $00, $14, $51, $CA, $FF, $EA, $4C, $DF, $0C, $07, $4E, $75 ;0x20
	MOVEM.l	A3/A2/A1/A0/D4/D3, -(A7)
	TST.w	D2
	BEQ.b	loc_00002A4E
	BSR.w	loc_00002746
	MOVE.w	D0, D3
	MOVE.w	D1, D4
	EXT.l	D3
	EXT.l	D4
	LSL.l	#6, D3
	LSL.l	#6, D4
	SUB.l	$8(A3), D3
	SUB.l	$10(A3), D4
	DIVS.w	D2, D3
	DIVS.w	D2, D4
	EXT.l	D3
	EXT.l	D4
	ADD.l	D3, $8(A3)
	ADD.l	D4, $10(A3)
	SUBQ.w	#1, D2
loc_00002A4E:
	MOVEM.l	(A7)+, D3/D4/A0/A1/A2/A3
	RTS
	MOVEM.l	A3/A2, -(A7)
	BSR.w	loc_00002746
	MOVE.l	A1, (A3)+
	MOVE.w	#2, (A3)+
	MOVE.w	D0, (A3)+
	MOVE.w	(A1), (A2)
	MOVEM.l	(A7)+, A2/A3
	RTS
	MOVEM.l	A3/A2, -(A7)
	BSR.w	loc_00002746
	ROL.w	#8, D0
	ROL.w	#5, D0
	MOVE.w	D0, $C(A3)
	MOVEM.l	(A7)+, A2/A3
	RTS
	dc.b	$48, $E7, $80, $30, $61, $00, $FC, $BE, $30, $2B, $00, $0E, $08, $C0, $00, $0F, $37, $40, $00, $0E, $4C, $DF, $0C, $01, $4E, $75, $48, $E7, $80, $30, $61, $00 ;0x0 (0x00002A82-0x00002B78, Entry count: 0xF6) [Unknown data]
	dc.b	$FC, $A4, $30, $2B, $00, $0E, $08, $80, $00, $0F, $37, $40, $00, $0E, $4C, $DF, $0C, $01, $4E, $75, $48, $E7, $00, $30, $61, $00, $FC, $8A, $20, $53, $32, $6B ;0x20
	dc.b	$00, $06, $4C, $DF, $0C, $00, $4E, $75, $48, $E7, $60, $30, $45, $F9, $00, $FF, $28, $5E, $47, $F9, $00, $FF, $28, $9E, $74, $1F, $0C, $5A, $FF, $FF, $67, $0C ;0x40
	dc.b	$32, $2B, $00, $0E, $08, $C1, $00, $0F, $37, $41, $00, $0E, $D7, $FC, $00, $00, $00, $14, $51, $CA, $FF, $E6, $4C, $DF, $0C, $06, $4E, $75, $48, $E7, $60, $30 ;0x60
	dc.b	$45, $F9, $00, $FF, $28, $5E, $47, $F9, $00, $FF, $28, $9E, $74, $1F, $0C, $5A, $FF, $FF, $67, $0C, $32, $2B, $00, $0E, $08, $81, $00, $0F, $37, $41, $00, $0E ;0x80
	dc.b	$D7, $FC, $00, $00, $00, $14, $51, $CA, $FF, $E6, $4C, $DF, $0C, $06, $4E, $75, $00, $00, $2B, $42, $00, $00, $2B, $3A, $42, $79, $00, $FF, $01, $1A, $4E, $75 ;0xA0
	dc.b	$70, $03, $41, $F9, $00, $FF, $2B, $20, $30, $FC, $FF, $FF, $42, $58, $42, $98, $51, $C8, $FF, $F6, $70, $3F, $4D, $F9, $00, $FF, $00, $1A, $4B, $F9, $00, $FF ;0xC0
	dc.b	$00, $9A, $3A, $DE, $51, $C8, $FF, $FC, $33, $FC, $00, $01, $00, $FF, $01, $1A, $42, $79, $00, $FF, $2B, $1E ;0xE0
loc_00002B78:
	TRAP	#5
	ORI.b	#$B9, D1	;Predicted (Code-scan)
	ORI.b	#$FF, D0	;Predicted (Code-scan)
	ORI.b	#8, (A0)+	;Predicted (Code-scan)
	MOVE.w	#1, $00FF2B1E	;Predicted (Code-scan)
loc_00002B8E:
	LEA	$00FF001A, A6
	LEA	$00FF009A, A5
	MOVEQ	#$0000003F, D0
loc_00002B9C:
	MOVE.w	(A6)+, (A5)+
	DBF	D0, loc_00002B9C
	LEA	$00FF001A, A6
	LEA	$00FF009A, A5
	LEA	$00FF2B20, A0
	MOVEQ	#3, D7
loc_00002BB6:
	CMPI.b	#$FF, (A0)
	BEQ.w	loc_00002C5C
	CLR.w	D0	;Predicted (Code-scan)
	MOVE.b	(A0), D0	;Predicted (Code-scan)
	MOVE.w	$4(A0), D1	;Predicted (Code-scan)
loc_00002BC6:
	MOVE.w	(A6,D0.w), D2	;Predicted (Code-scan)
	MOVE.w	D2, D4	;Predicted (Code-scan)
	ANDI.w	#$000F, D4	;Predicted (Code-scan)
	MULU.w	D1, D4	;Predicted (Code-scan)
	LSR.w	#8, D4	;Predicted (Code-scan)
	LSR.w	#4, D2	;Predicted (Code-scan)
	MOVE.w	D2, D3	;Predicted (Code-scan)
	ANDI.w	#$000F, D3	;Predicted (Code-scan)
	MULU.w	D1, D3	;Predicted (Code-scan)
	LSR.w	#4, D3	;Predicted (Code-scan)
	ANDI.w	#$00F0, D3	;Predicted (Code-scan)
	OR.w	D3, D4	;Predicted (Code-scan)
	LSR.w	#4, D2	;Predicted (Code-scan)
	MULU.w	D1, D2	;Predicted (Code-scan)
	ANDI.w	#$0F00, D2	;Predicted (Code-scan)
	OR.w	D2, D4	;Predicted (Code-scan)
	MOVE.w	D4, (A5,D0.w)	;Predicted (Code-scan)
	CMP.b	$1(A0), D0	;Predicted (Code-scan)
	BEQ.w	loc_00002C00	;Predicted (Code-scan)
	ADDQ.w	#2, D0	;Predicted (Code-scan)
	BRA.b	loc_00002BC6	;Predicted (Code-scan)
loc_00002C00:
	TST.b	$6(A0)	;Predicted (Code-scan)
	BEQ.b	loc_00002C54	;Predicted (Code-scan)
	BPL.b	loc_00002C34	;Predicted (Code-scan)
	SUB.w	$2(A0), D1	;Predicted (Code-scan)
	BPL.b	loc_00002C2E	;Predicted (Code-scan)
	CLR.w	D1	;Predicted (Code-scan)
	MOVE.b	(A0), D1	;Predicted (Code-scan)
	CLR.w	D2	;Predicted (Code-scan)
	MOVE.b	$1(A0), D2	;Predicted (Code-scan)
loc_00002C18:
	CLR.w	(A6,D1.w)	;Predicted (Code-scan)
	CMP.w	D2, D1	;Predicted (Code-scan)
	BEQ.b	loc_00002C24	;Predicted (Code-scan)
	ADDQ.w	#2, D1	;Predicted (Code-scan)
	BRA.b	loc_00002C18	;Predicted (Code-scan)
loc_00002C24:
	BSR.w	loc_00002E1C	;Predicted (Code-scan)
	MOVE.w	#$FFFF, (A0)	;Predicted (Code-scan)
	CLR.w	D1	;Predicted (Code-scan)
loc_00002C2E:
	MOVE.w	D1, $4(A0)	;Predicted (Code-scan)
	BRA.b	loc_00002C54	;Predicted (Code-scan)
loc_00002C34:
	CMPI.w	#$0100, D1	;Predicted (Code-scan)
	BCC.b	loc_00002C4A	;Predicted (Code-scan)
	ADD.w	$2(A0), D1	;Predicted (Code-scan)
	CMPI.w	#$0100, D1	;Predicted (Code-scan)
	BCS.b	loc_00002C50	;Predicted (Code-scan)
	MOVE.w	#$0100, D1	;Predicted (Code-scan)
	BRA.b	loc_00002C50	;Predicted (Code-scan)
loc_00002C4A:
	MOVE.w	#$FFFF, (A0)	;Predicted (Code-scan)
	CLR.w	D1	;Predicted (Code-scan)
loc_00002C50:
	MOVE.w	D1, $4(A0)	;Predicted (Code-scan)
loc_00002C54:
	MOVE.w	#1, $00FF2B1E	;Predicted (Code-scan)
loc_00002C5C:
	ADDQ.l	#8, A0
	DBF	D7, loc_00002BB6
	TST.w	$00FF2B1E
	BEQ.w	loc_00002B78
	BSET.b	#0, $00FF0018	;Predicted (Code-scan)
	CLR.w	$00FF2B1E	;Predicted (Code-scan)
	BRA.w	loc_00002B78	;Predicted (Code-scan)
	dc.b	$48, $E7, $10, $80, $61, $40, $4A, $43, $6B, $10, $E3, $48, $10, $C0, $E3, $49, $10, $C1, $30, $C2, $42, $58, $10, $BC, $00, $01, $30, $03, $4C, $DF, $01, $08 ;0x0 (0x00002C7E-0x00002D62, Entry count: 0xE4) [Unknown data]
	dc.b	$4E, $75, $48, $E7, $10, $80, $61, $1E, $4A, $43, $6B, $12, $E3, $48, $10, $C0, $E3, $49, $10, $C1, $30, $C2, $30, $FC, $01, $00, $10, $BC, $00, $FF, $30, $03 ;0x20
	dc.b	$4C, $DF, $01, $08, $4E, $75, $41, $F9, $00, $FF, $2B, $38, $76, $03, $0C, $10, $00, $FF, $67, $06, $51, $48, $51, $CB, $FF, $F6, $4E, $75, $48, $E7, $40, $86 ;0x40
	dc.b	$41, $F9, $00, $FF, $2B, $20, $E7, $48, $D0, $C0, $4D, $F9, $00, $FF, $00, $1A, $4B, $F9, $00, $FF, $00, $9A, $42, $40, $10, $10, $42, $41, $12, $28, $00, $01 ;0x60
	dc.b	$3D, $B5, $00, $00, $00, $00, $B2, $40, $67, $04, $54, $40, $60, $F2, $30, $BC, $FF, $FF, $4C, $DF, $61, $02, $4E, $75, $48, $E7, $40, $86, $41, $F9, $00, $FF ;0x80
	dc.b	$2B, $20, $E7, $48, $D0, $C0, $30, $BC, $FF, $FF, $4C, $DF, $61, $02, $4E, $75, $48, $E7, $80, $80, $41, $F9, $00, $FF, $2B, $20, $70, $03, $30, $BC, $FF, $FF ;0xA0
	dc.b	$50, $88, $51, $C8, $FF, $F8, $4C, $DF, $01, $01, $4E, $75, $00, $00, $2D, $54, $00, $00, $2D, $52, $4E, $75, $41, $F9, $00, $FF, $2B, $40, $70, $0F, $42, $98 ;0xC0
	dc.b	$51, $C8, $FF, $FC ;0xE0
loc_00002D62:
	TRAP	#5
	ORI.b	#$F9, D1	;Predicted (Code-scan)
	dc.b	$00, $FF, $2B, $40 ;0x0 (0x00002D68-0x00002D6C, Entry count: 0x4) [Unknown data]
	MOVEQ	#3, D7
loc_00002D6E:
	TST.w	(A0)
	BEQ.w	loc_00002DBE
	SUBQ.w	#1, $2(A0)	;Predicted (Code-scan)
	BNE.w	loc_00002DBE	;Predicted (Code-scan)
	MOVEA.l	$C(A0), A1	;Predicted (Code-scan)
	MOVE.w	(A1)+, D0	;Predicted (Code-scan)
	BNE.b	loc_00002D90	;Predicted (Code-scan)
	MOVEA.l	$8(A0), A1	;Predicted (Code-scan)
	MOVE.w	(A1)+, D0	;Predicted (Code-scan)
	LSL.w	#1, D0	;Predicted (Code-scan)
	ADDA.w	D0, A1	;Predicted (Code-scan)
	MOVE.w	(A1)+, D0	;Predicted (Code-scan)
loc_00002D90:
	MOVE.w	D0, $2(A0)	;Predicted (Code-scan)
	MOVEA.l	$8(A0), A2	;Predicted (Code-scan)
	MOVE.w	(A2)+, D0	;Predicted (Code-scan)
	SUBQ.w	#1, D0	;Predicted (Code-scan)
loc_00002D9C:
	LEA	$00FF001A, A3	;Predicted (Code-scan)
	ADDA.w	$4(A0), A3	;Predicted (Code-scan)
	MOVE.w	(A2)+, D1	;Predicted (Code-scan)
	LSL.w	#1, D1	;Predicted (Code-scan)
	ADDA.w	D1, A3	;Predicted (Code-scan)
	MOVE.w	(A1)+, (A3)	;Predicted (Code-scan)
	DBF	D0, loc_00002D9C	;Predicted (Code-scan)
	MOVE.l	A1, $C(A0)	;Predicted (Code-scan)
	BSET.b	#0, $00FF0018	;Predicted (Code-scan)
loc_00002DBE:
	ADDA.w	#$0010, A0
	DBF	D7, loc_00002D6E
	BRA.b	loc_00002D62
	dc.b	$48, $E7, $40, $40, $32, $00, $43, $F9, $00, $FF, $2B, $70, $70, $03, $4A, $51, $67, $0E, $92, $FC, $00, $10, $51, $C8, $FF, $F6, $4C, $DF, $02, $02, $4E, $75 ;0x0 (0x00002DC8-0x00002E1C, Entry count: 0x54) [Unknown data]
	dc.b	$EB, $49, $33, $41, $00, $04, $23, $48, $00, $08, $32, $18, $32, $81, $E3, $49, $D0, $C1, $23, $48, $00, $0C, $33, $7C, $00, $01, $00, $02, $4C, $DF, $02, $02 ;0x20
	dc.b	$4E, $75, $2F, $08, $41, $F9, $00, $FF, $2B, $40, $E9, $48, $D0, $C0, $42, $50, $20, $5F, $4E, $75 ;0x40
loc_00002E1C:
	MOVEM.l	A0/D0, -(A7)	;Predicted (Code-scan)
	LEA	$00FF2B40, A0	;Predicted (Code-scan)
	MOVEQ	#$0000000F, D0	;Predicted (Code-scan)
loc_00002E28:
	CLR.l	(A0)+	;Predicted (Code-scan)
	DBF	D0, loc_00002E28	;Predicted (Code-scan)
	MOVEM.l	(A7)+, D0/A0	;Predicted (Code-scan)
	RTS	;Predicted (Code-scan)
	dc.b	$00, $00, $2E, $42, $00, $00, $2E, $3C, $61, $00, $F0, $22, $4E, $75, $4D, $F9, $00, $06, $05, $80, $2A, $7C, $00, $00, $B6, $00, $61, $00, $F5, $34, $61, $00 ;0x0 (0x00002E34-0x00002E74, Entry count: 0x40) [Unknown data]
	dc.b	$01, $76, $41, $F9, $00, $FF, $30, $36, $70, $07, $42, $50, $D0, $FC, $00, $0C, $51, $C8, $FF, $F8, $41, $F9, $00, $FF, $2B, $80, $23, $C8, $00, $FF, $30, $30 ;0x20
loc_00002E74:
	TRAP	#5
	ORI.b	#$F9, D1	;Predicted (Code-scan)
	dc.b	$00, $FF, $30, $36 ;0x0 (0x00002E7A-0x00002E7E, Entry count: 0x4) [Unknown data]
	MOVEQ	#7, D7
loc_00002E80:
	TST.w	(A6)
	BEQ.w	loc_00002F66
	MOVE.b	$6(A6), D0
	BEQ.w	loc_00002F66
	SUBQ.b	#1, D0
	BEQ.w	loc_00002EE0
	SUBQ.b	#1, D0
	BEQ.w	loc_00002F16
	BSR.w	loc_00002F72
	MOVE.b	$7(A6), D4
	BTST.l	#7, D4
	BEQ.b	loc_00002EB6
	MOVEA.l	$8(A6), A0
	BSR.w	loc_00003146
	CLR.w	(A6)
	BRA.w	loc_00002F66
loc_00002EB6:
	BSR.w	loc_00003168	;Predicted (Code-scan)
	SUBQ.w	#1, D2	;Predicted (Code-scan)
	SUBQ.w	#1, D3	;Predicted (Code-scan)
	CLR.w	D1	;Predicted (Code-scan)
loc_00002EC0:
	MOVEM.l	D2/D0, -(A7)	;Predicted (Code-scan)
loc_00002EC4:
	BSR.w	*+$EED0	;Predicted (Code-scan)
	ADDQ.w	#2, D0	;Predicted (Code-scan)
	DBF	D2, loc_00002EC4	;Predicted (Code-scan)
	MOVEM.l	(A7)+, D0/D2	;Predicted (Code-scan)
	ADDI.w	#$0080, D0	;Predicted (Code-scan)
	DBF	D3, loc_00002EC0	;Predicted (Code-scan)
	CLR.w	(A6)	;Predicted (Code-scan)
	BRA.w	loc_00002F66	;Predicted (Code-scan)
loc_00002EE0:
	BSR.w	loc_00002F72
	MOVE.b	$7(A6), D4
	BTST.l	#7, D4
	BEQ.b	loc_00002EF6
	BSR.w	loc_00003116
	MOVE.l	A0, $8(A6)
loc_00002EF6:
	BTST.l	#6, D4
	BEQ.b	loc_00002F0C
	ANDI.w	#3, D4
	BSR.w	loc_00002FEC
	CLR.b	$6(A6)
	BRA.w	loc_00002F66
loc_00002F0C:
	MOVE.b	#2, $6(A6)	;Predicted (Code-scan)
	CLR.w	$4(A6)	;Predicted (Code-scan)
loc_00002F16:
	BSR.w	loc_00002F72	;Predicted (Code-scan)
	CLR.w	D5	;Predicted (Code-scan)
	CLR.w	D6	;Predicted (Code-scan)
	MOVE.b	$4(A6), D5	;Predicted (Code-scan)
	MOVE.b	$5(A6), D6	;Predicted (Code-scan)
	ADDQ.w	#2, D5	;Predicted (Code-scan)
	CMP.w	D5, D2	;Predicted (Code-scan)
	BCC.b	loc_00002F2E	;Predicted (Code-scan)
	MOVE.w	D2, D5	;Predicted (Code-scan)
loc_00002F2E:
	ADDQ.w	#2, D6	;Predicted (Code-scan)
	CMP.w	D6, D3	;Predicted (Code-scan)
	BCC.b	loc_00002F36	;Predicted (Code-scan)
	MOVE.w	D3, D6	;Predicted (Code-scan)
loc_00002F36:
	MOVE.b	D5, $4(A6)	;Predicted (Code-scan)
	MOVE.b	D6, $5(A6)	;Predicted (Code-scan)
	CMP.w	D2, D5	;Predicted (Code-scan)
	BNE.b	loc_00002F4A	;Predicted (Code-scan)
	CMP.w	D3, D6	;Predicted (Code-scan)
	BNE.b	loc_00002F4A	;Predicted (Code-scan)
	CLR.b	$6(A6)	;Predicted (Code-scan)
loc_00002F4A:
	SUB.w	D5, D2	;Predicted (Code-scan)
	LSR.w	#1, D2	;Predicted (Code-scan)
	ADD.w	D2, D0	;Predicted (Code-scan)
	SUB.w	D6, D3	;Predicted (Code-scan)
	LSR.w	#1, D3	;Predicted (Code-scan)
	ADD.w	D3, D1	;Predicted (Code-scan)
	MOVE.w	D5, D2	;Predicted (Code-scan)
	MOVE.w	D6, D3	;Predicted (Code-scan)
	MOVE.b	$7(A6), D4	;Predicted (Code-scan)
	ANDI.w	#3, D4	;Predicted (Code-scan)
	BSR.w	loc_00002FEC	;Predicted (Code-scan)
loc_00002F66:
	ADDA.w	#$000C, A6
	DBF	D7, loc_00002E80
	BRA.w	loc_00002E74
loc_00002F72:
	CLR.w	D0
	CLR.w	D1
	CLR.w	D2
	CLR.w	D3
	MOVE.b	$2(A6), D0
	MOVE.b	$3(A6), D1
	MOVE.b	(A6), D2
	MOVE.b	$1(A6), D3
	RTS
	dc.b	$0E, $E0, $00, $2C, $00, $0E, $0E, $EE, $04, $00, $0E, $E0, $00, $2C, $0E, $EE, $04, $00, $00, $EE, $0E, $E0, $00, $2C, $00, $EE, $04, $00, $0E, $EE, $48, $E7 ;0x0 (0x00002F8A-0x00002FEC, Entry count: 0x62) [Unknown data]
	dc.b	$C0, $80, $41, $FA, $FF, $DC, $70, $05, $72, $56, $61, $00, $EF, $A2, $41, $FA, $FF, $E4, $70, $05, $72, $76, $61, $00, $EF, $96, $4C, $DF, $01, $03, $4E, $75 ;0x20
	dc.b	$48, $E7, $C0, $80, $41, $FA, $FF, $C0, $70, $02, $72, $5C, $61, $00, $EF, $80, $41, $FA, $FF, $C8, $70, $02, $72, $7C, $61, $00, $EF, $74, $4C, $DF, $01, $03 ;0x40
	dc.b	$4E, $75 ;0x60
loc_00002FEC:
	MOVEM.l	D5/D4/D3/D2/D1/D0, -(A7)
	BSR.w	loc_00003168
	LSL.w	#8, D4
	LSL.w	#5, D4
	SUBQ.w	#3, D2
	SUBQ.w	#3, D3
	MOVEM.w	D2/D1/D0, -(A7)
	CLR.w	D5
	BSR.w	loc_0000308A
	ADDQ.w	#2, D0
	TST.w	D2
	BMI.b	loc_0000301C
	MOVE.w	#$85B2, D1
	OR.w	D4, D1
loc_00003012:
	BSR.w	*+$ED82
	ADDQ.w	#2, D0
	DBF	D2, loc_00003012
loc_0000301C:
	MOVEQ	#1, D5
	BSR.b	loc_0000308A
	MOVEM.w	(A7)+, D0/D1/D2
	ADDI.w	#$0080, D0
	TST.w	D3
	BMI.b	loc_00003066
loc_0000302C:
	MOVEM.w	D2/D0, -(A7)
	MOVE.w	#$85B3, D1
	OR.w	D4, D1
	BSR.w	*+$ED5E
	ADDQ.w	#2, D0
	TST.w	D2
	BMI.b	loc_00003050
	MOVE.w	#$85B0, D1
	OR.w	D4, D1
loc_00003046:
	BSR.w	*+$ED4E
	ADDQ.w	#2, D0
	DBF	D2, loc_00003046
loc_00003050:
	MOVE.w	#$8DB3, D1
	OR.w	D4, D1
	BSR.w	*+$ED3E
	MOVEM.w	(A7)+, D0/D2
	ADDI.w	#$0080, D0
	DBF	D3, loc_0000302C
loc_00003066:
	MOVEQ	#2, D5
	BSR.b	loc_0000308A
	ADDQ.w	#2, D0
	TST.w	D2
	BMI.b	loc_00003080
	MOVE.w	#$95B2, D1
	OR.w	D4, D1
loc_00003076:
	BSR.w	*+$ED1E
	ADDQ.w	#2, D0
	DBF	D2, loc_00003076
loc_00003080:
	MOVEQ	#3, D5
	BSR.b	loc_0000308A
	MOVEM.l	(A7)+, D0/D1/D2/D3/D4/D5
	RTS
loc_0000308A:
	MOVEM.l	A0/D6/D5/D4/D3/D2/D1/D0, -(A7)
	BSR.w	*+$ED34
	TST.w	D1
	BEQ.b	loc_000030CA
	LEA	loc_000030E6(PC), A0
	MOVE.w	D5, D3
	LSL.w	#2, D3
	MOVE.w	D1, D6
	ANDI.w	#$1800, D6
	LSR.w	#8, D6
	LSR.w	#3, D6
	ADD.w	D6, D3
	CLR.w	D6
	MOVE.b	(A0,D3.w), D6
	LSL.w	#3, D6
	ANDI.w	#$07FF, D1
	SUBI.w	#$05B0, D1
	BMI.b	loc_000030CA
	CMPI.w	#6, D1
	BCC.b	loc_000030CA
	ADD.w	D1, D6
	MOVE.b	$10(A0,D6.w), D3
	BRA.b	loc_000030CE
loc_000030CA:
	MOVE.b	#1, D3
loc_000030CE:
	MOVE.w	D5, D1
	LSL.w	#8, D1
	LSL.w	#3, D1
	ADDI.w	#$85B0, D1
	ADD.b	D3, D1
	OR.w	D4, D1
	BSR.w	*+$ECB8
	MOVEM.l	(A7)+, D0/D1/D2/D3/D4/D5/D6/A0
	RTS
loc_000030E6:
	dc.b	$00
	dc.b	$01, $02, $03, $01 ;0x0 (0x000030E7-0x000030EB, Entry count: 0x4) [Unknown data]
	dc.b	$00
	dc.b	$03, $02, $02, $03 ;0x0 (0x000030EC-0x000030F0, Entry count: 0x4) [Unknown data]
	dc.b	$00
	dc.b	$01, $03, $02, $01 ;0x0 (0x000030F1-0x000030F5, Entry count: 0x4) [Unknown data]
	dc.b	$00
	dc.b	$04 ;0x0 (0x000030F6-0x000030F7, Entry count: 0x1) [Unknown data]
	dc.b	$01
	dc.b	$05, $05, $04, $05, $00, $00, $04, $05, $05, $04, $05, $05, $00, $00, $04, $05, $04, $05, $05, $05, $00, $00, $04, $04, $04, $04, $04, $04, $00, $00 ;0x0 (0x000030F8-0x00003116, Entry count: 0x1E) [Unknown data]
loc_00003116:
	MOVEM.l	D3/D2/D1/D0, -(A7)
	MOVEA.l	$00FF3030, A0
	MOVE.l	A0, -(A7)
	BSR.b	loc_00003168
	SUBQ.w	#1, D3
loc_00003126:
	MOVE.w	D0, -(A7)
	MOVE.w	D2, D1
	BSR.w	*+$EC2E
	MOVE.w	(A7)+, D0
	ADDI.w	#$0080, D0
	DBF	D3, loc_00003126
	MOVE.l	A0, $00FF3030
	MOVEA.l	(A7)+, A0
	MOVEM.l	(A7)+, D0/D1/D2/D3
	RTS
loc_00003146:
	MOVEM.l	A6/A5/A0/D7/D6/D5/D3/D2/D1/D0, -(A7)
	BSR.b	loc_00003168
	MOVE.w	D0, D5
	MOVE.w	D2, D7
	SUBQ.w	#1, D7
	MOVE.w	D3, D6
	SUBQ.w	#1, D6
	MOVEA.l	A0, A6
	MOVE.l	A0, $00FF3030
	BSR.w	*+$EB5A
	MOVEM.l	(A7)+, D0/D1/D2/D3/D5/D6/D7/A0/A5/A6
	RTS
loc_00003168:
	LSL.w	#7, D1
	LSL.w	#1, D0
	ADD.w	D1, D0
	ADDI.w	#$C000, D0
	RTS
loc_00003174:
	MOVEM.l	A0/D6, -(A7)
	LEA	$00FF308A, A0
	MOVEQ	#7, D6
loc_00003180:
	TST.w	(A0)
	BEQ.b	loc_00003194
	SUBA.w	#$000C, A0	;Predicted (Code-scan)
	DBF	D6, loc_00003180	;Predicted (Code-scan)
	MOVE.w	D6, D0	;Predicted (Code-scan)
	MOVEM.l	(A7)+, D6/A0	;Predicted (Code-scan)
loc_00003192:
	BRA.b	loc_00003192	;Predicted (Code-scan)
loc_00003194:
	MOVE.b	D0, $2(A0)
	MOVE.b	D1, $3(A0)
	MOVE.b	D2, (A0)
	MOVE.b	D3, $1(A0)
	MOVE.b	D4, $7(A0)
	MOVE.b	#1, $6(A0)
	MOVE.w	D6, D0
	MOVEM.l	(A7)+, D6/A0
	RTS
loc_000031B4:
	MOVE.l	A0, -(A7)
	MULU.w	#$000C, D0
	LEA	$00FF3036, A0
	ADDA.w	D0, A0
	MOVE.b	#3, $6(A0)
	MOVEA.l	(A7)+, A0
	RTS
loc_000031CC:
	MOVEM.l	A6/D4/D3/D2/D1/D0, -(A7)
	MULU.w	#$000C, D0
	LEA	$00FF3036, A6
	ADDA.l	D0, A6
	BSR.w	loc_00002F72
	MOVE.b	$7(A6), D4
	ANDI.w	#3, D4
	BSR.w	loc_00002FEC
	MOVEM.l	(A7)+, D0/D1/D2/D3/D4/A6
	RTS
	dc.b	$48, $E7, $FC, $02, $C0, $FC, $00, $0C, $4D, $F9, $00, $FF, $30, $36, $DD, $C0, $61, $00, $FD, $6E, $02, $04, $00, $03, $1A, $2E, $00, $07, $02, $05, $00, $FC ;0x0 (0x000031F2-0x00003550, Entry count: 0x35E) [Unknown data]
	dc.b	$8A, $04, $1D, $45, $00, $07, $61, $00, $FF, $4E, $02, $45, $00, $03, $E1, $4D, $EB, $4D, $53, $42, $53, $43, $48, $E7, $A0, $00, $61, $00, $EB, $96, $02, $41 ;0x20
	dc.b	$9F, $FF, $82, $45, $61, $00, $EB, $5E, $54, $40, $51, $CA, $FF, $EE, $4C, $DF, $00, $05, $06, $40, $00, $80, $51, $CB, $FF, $DE, $4C, $DF, $40, $3F, $4E, $75 ;0x40
	dc.b	$48, $E7, $FC, $00, $61, $00, $FF, $10, $C8, $FC, $00, $05, $53, $42, $53, $43, $48, $E7, $A0, $00, $61, $00, $EB, $5C, $3A, $01, $02, $45, $07, $F0, $0C, $45 ;0x60
	dc.b	$05, $B0, $66, $24, $3A, $01, $02, $45, $00, $0F, $67, $1C, $0C, $45, $00, $06, $65, $0A, $5B, $45, $0C, $45, $00, $06, $65, $02, $5B, $45, $DA, $44, $02, $41 ;0x80
	dc.b	$FF, $F0, $D2, $45, $61, $00, $EA, $FE, $54, $40, $51, $CA, $FF, $C8, $4C, $DF, $00, $05, $06, $40, $00, $80, $51, $CB, $FF, $B8, $4C, $DF, $00, $3F, $4E, $75 ;0xA0
	dc.b	$2F, $0E, $C0, $FC, $00, $0C, $4D, $F9, $00, $FF, $30, $36, $DD, $C0, $42, $40, $4A, $56, $67, $00, $00, $0A, $10, $2E, $00, $06, $2C, $5F, $4E, $75, $70, $FF ;0xC0
	dc.b	$2C, $5F, $4E, $75, $2F, $04, $61, $00, $FE, $9A, $38, $00, $4E, $45, $00, $01, $30, $04, $61, $CC, $4A, $40, $66, $F4, $30, $04, $28, $1F, $4E, $75, $48, $E7 ;0xE0
	dc.b	$FE, $80, $2F, $00, $30, $3C, $00, $20, $61, $00, $08, $28, $20, $1F, $42, $68, $00, $10, $31, $7C, $FF, $FF, $00, $12, $60, $34, $48, $E7, $FE, $80, $2F, $00 ;0x100
	dc.b	$30, $3C, $00, $20, $61, $00, $08, $0C, $20, $1F, $31, $7C, $FF, $FF, $00, $10, $42, $68, $00, $12, $60, $18, $48, $E7, $FE, $80, $2F, $00, $30, $3C, $00, $20 ;0x120
	dc.b	$61, $00, $07, $F0, $20, $1F, $42, $68, $00, $10, $42, $68, $00, $12, $BC, $47, $64, $02, $3E, $06, $30, $87, $4A, $46, $6B, $00, $01, $98, $31, $40, $00, $02 ;0x140
	dc.b	$31, $41, $00, $04, $31, $42, $00, $06, $31, $43, $00, $08, $31, $46, $00, $0A, $3C, $04, $3E, $05, $34, $10, $3A, $02, $8A, $C6, $28, $05, $48, $44, $31, $46 ;0x160
	dc.b	$00, $0C, $31, $47, $00, $0E, $42, $46, $30, $06, $02, $40, $00, $07, $66, $16, $08, $06, $00, $03, $66, $0A, $7E, $02, $61, $00, $01, $12, $60, $00, $00, $08 ;0x180
	dc.b	$7E, $03, $61, $00, $01, $08, $4E, $45, $00, $01, $10, $39, $00, $FF, $27, $DA, $08, $00, $00, $06, $66, $00, $01, $2E, $08, $00, $00, $05, $66, $00, $01, $26 ;0x1A0
	dc.b	$08, $00, $00, $04, $66, $00, $01, $50, $10, $39, $00, $FF, $27, $DC, $08, $00, $00, $00, $66, $16, $08, $00, $00, $01, $66, $2A, $08, $00, $00, $02, $66, $50 ;0x1C0
	dc.b	$08, $00, $00, $03, $66, $7E, $52, $46, $60, $9E, $4A, $45, $67, $F8, $7E, $03, $61, $00, $00, $BA, $53, $45, $94, $68, $00, $0C, $42, $46, $70, $67, $61, $00 ;0x1E0
	dc.b	$EF, $84, $60, $84, $36, $28, $00, $0E, $53, $43, $BA, $43, $64, $D8, $36, $28, $00, $0C, $D6, $42, $B6, $68, $00, $0A, $62, $CC, $34, $03, $7E, $03, $61, $00 ;0x200
	dc.b	$00, $8C, $52, $45, $42, $46, $70, $67, $61, $00, $EF, $5A, $60, $00, $FF, $5A, $4A, $44, $67, $00, $00, $16, $7E, $03, $61, $72, $53, $44, $53, $42, $42, $46 ;0x220
	dc.b	$70, $67, $61, $00, $EF, $40, $60, $00, $FF, $40, $4A, $68, $00, $10, $67, $96, $7E, $03, $61, $58, $70, $67, $61, $00, $EF, $2C, $00, $42, $80, $00, $30, $82 ;0x240
	dc.b	$60, $00, $00, $CA, $36, $28, $00, $0C, $53, $43, $B8, $43, $64, $00, $00, $22, $36, $02, $52, $43, $B6, $68, $00, $0A, $62, $00, $00, $16, $34, $03, $7E, $03 ;0x260
	dc.b	$61, $2A, $52, $44, $42, $46, $70, $67, $61, $00, $EE, $FA, $60, $00, $FE, $FA, $4A, $68, $00, $10, $67, $00, $FF, $50, $7E, $03, $61, $10, $70, $67, $61, $00 ;0x280
	dc.b	$EE, $E4, $00, $42, $C0, $00, $30, $82, $60, $00, $00, $82, $48, $E7, $28, $00, $30, $28, $00, $06, $54, $40, $C0, $C4, $D0, $68, $00, $02, $32, $28, $00, $08 ;0x2A0
	dc.b	$52, $41, $0C, $41, $00, $01, $66, $02, $52, $41, $C2, $C5, $D2, $68, $00, $04, $34, $28, $00, $06, $36, $28, $00, $08, $28, $07, $61, $00, $E9, $4C, $4C, $DF ;0x2C0
	dc.b	$00, $14, $4E, $75, $7E, $02, $61, $C4, $30, $82, $70, $66, $61, $00, $EE, $96, $60, $3A, $4E, $45, $00, $01, $10, $39, $00, $FF, $27, $DA, $08, $00, $00, $06 ;0x2E0
	dc.b	$66, $00, $00, $20, $08, $00, $00, $05, $66, $00, $00, $18, $08, $00, $00, $04, $66, $00, $00, $10, $60, $DC, $4A, $68, $00, $12, $6B, $00, $FE, $CA, $7E, $03 ;0x300
	dc.b	$61, $8A, $7A, $FF, $30, $85, $70, $68, $61, $00, $EE, $5A, $3E, $10, $61, $00, $06, $76, $4C, $DF, $01, $7F, $4E, $75, $48, $E7, $40, $80, $42, $40, $12, $18 ;0x320
	dc.b	$67, $16, $0C, $01, $00, $0A, $65, $F6, $0C, $01, $00, $7B, $67, $F0, $0C, $01, $00, $7C, $67, $EA, $52, $40, $60, $E6, $4C, $DF, $01, $02, $4E, $75 ;0x340
loc_00003550:
	MOVEM.l	A2/A1/A0/D1/D0, -(A7)
	LEA	loc_000035E8(PC), A2
loc_00003558:
	CLR.w	D0
	MOVE.b	(A0)+, D0
	BNE.b	loc_00003568
	MOVE.b	#0, (A1)
	MOVEM.l	(A7)+, D0/D1/A0/A1/A2
	RTS
loc_00003568:
	CMPI.w	#$001A, D0
	BCS.b	loc_000035A4
	CMPI.w	#$003F, D0
	BCS.b	loc_00003598
	BEQ.b	loc_00003594	;Predicted (Code-scan)
	CMPI.w	#$007B, D0	;Predicted (Code-scan)
	BCS.b	loc_000035B2	;Predicted (Code-scan)
	CMPI.w	#$007D, D0	;Predicted (Code-scan)
	BEQ.b	loc_000035A0	;Predicted (Code-scan)
	CMPI.w	#$0080, D0	;Predicted (Code-scan)
	BCS.b	loc_00003594	;Predicted (Code-scan)
	CMPI.w	#$00B7, D0	;Predicted (Code-scan)
	BCS.b	loc_000035BE	;Predicted (Code-scan)
	CMPI.w	#$00B8, D0	;Predicted (Code-scan)
	BEQ.b	loc_000035A8	;Predicted (Code-scan)
loc_00003594:
	MOVEQ	#$0000000F, D1	;Predicted (Code-scan)
	BRA.b	loc_000035E2	;Predicted (Code-scan)
loc_00003598:
	MOVE.w	D0, D1
	ADDI.w	#0, D1
	BRA.b	loc_000035E2
loc_000035A0:
	MOVEQ	#$0000001F, D1	;Predicted (Code-scan)
	BRA.b	loc_000035E2	;Predicted (Code-scan)
loc_000035A4:
	MOVE.w	D0, D1
	BRA.b	loc_000035E2
loc_000035A8:
	MOVE.b	#1, (A1)+	;Predicted (Code-scan)
	MOVE.w	#$0083, D1	;Predicted (Code-scan)
	BRA.b	loc_000035E2	;Predicted (Code-scan)
loc_000035B2:
	SUBI.w	#$0040, D0	;Predicted (Code-scan)
	CLR.w	D1	;Predicted (Code-scan)
	MOVE.b	(A2,D0.w), D1	;Predicted (Code-scan)
	BRA.b	loc_000035CC	;Predicted (Code-scan)
loc_000035BE:
	SUBI.w	#$0080, D0	;Predicted (Code-scan)
	CLR.w	D1	;Predicted (Code-scan)
	MOVE.b	(A2,D0.w), D1	;Predicted (Code-scan)
	ADDI.w	#$0050, D1	;Predicted (Code-scan)
loc_000035CC:
	MOVE.b	(A0), D0	;Predicted (Code-scan)
	CMPI.b	#$7B, D0	;Predicted (Code-scan)
	BEQ.b	loc_000035DE	;Predicted (Code-scan)
	CMPI.b	#$7C, D0	;Predicted (Code-scan)
	BNE.b	loc_000035E2	;Predicted (Code-scan)
	ADDQ.w	#2, D1	;Predicted (Code-scan)
	BRA.b	loc_000035E0	;Predicted (Code-scan)
loc_000035DE:
	ADDQ.w	#1, D1	;Predicted (Code-scan)
loc_000035E0:
	ADDQ.l	#1, A0	;Predicted (Code-scan)
loc_000035E2:
	MOVE.b	D1, (A1)+
	BRA.w	loc_00003558
loc_000035E8:
	dc.b	$21, $23, $25, $27, $29, $2A, $2C, $2E, $30, $32, $34, $36, $38, $3A, $3C, $3E, $40, $43, $45, $47, $49, $4A, $4B, $4C, $4D, $4E, $51, $54, $57, $5A, $5D, $5E ;0x0 (0x000035E8-0x0000379E, Entry count: 0x1B6) [Unknown data]
	dc.b	$5F, $60, $61, $63, $65, $67, $68, $69, $6A, $6B, $6C, $6D, $6E, $6F, $20, $22, $24, $26, $28, $42, $62, $64, $66, $1B, $1A, $4C, $4D, $0F, $0F, $0F, $0F, $0F ;0x20
	dc.b	$48, $E7, $F0, $C0, $22, $48, $30, $7C, $C0, $00, $36, $00, $42, $42, $14, $19, $67, $42, $0C, $02, $00, $7B, $67, $12, $0C, $02, $00, $7C, $67, $0C, $0C, $02 ;0x40
	dc.b	$00, $0D, $66, $18, $54, $41, $30, $03, $60, $E2, $53, $40, $53, $41, $06, $42, $E4, $F0, $61, $00, $E7, $92, $52, $40, $52, $41, $60, $D0, $06, $42, $E4, $F0 ;0x60
	dc.b	$61, $00, $E7, $84, $53, $41, $34, $3C, $E5, $2F, $61, $00, $E7, $7A, $52, $41, $52, $40, $60, $B8, $4C, $DF, $03, $0F, $4E, $75, $48, $E7, $F0, $C0, $22, $48 ;0x80
	dc.b	$30, $7C, $C0, $00, $36, $00, $42, $42, $14, $19, $67, $24, $0C, $02, $00, $7B, $67, $F4, $0C, $02, $00, $7C, $67, $EE, $0C, $02, $00, $0D, $66, $06, $54, $41 ;0xA0
	dc.b	$30, $03, $60, $E2, $06, $42, $E4, $F0, $61, $00, $E7, $3C, $52, $40, $60, $D6, $4C, $DF, $03, $0F, $4E, $75, $48, $E7, $00, $A0, $48, $E7, $80, $80, $30, $3C ;0xC0
	dc.b	$00, $10, $61, $00, $04, $58, $24, $48, $4C, $DF, $01, $01, $2F, $09, $22, $4A, $61, $00, $FE, $76, $20, $49, $22, $5F, $61, $10, $2F, $08, $20, $4A, $61, $00 ;0xE0
	dc.b	$04, $B0, $20, $5F, $4C, $DF, $05, $00, $4E, $75, $48, $E7, $FF, $80, $3C, $00, $38, $00, $3E, $01, $42, $40, $10, $18, $67, $2C, $0C, $00, $00, $0D, $66, $06 ;0x100
	dc.b	$3C, $04, $54, $47, $60, $EE, $0C, $00, $00, $0E, $66, $04, $52, $46, $60, $E4, $0C, $00, $00, $03, $64, $04, $E1, $48, $10, $18, $61, $00, $E8, $C4, $4E, $71 ;0x120
	dc.b	$D2, $FC, $00, $40, $60, $CE, $4C, $DF, $01, $FF, $4E, $75, $48, $E7, $08, $C0, $2F, $00, $30, $3C, $00, $10, $61, $00, $03, $E4, $20, $1F, $78, $3F, $61, $56 ;0x140
	dc.b	$61, $00, $FF, $38, $61, $00, $04, $4A, $4C, $DF, $03, $10, $4E, $75, $48, $E7, $08, $C0, $2F, $00, $30, $3C, $00, $10, $61, $00, $03, $C2, $20, $1F, $78, $10 ;0x160
	dc.b	$61, $34, $61, $00, $FF, $16, $61, $00, $04, $28, $4C, $DF, $03, $10, $4E, $75, $48, $E7, $08, $80, $2F, $00, $30, $3C, $00, $10, $61, $00, $03, $A0, $20, $1F ;0x180
	dc.b	$2F, $09, $78, $0F, $61, $10, $22, $5F, $61, $00, $FF, $60, $61, $00, $04, $02, $4C, $DF, $01, $10, $4E, $75 ;0x1A0
loc_0000379E:
	MOVEM.l	D5/D4/D3/D2/D1/D0, -(A7)	;Predicted (Code-scan)
	MOVE.b	D4, D5	;Predicted (Code-scan)
	MOVEA.l	A0, A1	;Predicted (Code-scan)
	MOVE.w	D3, D0	;Predicted (Code-scan)
	BNE.b	loc_000037AC	;Predicted (Code-scan)
	MOVEQ	#6, D3	;Predicted (Code-scan)
loc_000037AC:
	CMPI.w	#7, D3	;Predicted (Code-scan)
	BCS.b	loc_000037B4	;Predicted (Code-scan)
	MOVEQ	#6, D3	;Predicted (Code-scan)
loc_000037B4:
	MOVEQ	#1, D4	;Predicted (Code-scan)
loc_000037B6:
	SUBQ.w	#1, D3	;Predicted (Code-scan)
	BEQ.b	loc_000037C0	;Predicted (Code-scan)
	MULU.w	#$000A, D4	;Predicted (Code-scan)
	BRA.b	loc_000037B6	;Predicted (Code-scan)
loc_000037C0:
	MOVE.l	D4, D3	;Predicted (Code-scan)
	MOVE.l	D2, D4	;Predicted (Code-scan)
	CLR.w	D1	;Predicted (Code-scan)
loc_000037C6:
	MOVEQ	#$00000010, D2	;Predicted (Code-scan)
loc_000037C8:
	SUB.l	D3, D4	;Predicted (Code-scan)
	BMI.b	loc_000037D2	;Predicted (Code-scan)
	ADDQ.w	#1, D2	;Predicted (Code-scan)
	MOVEQ	#1, D1	;Predicted (Code-scan)
	BRA.b	loc_000037C8	;Predicted (Code-scan)
loc_000037D2:
	ADD.l	D3, D4	;Predicted (Code-scan)
	TST.w	D1	;Predicted (Code-scan)
	BNE.b	loc_000037E4	;Predicted (Code-scan)
	CMPI.w	#1, D3	;Predicted (Code-scan)
	BEQ.b	loc_000037E4	;Predicted (Code-scan)
	TST.w	D0	;Predicted (Code-scan)
	BEQ.b	loc_000037E6	;Predicted (Code-scan)
	MOVE.b	D5, D2	;Predicted (Code-scan)
loc_000037E4:
	MOVE.b	D2, (A1)+	;Predicted (Code-scan)
loc_000037E6:
	DIVU.w	#$000A, D3	;Predicted (Code-scan)
	BNE.b	loc_000037C6	;Predicted (Code-scan)
	MOVE.b	#0, (A1)	;Predicted (Code-scan)
	MOVEM.l	(A7)+, D0/D1/D2/D3/D4/D5	;Predicted (Code-scan)
	RTS	;Predicted (Code-scan)
	dc.b	$33, $FC, $FF, $FF, $00, $FF, $30, $96, $4E, $75 ;0x0 (0x000037F6-0x00003800, Entry count: 0xA) [Unknown data]
	TST.w	$00FF3096
	BPL.b	loc_0000382E-2
	MOVEM.l	D4/D3/D2/D1/D0, -(A7)
	MOVEQ	#1, D0
	MOVEQ	#$00000014, D1
	MOVEQ	#$00000026, D2
	MOVE.w	#7, D3
	MOVE.w	#$00C3, D4
	BSR.w	loc_00003174
	MOVE.w	D0, $00FF3096
	TRAP	#5
	ORI.b	#$DF, D1	;Predicted (Code-scan)
	ORI.b	#$75, (A7)+	;Predicted (Code-scan)
loc_0000382E:
	MOVEM.l	D0, -(A7)
	MOVE.w	$00FF3096, D0
	BMI.b	loc_00003846
	BSR.w	loc_000031B4
	MOVE.w	#$FFFF, $00FF3096
loc_00003846:
	MOVEM.l	(A7)+, D0
	TRAP	#5
	ORI.b	#$75, D1	;Predicted (Code-scan)
	MOVEM.l	A6/A5/A4/A3/A2/A1/A0/D7/D6/D5/D4/D3/D2/D1/D0, -(A7)
	MOVE.w	D0, D5
	LEA	$00FF3098, A6
	MOVEM.l	A0/D0, -(A7)
	MOVE.w	#$00A0, D0
	BSR.w	loc_00003B24
	MOVEA.l	A0, A5
	MOVEM.l	(A7)+, D0/A0
loc_0000386E:
	MOVE.w	$00FF3096, D0
	BMI.w	loc_000039F2
	BSR.w	loc_000031CC
	MOVEQ	#4, D4
	BTST.l	#1, D5
	BEQ.b	loc_00003886
	CLR.w	D4	;Predicted (Code-scan)
loc_00003886:
	MOVEA.w	#$F000, A2
	MOVEQ	#$00000015, D7
	MOVE.w	#2, $9E(A5)
loc_00003892:
	MOVEA.l	A5, A1
	MOVEQ	#1, D1
	BSR.w	loc_00003A6A
	MOVEQ	#3, D6
	MOVEA.l	A5, A3
loc_0000389E:
	TST.b	(A3)
	BEQ.b	loc_00003908
	CMPI.w	#$0025, D6
	BCC.w	loc_0000393C
	CLR.w	D0
	MOVE.b	(A3)+, D0
	CMPI.b	#3, D0
	BCC.b	loc_000038B8
	LSL.w	#8, D0	;Predicted (Code-scan)
	MOVE.b	(A3)+, D0	;Predicted (Code-scan)
loc_000038B8:
	MOVEA.l	A2, A1
	BSR.w	loc_00001FE8
	ADDA.w	#$0040, A2
	CMPA.w	#$FFC0, A2
	BNE.b	loc_000038CC
	MOVEA.w	#$F000, A2	;Predicted (Code-scan)
loc_000038CC:
	MOVE.w	D4, D0
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
loc_000038DC:
	TRAP	#5
	ORI.b	#$39, D1	;Predicted (Code-scan)
	ORI.b	#$FF, D6	;Predicted (Code-scan)
	dc.b	$27, $DA ;0x0 (0x000038E6-0x000038E8, Entry count: 0x2) [Unknown data]
	BNE.b	loc_000038FE
	BTST.b	#4, $00FF27DA
	BNE.b	loc_000038FE
	BTST.b	#5, $00FF27DA
	BEQ.b	loc_00003902
loc_000038FE:
	CLR.w	D0
	CLR.w	D4
loc_00003902:
	DBF	D0, loc_000038DC
	BRA.b	loc_0000389E
loc_00003908:
	MOVE.b	(A0), D0
	BEQ.b	loc_0000395C
	CMPI.b	#$0C, D0	;Predicted (Code-scan)
	BNE.b	loc_00003918	;Predicted (Code-scan)
	BSR.w	loc_00003A5A	;Predicted (Code-scan)
	BRA.b	loc_00003968	;Predicted (Code-scan)
loc_00003918:
	SUBQ.w	#1, $9E(A5)	;Predicted (Code-scan)
	ADDQ.w	#2, D7	;Predicted (Code-scan)
	CMPI.w	#$0019, D7	;Predicted (Code-scan)
	BEQ.b	loc_0000392A	;Predicted (Code-scan)
	ADDQ.l	#1, A0	;Predicted (Code-scan)
	BRA.w	loc_00003892	;Predicted (Code-scan)
loc_0000392A:
	TST.w	$9E(A5)	;Predicted (Code-scan)
	BEQ.b	loc_00003968	;Predicted (Code-scan)
	BSR.w	loc_00003A02	;Predicted (Code-scan)
	MOVEQ	#$00000017, D7	;Predicted (Code-scan)
	ADDQ.l	#1, A0	;Predicted (Code-scan)
	BRA.w	loc_00003892	;Predicted (Code-scan)
loc_0000393C:
	MOVEQ	#3, D6	;Predicted (Code-scan)
	SUBQ.w	#1, $9E(A5)	;Predicted (Code-scan)
	ADDQ.w	#2, D7	;Predicted (Code-scan)
	CMPI.w	#$0019, D7	;Predicted (Code-scan)
	BNE.w	loc_0000389E	;Predicted (Code-scan)
	TST.w	$9E(A5)	;Predicted (Code-scan)
	BEQ.b	loc_00003968	;Predicted (Code-scan)
	BSR.w	loc_00003A02	;Predicted (Code-scan)
	MOVEQ	#$00000017, D7	;Predicted (Code-scan)
	BRA.w	loc_0000389E	;Predicted (Code-scan)
loc_0000395C:
	BSR.w	loc_00003A5A
	BTST.l	#0, D5
	BNE.w	loc_000039F2
loc_00003968:
	MOVE.l	A0, -(A7)
	CLR.w	D3
	MOVEQ	#$00000024, D0
	MOVEQ	#$00000019, D1
	MOVEA.w	#$C000, A0
loc_00003974:
	BTST.l	#2, D5
	BEQ.b	loc_00003980
	CMPI.w	#$0032, D3	;Predicted (Code-scan)
	BCC.b	loc_000039B6	;Predicted (Code-scan)
loc_00003980:
	MOVE.w	#$E52F, D2
	BTST.l	#4, D3
	BNE.b	loc_0000398E
	MOVE.w	#$E56E, D2
loc_0000398E:
	BSR.w	*+$E45E
	TRAP	#5
	ORI.b	#$43, D1	;Predicted (Code-scan)
	BTST.b	#6, $00FF27DA
	BNE.b	loc_000039B6
	BTST.b	#4, $00FF27DA
	BNE.b	loc_000039B6
	BTST.b	#5, $00FF27DA
	BEQ.b	loc_00003974
loc_000039B6:
	MOVEQ	#$00000024, D0
	MOVEQ	#$00000019, D1
	MOVEA.w	#$C000, A0
	MOVE.w	#$E52F, D2
	BSR.w	*+$E42A
	MOVEA.l	(A7)+, A0
	TST.b	(A3)
	BNE.b	loc_000039DA
	MOVE.b	(A0), D2
	BEQ.b	loc_000039F2
	ADDQ.l	#1, A0	;Predicted (Code-scan)
	CMPI.b	#$0C, D2	;Predicted (Code-scan)
	BEQ.w	loc_0000386E	;Predicted (Code-scan)
loc_000039DA:
	MOVE.w	#2, $9E(A5)	;Predicted (Code-scan)
	BSR.b	loc_00003A02	;Predicted (Code-scan)
	MOVE.w	#6, D4	;Predicted (Code-scan)
	MOVEQ	#$00000017, D7	;Predicted (Code-scan)
	TST.b	(A3)	;Predicted (Code-scan)
	BNE.w	loc_0000389E	;Predicted (Code-scan)
	BRA.w	loc_00003892	;Predicted (Code-scan)
loc_000039F2:
	MOVE.l	A0, -(A7)
	MOVEA.l	A5, A0
	BSR.w	loc_00003B98
	MOVEA.l	(A7)+, A0
	MOVEM.l	(A7)+, D0/D1/D2/D3/D4/D5/D6/D7/A0/A1/A2/A3/A4/A5/A6
	RTS
loc_00003A02:
	MOVEQ	#1, D2	;Predicted (Code-scan)
	MOVEM.l	A6/A4/A0/D7/D6/D5/D4/D3/D2/D1/D0, -(A7)	;Predicted (Code-scan)
	MOVEM.l	A0/D0, -(A7)	;Predicted (Code-scan)
	MOVE.w	#$0050, D0	;Predicted (Code-scan)
	BSR.w	loc_00003B24	;Predicted (Code-scan)
	MOVEA.l	A0, A4	;Predicted (Code-scan)
	MOVEM.l	(A7)+, D0/A0	;Predicted (Code-scan)
	CLR.l	D0	;Predicted (Code-scan)
	MOVE.w	#$CB06, D0	;Predicted (Code-scan)
	MOVEQ	#$00000022, D1	;Predicted (Code-scan)
	MOVEQ	#3, D2	;Predicted (Code-scan)
loc_00003A24:
	MOVEA.l	A4, A0	;Predicted (Code-scan)
	BSR.w	*+$E332	;Predicted (Code-scan)
	MOVE.l	D0, D5	;Predicted (Code-scan)
	SUBI.w	#$0080, D5	;Predicted (Code-scan)
	MOVEQ	#$00000021, D7	;Predicted (Code-scan)
	CLR.w	D6	;Predicted (Code-scan)
	MOVEA.l	A4, A6	;Predicted (Code-scan)
	BSR.w	*+$E282	;Predicted (Code-scan)
	ADDI.w	#$0080, D0	;Predicted (Code-scan)
	DBF	D2, loc_00003A24	;Predicted (Code-scan)
	MOVE.l	A0, -(A7)	;Predicted (Code-scan)
	MOVEA.l	A4, A0	;Predicted (Code-scan)
	BSR.w	loc_00003B98	;Predicted (Code-scan)
	MOVEA.l	(A7)+, A0	;Predicted (Code-scan)
	MOVEM.l	(A7)+, D0/D1/D2/D3/D4/D5/D6/D7/A0/A4/A6	;Predicted (Code-scan)
	TRAP	#5	;Predicted (Code-scan)
	ORI.b	#$CA, D4	;Predicted (Code-scan)
	dc.b	$FF, $AE, $4E, $75 ;0x0 (0x00003A56-0x00003A5A, Entry count: 0x4) [Unknown data]
loc_00003A5A:
	CMPI.w	#2, $9E(A5)
	BCS.b	loc_00003A6A
	CMPI.w	#$0015, D7
	BEQ.b	loc_00003A6A
	BSR.b	loc_00003A02	;Predicted (Code-scan)
loc_00003A6A:
	MOVEM.l	A2/A1/D4/D3/D2/D1/D0, -(A7)
	MOVEA.l	A0, A2
loc_00003A70:
	CLR.w	D2
	MOVE.b	(A2)+, D2
	BEQ.w	loc_00003AFE
	CMPI.b	#3, D2
	BCC.b	loc_00003A84
	MOVE.b	D2, (A1)+	;Predicted (Code-scan)
	MOVE.b	(A2)+, (A1)+	;Predicted (Code-scan)
	BRA.b	loc_00003A70	;Predicted (Code-scan)
loc_00003A84:
	BNE.b	loc_00003A9C
	MOVEA.l	(A6)+, A0	;Predicted (Code-scan)
loc_00003A88:
	MOVE.b	(A0)+, D3	;Predicted (Code-scan)
	BEQ.b	loc_00003A9A	;Predicted (Code-scan)
	CMPI.b	#3, D3	;Predicted (Code-scan)
	BCC.b	loc_00003A96	;Predicted (Code-scan)
	MOVE.b	D3, (A1)+	;Predicted (Code-scan)
	MOVE.b	(A0)+, D3	;Predicted (Code-scan)
loc_00003A96:
	MOVE.b	D3, (A1)+	;Predicted (Code-scan)
	BRA.b	loc_00003A88	;Predicted (Code-scan)
loc_00003A9A:
	BRA.b	loc_00003A70	;Predicted (Code-scan)
loc_00003A9C:
	CMPI.b	#4, D2
	BNE.b	loc_00003AB2
	MOVE.l	(A6)+, D2	;Predicted (Code-scan)
	CLR.w	D3	;Predicted (Code-scan)
	MOVE.b	(A2)+, D3	;Predicted (Code-scan)
	MOVEA.l	A1, A0	;Predicted (Code-scan)
	MOVEQ	#$0000000F, D4	;Predicted (Code-scan)
	BSR.w	loc_0000379E	;Predicted (Code-scan)
	BRA.b	loc_00003A70	;Predicted (Code-scan)
loc_00003AB2:
	CMPI.b	#5, D2
	BNE.b	loc_00003ACC
	MOVE.b	(A2)+, D2
	BSR.w	*+$6720
	BSR.w	loc_00003550
loc_00003AC2:
	TST.b	(A1)
	BEQ.b	loc_00003ACA
	ADDQ.l	#1, A1
	BRA.b	loc_00003AC2
loc_00003ACA:
	BRA.b	loc_00003A70
loc_00003ACC:
	CMPI.b	#6, D2
	BNE.b	loc_00003AE2
	MOVEA.l	(A6)+, A0	;Predicted (Code-scan)
	BSR.w	loc_00003550	;Predicted (Code-scan)
loc_00003AD8:
	TST.b	(A1)	;Predicted (Code-scan)
	BEQ.b	loc_00003AE0	;Predicted (Code-scan)
	ADDQ.l	#1, A1	;Predicted (Code-scan)
	BRA.b	loc_00003AD8	;Predicted (Code-scan)
loc_00003AE0:
	BRA.b	loc_00003A70	;Predicted (Code-scan)
loc_00003AE2:
	CMPI.b	#$0F, D2
	BCC.b	loc_00003AF8
	CMPI.b	#$0D, D2	;Predicted (Code-scan)
	BEQ.b	loc_00003AF4	;Predicted (Code-scan)
	CMPI.b	#$0C, D2	;Predicted (Code-scan)
loc_00003AF2:
	BNE.b	loc_00003AF2	;Predicted (Code-scan)
loc_00003AF4:
	TST.w	D1	;Predicted (Code-scan)
	BNE.b	loc_00003AFE	;Predicted (Code-scan)
loc_00003AF8:
	MOVE.b	D2, (A1)+
	BRA.w	loc_00003A70
loc_00003AFE:
	CLR.b	(A1)
	MOVEA.l	A2, A0
	SUBQ.l	#1, A0
	MOVEM.l	(A7)+, D0/D1/D2/D3/D4/A1/A2
	RTS
	dc.b	$48, $E7, $80, $80, $30, $3C, $01, $FF, $41, $F9, $00, $FF, $30, $B8, $42, $18, $51, $C8, $FF, $FC, $4C, $DF, $01, $01, $4E, $75 ;0x0 (0x00003B0A-0x00003B24, Entry count: 0x1A) [Unknown data]
loc_00003B24:
	MOVEM.l	A3/A2/A1/D2/D1/D0, -(A7)
	LEA	$00FF32B8, A0
	LEA	$00FF30B8, A1
	MOVE.w	#$01FF, D1
	ADDI.w	#$000F, D0
	LSR.w	#4, D0
loc_00003B3E:
	TST.b	(A1)
	BEQ.b	loc_00003B50
loc_00003B42:
	ADDQ.l	#1, A1
	ADDA.w	#$0010, A0
	DBF	D1, loc_00003B3E
	BRA.w	loc_00003B96	;Predicted (Code-scan)
loc_00003B50:
	MOVEA.l	A0, A2
	MOVEA.l	A1, A3
	MOVE.w	D0, D2
loc_00003B56:
	TST.b	(A1)
	BNE.b	loc_00003B42
	SUBQ.w	#1, D2
	BEQ.b	loc_00003B6C
	ADDQ.l	#1, A1
	ADDA.w	#$0010, A0
	DBF	D1, loc_00003B56
	BRA.w	loc_00003B96	;Predicted (Code-scan)
loc_00003B6C:
	MOVEQ	#1, D2
loc_00003B6E:
	LEA	$00FF30B8, A1
	MOVE.w	#$01FF, D1
loc_00003B78:
	CMP.b	(A1)+, D2
	BEQ.b	loc_00003B82
	DBF	D1, loc_00003B78
	BRA.b	loc_00003B86
loc_00003B82:
	ADDQ.b	#1, D2
	BRA.b	loc_00003B6E
loc_00003B86:
	SUBQ.w	#1, D0
loc_00003B88:
	MOVE.b	D2, (A3)+
	DBF	D0, loc_00003B88
	MOVEA.l	A2, A0
	MOVEM.l	(A7)+, D0/D1/D2/A1/A2/A3
	RTS
loc_00003B96:
	BRA.b	loc_00003B96	;Predicted (Code-scan)
loc_00003B98:
	MOVEM.l	A0/D0, -(A7)
	SUBA.l	#$00FF32B8, A0
	MOVE.l	A0, D0
	LSR.l	#4, D0
	LEA	$00FF30B8, A0
	ADDA.l	D0, A0
	MOVE.b	(A0), D0
	BEQ.b	loc_00003BC0
loc_00003BB2:
	CMP.b	(A0), D0
	BNE.b	loc_00003BBA
	CLR.b	(A0)+
	BRA.b	loc_00003BB2
loc_00003BBA:
	MOVEM.l	(A7)+, D0/A0
	RTS
loc_00003BC0:
	BRA.b	loc_00003BC0	;Predicted (Code-scan)
	MOVE.l	$00FFCED2, D0
	ANDI.w	#$07FF, D0
	CMPI.w	#$0100, D0
	BCC.b	loc_00003BD6
	MOVEQ	#3, D0	;Predicted (Code-scan)
	RTS	;Predicted (Code-scan)
loc_00003BD6:
	CMPI.w	#$0400, D0
	BCC.b	loc_00003BE0
	CLR.w	D0	;Predicted (Code-scan)
	RTS	;Predicted (Code-scan)
loc_00003BE0:
	CMPI.w	#$0500, D0
	BCC.b	loc_00003BEA
	MOVEQ	#1, D0	;Predicted (Code-scan)
	RTS	;Predicted (Code-scan)
loc_00003BEA:
	MOVEQ	#2, D0
	RTS
	dc.b	$48, $E7, $C0, $00, $02, $80, $00, $00, $07, $FF, $22, $39, $00, $FF, $CE, $D2, $02, $41, $07, $FF, $B2, $40, $65, $14, $06, $80, $00, $00, $08, $00, $4A, $79 ;0x0 (0x00003BEE-0x00004000, Entry count: 0x412) [Unknown data]
	dc.b	$00, $FF, $D6, $52, $67, $06, $53, $79, $00, $FF, $D6, $52, $22, $39, $00, $FF, $CE, $D2, $02, $81, $FF, $FF, $F8, $00, $D2, $80, $23, $C1, $00, $FF, $CE, $D2 ;0x20
	dc.b	$4C, $DF, $00, $03, $4E, $75, $48, $E7, $C0, $80, $61, $3A, $03, $D0, $4C, $DF, $01, $03, $4E, $75, $48, $E7, $C0, $80, $61, $2C, $03, $90, $4C, $DF, $01, $03 ;0x40
	dc.b	$4E, $75, $48, $E7, $40, $80, $61, $1E, $08, $01, $00, $0F, $66, $08, $03, $10, $67, $0C, $70, $01, $60, $0A, $03, $10, $66, $04, $70, $01, $60, $02, $42, $40 ;0x60
	dc.b	$4C, $DF, $01, $02, $4E, $75, $41, $F9, $00, $FF, $52, $B8, $53, $40, $32, $00, $08, $80, $00, $0F, $E6, $48, $48, $C0, $D1, $C0, $4E, $75, $48, $E7, $80, $80 ;0x80
	dc.b	$41, $F9, $00, $FF, $52, $B8, $70, $27, $42, $98, $51, $C8, $FF, $FC, $4C, $DF, $01, $01, $4E, $75, $48, $E7, $80, $80, $53, $40, $02, $40, $00, $FF, $48, $C0 ;0xA0
	dc.b	$41, $F9, $00, $FF, $53, $58, $D1, $C0, $10, $81, $4C, $DF, $01, $01, $4E, $75, $2F, $08, $53, $40, $02, $40, $00, $FF, $48, $C0, $41, $F9, $00, $FF, $53, $58 ;0xC0
	dc.b	$D1, $C0, $42, $80, $10, $10, $20, $5F, $4E, $75, $2F, $08, $53, $40, $02, $40, $00, $FF, $48, $C0, $41, $F9, $00, $FF, $53, $58, $D1, $C0, $52, $10, $20, $5F ;0xE0
	dc.b	$4E, $75, $2F, $08, $53, $40, $02, $40, $00, $FF, $48, $C0, $41, $F9, $00, $FF, $53, $58, $D1, $C0, $53, $10, $20, $5F, $4E, $75, $48, $E7, $60, $C0, $42, $42 ;0x100
	dc.b	$20, $7C, $00, $20, $00, $01, $01, $48, $00, $02, $0C, $80, $41, $42, $59, $00, $67, $20, $01, $48, $20, $02, $0C, $80, $41, $42, $59, $00, $67, $14, $42, $80 ;0x120
	dc.b	$32, $3C, $07, $FF, $22, $48, $01, $C9, $00, $00, $50, $89, $51, $C9, $FF, $F8, $74, $FF, $20, $3C, $41, $42, $59, $00, $01, $C8, $00, $02, $01, $C8, $20, $02 ;0x140
	dc.b	$30, $02, $4C, $DF, $03, $06, $4E, $75, $23, $FC, $00, $20, $00, $0B, $00, $FF, $53, $9A, $4E, $75, $48, $E7, $C0, $C0, $53, $40, $22, $79, $00, $FF, $53, $9A ;0x160
	dc.b	$03, $09, $00, $00, $30, $C1, $58, $89, $51, $C8, $FF, $F6, $23, $C9, $00, $FF, $53, $9A, $4C, $DF, $03, $03, $4E, $75, $48, $E7, $C0, $C0, $53, $40, $22, $79 ;0x180
	dc.b	$00, $FF, $53, $9A, $58, $89, $51, $C8, $FF, $FC, $23, $C9, $00, $FF, $53, $9A, $4C, $DF, $03, $03, $4E, $75, $48, $E7, $C0, $C0, $53, $40, $22, $79, $00, $FF ;0x1A0
	dc.b	$53, $9A, $32, $18, $03, $89, $00, $00, $58, $89, $51, $C8, $FF, $F6, $23, $C9, $00, $FF, $53, $9A, $4C, $DF, $03, $03, $4E, $75, $48, $E7, $E0, $C0, $20, $7C ;0x1C0
	dc.b	$00, $20, $00, $0B, $22, $48, $D3, $FC, $00, $00, $20, $00, $42, $42, $32, $3C, $07, $FB, $01, $08, $00, $00, $01, $89, $00, $00, $D4, $40, $58, $88, $58, $89 ;0x1E0
	dc.b	$51, $C9, $FF, $F0, $05, $88, $00, $00, $05, $89, $00, $00, $4C, $DF, $03, $07, $4E, $75, $48, $E7, $20, $C0, $20, $7C, $00, $20, $00, $0B, $42, $42, $32, $3C ;0x200
	dc.b	$07, $FB, $01, $08, $00, $00, $D4, $40, $58, $88, $51, $C9, $FF, $F6, $01, $08, $00, $00, $B4, $40, $67, $5A, $20, $7C, $00, $20, $00, $0B, $22, $48, $D3, $FC ;0x220
	dc.b	$00, $00, $20, $00, $42, $42, $32, $3C, $07, $FB, $01, $09, $00, $00, $01, $88, $00, $00, $D4, $40, $58, $88, $58, $89, $51, $C9, $FF, $F0, $01, $09, $00, $00 ;0x240
	dc.b	$01, $88, $00, $00, $B4, $40, $67, $28, $20, $7C, $00, $20, $00, $0B, $22, $48, $D3, $FC, $00, $00, $20, $00, $42, $42, $32, $3C, $07, $FC, $05, $88, $00, $00 ;0x260
	dc.b	$05, $89, $00, $00, $58, $88, $58, $89, $51, $C9, $FF, $F2, $70, $FF, $60, $02, $42, $40, $20, $7C, $00, $20, $00, $0B, $03, $48, $00, $00, $4C, $DF, $03, $04 ;0x280
	dc.b	$4E, $75, $48, $E7, $80, $80, $61, $00, $FE, $C0, $41, $F9, $00, $00, $3E, $FE, $70, $02, $61, $00, $FF, $02, $41, $F9, $00, $FF, $CA, $6E, $70, $01, $61, $00 ;0x2A0
	dc.b	$FE, $F6, $41, $F9, $00, $FF, $CA, $9E, $70, $03, $61, $00, $FE, $EA, $41, $F9, $00, $FF, $CA, $B2, $70, $03, $61, $00, $FE, $DE, $41, $F9, $00, $FF, $DB, $66 ;0x2C0
	dc.b	$70, $02, $61, $00, $FE, $D2, $41, $F9, $00, $FF, $CE, $CE, $30, $3C, $0B, $D4, $E2, $48, $61, $00, $FE, $C2, $41, $F9, $00, $FF, $52, $B8, $30, $3C, $00, $E0 ;0x2E0
	dc.b	$E2, $48, $61, $00, $FE, $B2, $61, $00, $FE, $D2, $4C, $DF, $01, $01, $4E, $75, $61, $62, $79, $00, $48, $E7, $80, $80, $61, $00, $FE, $4E, $70, $02, $61, $00 ;0x300
	dc.b	$FE, $78, $41, $F9, $00, $FF, $CA, $6E, $70, $01, $61, $00, $FE, $48, $41, $F9, $00, $FF, $CA, $9E, $70, $03, $61, $00, $FE, $3C, $41, $F9, $00, $FF, $CA, $B2 ;0x320
	dc.b	$70, $03, $61, $00, $FE, $30, $41, $F9, $00, $FF, $DB, $66, $70, $02, $61, $00, $FE, $24, $41, $F9, $00, $FF, $CE, $CE, $30, $3C, $0B, $D4, $E2, $48, $61, $00 ;0x340
	dc.b	$FE, $14, $41, $F9, $00, $FF, $52, $B8, $30, $3C, $00, $E0, $E2, $48, $61, $00, $FE, $04, $4C, $DF, $01, $01, $4E, $75, $48, $E7, $F8, $40, $2F, $08, $48, $E7 ;0x360
	dc.b	$80, $80, $30, $3C, $00, $20, $61, $00, $FB, $AE, $22, $48, $4C, $DF, $01, $01, $20, $49, $70, $07, $42, $98, $51, $C8, $FF, $FC, $70, $01, $72, $01, $74, $26 ;0x380
	dc.b	$76, $1A, $38, $3C, $00, $43, $61, $00, $F3, $40, $33, $40, $00, $1E, $70, $1D, $72, $16, $74, $08, $76, $04, $78, $03, $61, $00, $F0, $44, $70, $04, $72, $03 ;0x3A0
	dc.b	$41, $FA, $03, $2C, $61, $00, $F6, $74, $70, $10, $72, $03, $41, $FA, $03, $98, $61, $00, $F6, $68, $70, $1C, $72, $03, $41, $FA, $04, $04, $61, $00, $F6, $5C ;0x3C0
	dc.b	$70, $1C, $72, $11, $34, $3C, $E5, $6B, $30, $7C, $C0, $00, $61, $00, $DE, $12, $70, $1E, $52, $42, $61, $00, $DE, $0A, $42, $69, $00, $14, $42, $69, $00, $16 ;0x3E0
	dc.b	$42, $69, $00, $18, $33, $7C, $00, $03, $00, $1A, $33, $7C, $00, $03, $00, $1C, $61, $00 ;0x400
