; ########################################################################################
; # Generated by the active disassembly feature of the Exodus emulation platform
; #
; # Creation Date:   2021-1-5 9:40:29
; # Analysis Region: 0x000038BE - 0x000038DC
; ########################################################################################

 org $000038BE

	ADDQ.w	#2, D6
	ADDA.w	#$0080, A2
	CMPA.w	#$E000, A2
	BNE.b	loc_000038D0
	MOVEA.w	#$F000, A2	;Predicted (Code-scan)
	BRA.b	loc_000038DA	;Predicted (Code-scan)
loc_000038D0:
	CMPA.w	#0, A2
	BNE.b	loc_000038DA
	MOVEA.w	#$DF00, A2	;Predicted (Code-scan)
loc_000038DA:
	MOVE.w	D4, D0
