; ########################################################################################
; # Generated by the active disassembly feature of the Exodus emulation platform
; #
; # Creation Date:   2021-1-23 9:45:00
; # Analysis Region: 0x00001E90 - 0x00001EFF
; ########################################################################################

 org $00001E90

	MOVEM.l	A2/D7/D6/D5/D4/D3/D2, -(A7)
	MOVEM.l	A0/D0, -(A7)
	MOVE.w	#$0080, D0
	BSR.w	*+$1C86
	MOVEA.l	A0, A2
	MOVEM.l	(A7)+, D0/A0
	ANDI.b	#$0F, D0
	ANDI.b	#$0F, D1
	MOVE.l	A2, -(A7)
	MOVE.l	A2, -(A7)
	MOVEQ	#7, D4
loc_00001EB4:
	MOVE.l	(A0)+, D3
	MOVEQ	#3, D5
loc_00001EB8:
	MOVEQ	#7, D6
	CLR.l	D7
loc_00001EBC:
	LSL.l	#4, D7
	LSL.l	#1, D3
	BCS.b	loc_00001EC6
	ADD.b	D1, D7
	BRA.b	loc_00001EC8
loc_00001EC6:
	ADD.b	D0, D7
loc_00001EC8:
	DBF	D6, loc_00001EBC
	MOVE.l	D7, (A2)+
	DBF	D5, loc_00001EB8
	DBF	D4, loc_00001EB4
	MOVEA.l	(A7)+, A2
	MOVEQ	#$0000001F, D4
loc_00001EDA:
	MOVE.l	(A2)+, (A1)+
	DBF	D4, loc_00001EDA
	MOVEA.l	(A7)+, A2
	MOVE.l	A0, -(A7)
	MOVEA.l	A2, A0
	BSR.w	*+$1CB0
	MOVEA.l	(A7)+, A0
	MOVEM.l	(A7)+, D2/D3/D4/D5/D6/D7/A2
	RTS
	MOVEM.l	A6/A5/A4/A3/A2/A1/A0/D2/D1/D0, -(A7)
	MOVEM.l	A0/D0, -(A7)
	MOVE.w	#$0080, D0
	dc.b	$61 ;0x0 (0x00001EFE-0x00001EFF, Entry count: 0x1) [Unknown data]
